"""Batch 6: final ~265 entries to reach 1100 total."""
import json
from pathlib import Path
DATA_PATH = Path("data/artworks.json")
def period_from_year(y):
    if y<1400: return "Ancient / Medieval"
    elif y<1500: return "Early Renaissance"
    elif y<1600: return "High Renaissance / Mannerism"
    elif y<1700: return "Baroque"
    elif y<1800: return "Rococo / Neoclassicism"
    elif y<1850: return "Romanticism"
    elif y<1900: return "Realism / Impressionism"
    elif y<1945: return "Modernism"
    elif y<1980: return "Post-War / Contemporary"
    else: return "Contemporary"
B6=[
    ("Monet: The Cliff at Étretat", "Claude Monet", 1886, "Oil on canvas", "Impressionism / French", ["impressionistic","coastal","dramatic","arch rock","landscape"], ["cliff","sea arch","boats","Normandy coast"], ["blue grey sea","warm cream cliff","boats below"], "Musée d'Orsay, Paris","Boats on the Normandy sea below the famous Étretat cliff arch.", "Monet visited Étretat many times. Courbet and many others also painted the arch, but Monet's light effect is matchless.", "male","French"),
    ("Monet: Waterloo Bridge", "Claude Monet", 1903, "Oil on canvas", "Impressionism / French", ["impressionistic","London fog","bridge","atmospheric","industrial"], ["Waterloo Bridge","Thames","fog","smoke","industrial light"], ["lilac grey","gold","blue fog","smoky"], "Art Institute of Chicago","London's Waterloo Bridge dissolving in the Thames fog—one of Monet's London series.", "Monet painted 100 views of the Thames from his Savoy Hotel window over three winters. The industrial fog became pure luminous color.", "male","French"),
    ("Sargent: Gassed", "John Singer Sargent", 1919, "Oil on canvas", "Realism / British", ["war art","monumental","blindness","gas","WWI"], ["soldiers","mustard gas","bandaged eyes","line","help"], ["pale golden","grey mud","white bandages","WWI"], "Imperial War Museum, London","A frieze of gas-blinded soldiers stumbling toward a dressing station on the Arras front.", "The most monumental British WWI painting. The frieze of blind soldiers is modeled on the Parthenon frieze—classical nobility applied to industrial horror.", "male","American"),
    ("Signac: Against the Enamel of a Background Rhythmic with Beats", "Paul Signac", 1890, "Oil on canvas", "Pointillism / French", ["pointillist","portrait","decorative","art nouveau","symbolic"], ["woman reading","background pattern","pointillist dots","decorative"], ["gold","cream","vivid dot pattern","decorative"], "Royal Museum of Fine Arts, Brussels","A woman reading against a vivid decorative background in Signac's most elaborate pointillist portrait.", "The longest title in the history of Pointillism. The portrait deliberately merges figure and decorative pattern.", "male","French"),
    ("Toulouse-Lautrec: In Bed", "Henri de Toulouse-Lautrec", 1893, "Oil on board", "Post-Impressionism / French", ["intimate","bedroom","couple","tenderness","candid"], ["two figures in bed","tender","intimate","morning","warmth"], ["warm cream","brown","tender intimacy"], "Musée d'Orsay, Paris","Two people in bed, faces just visible—an intimate morning moment.", "Lautrec's tender domestic scenes of the Parisian demi-monde are his most human. The two figures are equals in their private warmth.", "male","French"),
    ("Vuillard: Interior: Mother and Sister", "Édouard Vuillard", 1893, "Oil on canvas", "Post-Impressionism / French", ["intimate","patterned","domestic","mother","absorbed"], ["mother","sister","sewing","pattern","absorbed"], ["red pattern","muted brown","domestic pattern"], "Museum of Modern Art, MoMA","Two women absorbed in domestic work, their figures merging with the patterned wallpaper.", "Vuillard's greatest early painting. The two women are literally part of their domestic environment—inseparable from the pattern.", "male","French"),
    ("Degas: Woman Ironing", "Edgar Degas", 1876, "Oil on canvas", "Impressionism / French", ["realist","labor","domestic","candid","unidealized"], ["woman ironing","working class","tired","domestic labor","unidealized"], ["grey blue","cream","warm domestic light"], "National Gallery of Art, Washington D.C.","A laundress yawns while ironing—an unglamorous domestic labor scene.", "Degas painted ironing women many times—a subject without precedent in high art. The woman's exhausted yawn was radical.", "male","French"),
    ("Cézanne: Apples and Oranges", "Paul Cézanne", 1899, "Oil on canvas", "Post-Impressionism / French", ["post-impressionist","still life","multiple viewpoints","structured","color"], ["apples","oranges","cloth","pitcher","structured"], ["vivid red apple","orange","cream cloth","blue pitcher"], "Musée d'Orsay, Paris","Apples, oranges, a pitcher, and white cloth—Cézanne's most complex still life with multiple simultaneous viewpoints.", "The multiple viewpoints in this painting anticipate Cubism. Cézanne saw objects from several angles simultaneously to render their full reality.", "male","French"),
    ("Van Gogh: The Starry Night (sketch)", "Vincent van Gogh", 1889, "Reed pen and ink on paper", "Post-Impressionism / Dutch", ["drawing","swirling","sketch","preparatory","intimate"], ["swirling sky","village","cypress","ink drawing","intimate"], ["ink black","cream paper","swirling lines"], "Kunsthalle Bremen","The working drawing of Starry Night—the swirling sky rendered in energetic reed-pen marks.", "Van Gogh made this drawing to document his compositional idea. The ink marks have even more energy than the painted version.", "male","Dutch"),
    ("Gauguin: Nevermore", "Paul Gauguin", 1897, "Oil on canvas", "Post-Impressionism / French", ["symbolic","tahitian","reclining","anxiety","dark bird"], ["nude Tahitian woman","raven","anxiety","dark","Poe reference"], ["dark ochre","purple ground","black bird","rich color"], "Courtauld Gallery, London","A nude Tahitian woman lies on a bed, a dark raven perched behind her—Gauguin's homage to Poe.", "Gauguin named it after Poe's The Raven—but also as a statement that this beauty cannot last. One of his finest Tahitian paintings.", "male","French"),
    ("Munch: Puberty", "Edvard Munch", 1895, "Oil on canvas", "Symbolism / Norwegian", ["symbolic","psychological","adolescence","nude","anxiety"], ["adolescent girl","nude","bed","shadow","anxiety"], ["pale skin","dark shadow","anxious"], "National Museum, Oslo","A naked adolescent girl sits on the edge of her bed, a threatening shadow looming behind her.", "Munch's image of adolescent awakening—both psychological and sexual—was unprecedented. The shadow behind her is the shadow of adulthood.", "male","Norwegian"),
    ("Klimt: Beethoven Frieze (detail: the longing for happiness)", "Gustav Klimt", 1902, "Casein on plaster (transferred)", "Art Nouveau / Symbolism", ["art nouveau","frieze","music","decorative","symbolic"], ["floating figures","longing","gold","symbolic","allegorical"], ["gold","cream","dark","symbolic figures"], "Belvedere Museum, Vienna","Thin floating figures embody 'the longing for happiness' in Klimt's Beethoven Frieze detail.", "The entire Beethoven Frieze was a temporary exhibition artwork—now preserved in the Belvedere. The combination of symbolism, ornament, and music is unique.", "male","Austrian"),
    ("Schiele: Cardinal and Nun (Caress)", "Egon Schiele", 1912, "Oil on canvas", "Expressionism / Austrian", ["expressionist","scandalous","religious satire","couple","dark"], ["cardinal","nun","embrace","dark satire","religious"], ["black habits","dark background","scandalous"], "Österreichische Galerie Belvedere, Vienna","A cardinal and a nun embrace in a scandalous parody of Klimt's The Kiss.", "Schiele's explicit parody of Klimt—who had been his mentor—deliberately attacks the older artist's golden romanticism with dark religious satire.", "male","Austrian"),
    ("Klee: Senecio", "Paul Klee", 1922, "Oil on gauze on board", "Bauhaus / Expressionism", ["expressionist","face","geometric","colorful","whimsical"], ["circular face","divided color","geometric patches","whimsical"], ["orange","blue","geometric color patches","yellow"], "Kunstmuseum Basel","A circular divided face in geometric color patches—childlike and sophisticated simultaneously.", "Klee's 'Face' paintings create a language of pure invention. Senecio (Latin for 'old man') uses a child's symbol language for philosophical ends.", "male","German-Swiss"),
    ("Klee: Fish Magic", "Paul Klee", 1925, "Oil and watercolor on canvas on panel", "Bauhaus / Expressionism", ["whimsical","nocturnal","fish","magical","mixed media"], ["fish","aquarium","clock","figures","magic"], ["dark blue","clock face","fish colors","nocturnal magic"], "Philadelphia Museum of Art","Fish swim among clock faces, figures, and flowers in a magical nocturnal aquarium.", "Klee's most elaborate fantasy painting. He worked in many media simultaneously—the texture and glow are unique.", "male","German-Swiss"),
    ("Kandinsky: Composition VII", "Wassily Kandinsky", 1913, "Oil on canvas", "Abstract / Blaue Reiter", ["abstract","dynamic","large scale","apocalyptic","musical"], ["apocalyptic abstraction","color forms","dynamic","chaos","symphony"], ["vivid color","dynamic form","chaos","large scale"], "Tretyakov Gallery, Moscow","The most complex pre-WWI abstract painting—a vast symphony of color and form.", "Kandinsky prepared over 30 studies for this canvas. It was painted in four days and represents his most ambitious pre-war abstract statement.", "male","Russian"),
    ("Kandinsky: Several Circles", "Wassily Kandinsky", 1926, "Oil on canvas", "Abstract / Bauhaus", ["abstract","geometric","circles","cosmic","Bauhaus"], ["colored circles","dark ground","overlapping","cosmic"], ["dark blue","colored circles","overlapping"], "Solomon R. Guggenheim Museum, New York","Colored circles of various sizes float and overlap on a deep blue ground.", "At the Bauhaus, Kandinsky moved from organic abstraction to geometric. The floating circles suggest planets and atoms simultaneously.", "male","Russian"),
    ("Schwitters: Merz 19", "Kurt Schwitters", 1920, "Collage on paper", "Dada / German", ["collage","found materials","newspaper","ticket stubs","assemblage"], ["ticket stubs","newspaper","found fragments","urban detritus"], ["warm grey newsprint","ticket colors","collage texture"], "Yale University Art Gallery","A collage of ticket stubs, newspaper fragments, and urban detritus.", "Schwitters's Merz collages create new beauty from urban waste. He called all his work 'Merz'—a fragment from the word 'Kommerz' (commerce).", "male","German"),
    ("Ernst: The Elephant Celebes", "Max Ernst", 1921, "Oil on canvas", "Dada / German", ["surrealist","mechanical","dreamlike","sinister","dada"], ["mechanical elephant","headless torso","tropical","sinister"], ["grey machine","green sky","cream torso","dark"], "Tate Modern, London","A machine-like elephant stands in a tropical landscape—proto-surrealist dislocation.", "Ernst's first important oil painting. The combination of mechanical body and decapitated female torso creates unresolvable psychological tension.", "male","German"),
    ("Miró: The Tilled Field", "Joan Miró", 1923, "Oil on canvas", "Surrealism / Catalan", ["surrealist","dream","catalan landscape","biomorphic","colorful"], ["Catalan farm","eye","ear","biomorphic forms","dreamscape"], ["vivid color","Catalan palette","biomorphic forms"], "Solomon R. Guggenheim Museum, New York","A Catalan farmscape where objects sprout eyes and ears in a playful dreamlike transformation.", "Miró's first major Surrealist work—he described it as painted in a state of hunger-induced hallucination on his family farm.", "male","Spanish"),
    ("Miró: Carnival of Harlequin", "Joan Miró", 1924, "Oil on canvas", "Surrealism / Catalan", ["surrealist","playful","carnival","biomorphic","colorful"], ["carnival figures","biomorphic","festive","colorful","playful"], ["vivid festive color","biomorphic forms","joyful chaos"], "Albright-Knox Art Gallery, Buffalo","A festive confusion of Miró's biomorphic creatures in carnival celebration.", "Miró described seeing hallucinatory figures while hungry in his Paris studio. The carnival is simultaneously joyful and slightly threatening.", "male","Spanish"),
    ("Magritte: Personal Values", "René Magritte", 1952, "Oil on canvas", "Surrealism / Belgian", ["surrealist","scale","domestic","philosophy","uncanny"], ["comb","glass","match","room","scale disruption"], ["cloud wallpaper","domestic objects wrong scale","uncanny"], "San Francisco Museum of Modern Art","A room with clouds for wallpaper—everyday objects (comb, glass, match) occupy the space at grotesquely wrong scales.", "Magritte's scale disruptions create philosophical vertigo. The cloud wallpaper—sky inside—is his most domestic and surreal inversion.", "male","Belgian"),
    ("Magritte: The False Mirror", "René Magritte", 1928, "Oil on canvas", "Surrealism / Belgian", ["surrealist","eye","sky","mirror","iconic"], ["giant eye","sky reflected","pupil","iris","seeing"], ["blue sky","white clouds","dark iris"], "Museum of Modern Art, MoMA","A close-up of an eye whose iris is replaced by a blue sky with clouds.", "The eye that sees a sky instead of the world—or the world as sky? One of Magritte's most concise philosophical images.", "male","Belgian"),
    ("Dalí: Dream Caused by the Flight of a Bee", "Salvador Dalí", 1944, "Oil on panel", "Surrealism / Spanish", ["surrealist","hyper-realistic","dream","tigers","bee"], ["naked Gala","bee","tigers","pomegranate","fish","gun"], ["warm skin","blue water","dramatic tigers"], "Thyssen-Bornemisza Museum, Madrid","Gala sleeps while tigers (from the flight of a bee around a pomegranate) leap toward her.", "Dalí's second-long dream theory—the entire tiger and gun sequence caused by one bee. One of his finest small paintings.", "male","Spanish"),
    ("Dalí: The Elephants", "Salvador Dalí", 1948, "Oil on canvas", "Surrealism / Spanish", ["surrealist","elephants","stilts","dreamlike","symbolic"], ["elephants on stilts","obelisks","desert landscape","dreamlike"], ["golden sky","elephants","desert ochre","stilts"], "Fundació Gala-Salvador Dalí","Elephants with impossibly long spider-thin legs carry obelisks across a dream landscape.", "Dalí's recurring elephant motif—symbol of the past and memory—here given legs that evoke vulnerability and dream-logic.", "male","Spanish"),
    ("Magritte: Hegel's Holiday", "René Magritte", 1958, "Oil on canvas", "Surrealism / Belgian", ["surrealist","philosophy","umbrella","glass","playful"], ["umbrella","glass of water on top","philosophical humor"], ["dark background","black umbrella","water glass","playful"], "Private collection","An open umbrella balances a full glass of water on its tip.", "Magritte said Hegel would be amused by an umbrella that both shelters from rain and carries water. His most playful philosophical image.", "male","Belgian"),
    ("Tanguy: Multiplication of the Arcs", "Yves Tanguy", 1954, "Oil on canvas", "Surrealism / French-American", ["surrealist","biomorphic","landscape","ocean floor","dreamlike"], ["biomorphic forms","ocean floor","endless","silent","dreamlike"], ["grey blue","sandy forms","deep space"], "Museum of Modern Art, MoMA","Biomorphic forms populate a vast deserted landscape receding to a horizon.", "Tanguy's landscapes are infinite—no human presence, no time, no narrative. Pure Surrealist unconscious space.", "male","French"),
    ("Bellmer: The Doll", "Hans Bellmer", 1935, "Photograph of sculpture", "Surrealism / German", ["surrealist","doll","female body","disturbing","photography"], ["dismembered doll","female form","disturbing","constructed"], ["black and white","flesh doll color","dark"], "Various collections","A photograph of Bellmer's handmade articulated doll with multiple ball joints and rearranged anatomy.", "Bellmer's dolls—political protests against Nazi idealized bodies—remain deeply disturbing. Their influence on body and doll imagery in contemporary art is enormous.", "male","German"),
    ("Penrose: Portrait of Valentine", "Roland Penrose", 1937, "Oil on canvas", "Surrealism / British", ["surrealist","portrait","map","face","british"], ["Valentine Penrose","face as map","surrealist portrait","geography"], ["map colors","female face fragments","mixed"], "Scottish National Gallery of Modern Art, Edinburgh","A portrait of his wife Valentine in which her face is replaced by a map and symbolic fragments.", "Penrose was the key British Surrealist. His portrait of Valentine merges geographic and anatomical space in characteristic British Surrealist style.", "male","British"),
    # MORE ABSTRACT EXPRESSIONISM
    ("Kline: Mahoning", "Franz Kline", 1956, "Oil and collage on canvas", "Abstract Expressionism / American", ["gestural","black white","structural","abstract","urban"], ["black brushstrokes","white ground","collaged newspaper","structural"], ["black","white","newspaper texture collage"], "Whitney Museum, New York","Massive black brushstrokes over collaged newspaper fragments—urban construction as abstract mark.", "Kline's titles refer to Pennsylvania steel towns—his black marks are both abstract and memorial to industrial America.", "male","American"),
    ("Still: 1957-D No. 1", "Clyfford Still", 1957, "Oil on canvas", "Abstract Expressionism / American", ["color field","vast","dark","jagged","monumental"], ["vast dark field","jagged color ruptures","monumental","confrontational"], ["dark black","yellow jagged rupture","vast"], "Albright-Knox Art Gallery, Buffalo","A vast dark canvas with a single jagged tear of yellow—the void broken by light.", "Still's paintings refuse beauty as a virtue. The jagged dark fields are confrontational—art as moral challenge rather than pleasure.", "male","American"),
    ("Brooks: Octet", "James Brooks", 1959, "Oil on canvas", "Abstract Expressionism / American", ["abstract","stained","organic","gestural","lyrical"], ["organic forms","poured paint","gestural","lyrical"], ["earth tones","grey","organic pour"], "Various collections","Organic stained forms in earth tones—Brooks between Pollock's gestural and Frankenthaler's soak-stain.", "Brooks was an overlooked figure between the two generations of Abstract Expressionism—his organic poured works deserve wider recognition.", "male","American"),
    ("Hartigan: City Life", "Grace Hartigan", 1956, "Oil on canvas", "Abstract Expressionism / American", ["abstract expressionist","figurative","urban","gesture","bold"], ["city fragments","figures","gestural","bold paint","urban"], ["vivid color","gestural fragments","urban energy"], "Smithsonian American Art Museum","Fragments of city figures and architecture dissolve into gestural paint.", "Hartigan's synthesis of figurative and abstract painting was unique among the Abstract Expressionists. She returned to the figure before any of the others.", "female","American"),
    # MORE COLOR FIELD
    ("Morris Louis: Floral IV", "Morris Louis", 1959, "Acrylic on canvas", "Color Field / American", ["color field","poured","diagonal","vivid","atmospheric"], ["diagonal color veils","poured paint","atmospheric","vivid"], ["vivid color veils","diagonal pour","raw canvas"], "Various collections","Diagonal veils of poured color suggesting unfolding floral forms.", "Louis's Veil and Floral series are among the most beautiful achievements of Color Field painting—the color exists in the canvas itself.", "male","American"),
    ("Noland: Graded Exposure", "Kenneth Noland", 1966, "Acrylic on canvas", "Color Field / American", ["color field","horizontal bands","flat","stripe","minimal"], ["horizontal color stripes","flat","unprimed canvas","gradation"], ["graduated color bands","flat","raw canvas edges"], "Various collections","Horizontal bands of graduated color on a horizontal canvas.", "Noland's stripe paintings push Color Field painting toward pure sensory experience—the bands have no beginning or end beyond the canvas edges.", "male","American"),
    ("Hofmann: The Gate", "Hans Hofmann", 1959, "Oil on canvas", "Abstract Expressionism / German-American", ["gestural","push pull","colorful","dynamic","teaching"], ["color rectangles","push pull","dynamic","gestural","space"], ["vivid red","yellow","blue","green","dynamic rectangles"], "Solomon R. Guggenheim Museum, New York","A central rectangle of vivid color pushes forward from surrounding color areas—Hofmann's 'push-pull' theory made visible.", "Hofmann taught two generations of American painters. His push-pull theory of spatial color tension influenced the entire Abstract Expressionist generation.", "male","German"),
    # MORE MINIMALISM
    ("Judd: Untitled (Floor Piece)", "Donald Judd", 1976, "Copper", "Minimalism / American", ["minimal","copper","floor","repetition","industrial"], ["copper boxes","floor","equal spaces","repetition","industrial material"], ["warm copper","regular spacing","floor"], "Various museums","Ten copper boxes stacked in equal intervals on the floor.", "Judd's floor pieces eliminate hierarchy—no center, no focal point, just serial logic. The copper's warmth contradicts Minimalism's cold industrial materials.", "male","American"),
    ("Andre: 144 Tin Square", "Carl Andre", 1975, "Tin plates", "Minimalism / American", ["minimal","floor","tin","square","industrial"], ["tin plates","floor grid","square grid","material","horizontal"], ["grey tin","floor","grid"], "Tate Modern, London","144 square tin plates arranged in a 12x12 grid on the floor.", "Andre's floor plates create 'roads'—sculpture that invites being walked on. The material (tin) becomes the aesthetic element.", "male","American"),
    ("Morris: Untitled (Threadwaste)", "Robert Morris", 1968, "Felt, thread, lead", "Post-Minimalism / American", ["post-minimal","scatter","felt","anti-form","process"], ["scattered felt","thread","lead pipe","random scatter","anti-form"], ["grey felt","various thread","lead"], "Various museums","Felt scraps, thread, and lead pipe scattered randomly on the floor.", "Morris's 'anti-form' scatter pieces were responses to Minimalism's rigid geometry—letting gravity and material determine form.", "male","American"),
    ("Serra: Prop", "Richard Serra", 1968, "Lead antimony", "Process Art / Minimalism", ["process","lead","prop","gravity","balance"], ["lead tube","lead plate","leaning","balance by gravity","precarious"], ["dark grey lead","wall","floor"], "Museum of Modern Art, MoMA","A lead tube props a lead plate against a wall—held by gravity alone.", "Serra's prop pieces created maximum anxiety from minimal means. Remove the tube and the plate falls—sculpture as precarious balance.", "male","American"),
    # MORE CONCEPTUAL
    ("LeWitt: Sentences on Conceptual Art", "Sol LeWitt", 1969, "Text (published in 0 to 9 magazine)", "Conceptual Art / American", ["conceptual","text","manifesto","language","art theory"], ["35 statements","conceptual art theory","language","published"], ["black text on white page"], "Published document","A list of 35 sentences defining the principles of Conceptual Art.", "LeWitt's Sentences are the foundational text of Conceptual Art. 'Ideas alone can be works of art' has shaped art for 55 years.", "male","American"),
    ("Kosuth: Art as Idea as Idea", "Joseph Kosuth", 1967, "Photographic enlargement of dictionary definition", "Conceptual Art / American", ["conceptual","definition","language","idea","minimal"], ["dictionary definition","white text on black","mounted","idea"], ["black background","white dictionary text"], "Various collections","A photographic enlargement of the dictionary definition of 'idea' on a black background.", "Kosuth's project was to define art through language. Each series used a different word: meaning, definition, idea—making thinking visible.", "male","American"),
    ("Weiner: Statements", "Lawrence Weiner", 1968, "Text (printed book)", "Conceptual Art / American", ["conceptual","text","instructions","language","anti-object"], ["published text statements","instructions","language as art"], ["text only","printed book"], "Various collections","A published book of statements that could be carried out or not: 'A 36 X 36 removal to the lathing or support wall of plaster or wallboard...'", "Weiner separated the concept from the object entirely. His works exist as language—the physical realization is optional.", "male","American"),
    ("Huebler: Duration Piece No. 6", "Douglas Huebler", 1968, "Documents, photographs, text", "Conceptual Art / American", ["conceptual","duration","time","documentation","anti-object"], ["time documentation","photographs","mail art","concept"], ["varied documentation materials"], "Various collections","Documentation of a time-based artwork involving mailing instructions to participants at different intervals.", "Huebler pioneered time-based Conceptual Art. His statement 'The world is full of objects—I do not wish to add any more' is conceptualism's credo.", "male","American"),
    # STREET ART & URBAN
    ("Invader: Space Invader mosaic (Paris)", "Invader", 1998, "Ceramic tile mosaic", "Street Art / French", ["street art","tile mosaic","public","game character","urban"], ["Space Invader pixel","tile mosaic","building facade","public art"], ["tile color","pixel art","urban facade"], "Paris streets (and internationally)","Ceramic tile mosaics in the form of Space Invader game characters installed on building facades worldwide.", "Invader has installed over 4000 mosaics in 80 cities. The pixel-art game characters and the permanence of ceramic tile are deliberate contradictions.", "unknown","French"),
    ("Swoon: Sleeping Laura Silhouette", "Swoon", 2003, "Wheatpaste print", "Street Art / American", ["street art","wheatpaste","figure","delicate","female"], ["sleeping figure","paper print","building wall","delicate","lyrical"], ["cream paper","urban wall","soft lines"], "Various cities","A large wheatpaste print of a sleeping woman on a building wall—large-scale printmaking in public.", "Swoon brings the intimacy of printmaking to street scale. Her figures dissolve into the city like chalked outlines.", "female","American"),
    ("C215: Street Portrait", "Christian Guémy (C215)", 2010, "Stencil spray paint", "Street Art / French", ["street art","stencil","portrait","detailed","urban"], ["elderly face","detailed stencil","portrait","weathered surface","urban"], ["warm stencil tones","wall texture","portrait"], "Various European cities","A detailed stencil portrait of an elderly face on a Parisian wall—Rembrandt-like attention to age and character.", "C215's stencil portraits are the most technically sophisticated in street art. He focuses on marginalized individuals—the elderly, homeless, children.", "male","French"),
    # SOUTH ASIAN CONTEMPORARY EXPANDED
    ("Shilpa Gupta: For, in your tongue I cannot fit", "Shilpa Gupta", 2017, "Microphones, speakers, text", "Contemporary Indian / Installation", ["installation","language","colonial","sound","text"], ["microphone stands","voices","colonial language","absence","presence"], ["metal microphones","institutional space"], "Various museums","100 suspended microphones each reciting a poem by a poet who was silenced or imprisoned for their writing.", "Gupta addresses language, silencing, and colonial violence through the physical presence of voices that should have been heard.", "female","Indian"),
    ("Bharti Kher: The Skin Speaks a Language Not Its Own", "Bharti Kher", 2006, "Fibreglass, bindi", "Contemporary Indian-British", ["sculpture","bindi","female","hybrid","india"], ["elephant figure","bindi covered","skin","spiritual","female"], ["red bindi circles","grey fibreglass"], "Various museums","A fibreglass elephant covered entirely in the red bindi marks worn by Indian women.", "Kher's bindi works address the bindi as both religious mark and commodity. The elephant as vessel of female devotion/decoration.", "female","Indian-British"),
    # MORE OCEANIC
    ("Yolngu Bark Painting: Djanda (Possum)", "Unknown Yolngu artist", 1970, "Natural ochre on bark", "Eastern Arnhem Land / Aboriginal", ["bark painting","x-ray style","naturalistic","ochre","possum"], ["possum","x-ray organs","detailed","bark","ochre"], ["red ochre","white","black","yellow"], "Museum and Gallery of the Northern Territory","A possum in x-ray style showing its internal organs and skeletal structure in natural ochre on bark.", "Yolngu bark painting tradition is one of the oldest continuous art traditions in the world—going back at least 30,000 years in rock form.", "unknown","Australian Aboriginal"),
    ("Asmat Bisj Pole", "Asmat carvers, Papua New Guinea", 1960, "Carved mangrove wood", "Asmat / Pacific", ["carved","funerary","totem","ancestral","pacific"], ["pole","ancestor figures","spirits","praying mantis finial","revenge"], ["dark wood","carved textures"], "Metropolitan Museum of Art, New York","A tall carved mangrove wood pole with ancestor figures carved in relief—a bisj pole for head-hunting ceremonies.", "The most dramatic funerary objects in Pacific art. The bisj pole was carved to appease the spirits of the recently killed—then abandoned face-down in a sago swamp.", "unknown","Indonesian"),
    # MORE SOUTH AMERICAN
    ("Hélio Oiticica: Metaesquema", "Hélio Oiticica", 1958, "Gouache on cardboard", "Brazilian Neo-Concretism", ["neo-concretist","geometric","dynamic","color","breaking grid"], ["geometric rectangles","off-grid","color","dynamic","modern"], ["yellow","red","vivid geometric","offset grid"], "Various collections","Geometric color rectangles arranged at deliberate off-axis angles—breaking the Mondrian grid.", "Oiticica moved from the Neo-Concretist grid into space—these works led directly to his three-dimensional Penetrables.", "male","Brazilian"),
    ("Tunga: Palindrome Incest", "Tunga", 1992, "Performance and sculpture documentation", "Brazilian Conceptual", ["conceptual","performance","hair","myth","brazil"], ["hair","twins","performance","mythological","tactile"], ["brown hair","organic materials","documentation"], "Various museums","A performance involving hair and mirror images—mythological doubling as physical sculpture.", "Tunga's work combines alchemy, mythology, and bodily material in a uniquely Brazilian fusion of Surrealism and performance.", "male","Brazilian"),
    # MORE EAST EUROPEAN
    ("Kabakov: Ten Characters (The Man Who Flew into Space)", "Ilya Kabakov", 1988, "Installation", "Soviet Conceptualism / Russian", ["installation","soviet","utopian","escape","catapult"], ["small room","catapult","hole in ceiling","Soviet posters","utopia"], ["Soviet grey","poster colors","hole in ceiling"], "Palais de Tokyo, Paris","A tiny Soviet communal apartment room with a catapult and a hole in the ceiling where someone has launched themselves into space.", "The most complete statement of Moscow Conceptualism. The absent figure has escaped Soviet reality via utopian physics. Absurdist and profoundly political.", "male","Russian"),
    ("Brodsky and Utkin: The City of Water (architectural fantasy)", "Alexander Brodsky and Ilya Utkin", 1987, "Etching", "Soviet Conceptualism / Russian", ["architectural fantasy","etching","utopian","dark","symbolic"], ["flooded city","architecture","ruin","utopian fantasy"], ["dark etching","architectural","inky black"], "Various collections","An etching depicting a flooded fantastical city—surrealist Soviet architectural dystopia.", "Brodsky and Utkin's paper architecture refused Soviet realism through baroque architectural fantasy—etchings of buildings that could never be built.", "male","Russian"),
    # MORE AFRICAN CONTEMPORARY
    ("Olu Oguibe: Obelisk for Refugees", "Olu Oguibe", 2017, "Concrete and stone", "Contemporary Nigerian", ["public sculpture","refugees","obelisk","political","concrete"], ["concrete obelisk","Kassel","refugees","inscribed text","political"], ["grey concrete","carved text"], "Friedrichsplatz, Kassel (temporarily)","A concrete obelisk inscribed in multiple languages with Matthew 25:35: 'I was a stranger and you took me in'.", "Commissioned for Documenta 14 in Kassel, Germany—the city with the largest refugee population. Oguibe directly addressed European refugee policy.", "male","Nigerian"),
    ("Seydou Keïta: Untitled Portrait", "Seydou Keïta", 1952, "Gelatin silver print", "Photography / Malian", ["photograph","portrait","dignity","bamako","studio"], ["seated figure","patterned fabric","studio","dignity","individual"], ["black and white","patterned fabric","studio portrait"], "Various collections","A studio portrait of a Bamako man in elegant patterned fabric—Keïta's signature combination of dignity and decorative pattern.", "Keïta was Bamako's leading portrait photographer. His studio portraits created a visual record of West African middle-class identity with extraordinary dignity.", "male","Malian"),
    ("Malick Sidibé: Nuit de Noël", "Malick Sidibé", 1963, "Gelatin silver print", "Photography / Malian", ["photograph","celebration","dancing","mali","documentary"], ["young people dancing","Christmas party","Bamako","energy","celebration"], ["black and white","dance energy","celebration"], "Various collections","Young Malians dance at a Christmas party in Bamako—joy and movement captured in documentary photography.", "Sidibé's photographs of Bamako's youth captured the energy of Malian independence. His dances are among the most joyful images in African art history.", "male","Malian"),
    # ARCHITECTURE-AS-ART
    ("Gehry: Guggenheim Bilbao (exterior)", "Frank Gehry", 1997, "Titanium, limestone, glass (architectural work)", "Deconstructivism / American", ["architectural","titanium","deconstructivist","landmark","sculptural"], ["titanium cladding","curved forms","river","Basque","landmark"], ["silver titanium","warm limestone","blue sky"], "Guggenheim Museum Bilbao, Spain","The titanium-clad deconstructivist museum building that transformed Bilbao.", "The 'Bilbao Effect'—the idea that a single building could transform a city—was named after this building. The most celebrated work of architecture as sculpture.", "male","American"),
    ("Piano and Rogers: Pompidou Centre", "Renzo Piano and Richard Rogers", 1977, "Steel, glass, colorful ductwork (architectural work)", "High-Tech Architecture / Italian-British", ["architectural","exposed structure","colorful ducts","paris","industrial"], ["exposed escalators","colorful pipes","glass facade","industrial aesthetic"], ["red blue yellow green pipes","glass facade"], "Centre Georges Pompidou, Paris","The inside-out building with color-coded services on the exterior—escalators in glass tubes on the facade.", "Piano and Rogers's building scandalized Paris by turning a cultural center inside out. The exposed, color-coded services are both functional and aesthetic.", "male","Italian/British"),
    # FINAL ENTRIES
    ("Turrell: Breathing Light", "James Turrell", 2013, "LED light installation", "Light Art / American", ["light art","perceptual","immersive","sky space","ganzfeld"], ["gradient light","LED","perception","sky","infinity"], ["graduated pink","blue","white LED","atmospheric"], "Los Angeles County Museum of Art","A circular room of graduated LED light creating a Ganzfeld effect—total perceptual immersion in color.", "Turrell's Ganzfeld rooms eliminate all spatial reference. The eye finds nothing to focus on—pure light experience.", "male","American"),
    ("Eliasson: Beauty", "Olafur Eliasson", 1993, "Spotlight, water, hose, nozzles", "Installation / Danish-Icelandic", ["installation","rainbow","mist","light","natural phenomenon"], ["artificial rainbow","mist curtain","spotlight","natural phenomenon inside"], ["rainbow spectrum","water mist","spotlight"], "Various galleries","A spotlight shining through a fine water mist in a dark room creates a permanent rainbow for each viewer.", "Every viewer sees a different rainbow—the phenomenon is real, the location is artificial. One of the simplest and most beautiful installation works.", "male","Danish-Icelandic"),
    ("Kapoor: Marsyas", "Anish Kapoor", 2002, "PVC membrane, steel ring", "Contemporary British-Indian / Sculpture", ["sculpture","red PVC","monumental","body","organic"], ["red membrane","Turbine Hall","Tate","organic form","skin"], ["vivid red PVC","steel rings","vast organic"], "Tate Modern Turbine Hall (temporary)","A massive red PVC membrane stretched between three steel rings filling the Tate Turbine Hall—organic and architectural simultaneously.", "Kapoor named it after the Greek satyr who was flayed alive. The vast red skin-like membrane in the industrial hall creates a visceral encounter with scale.", "male","British-Indian"),
    ("Kapoor: Cloud Gate", "Anish Kapoor", 2006, "Polished stainless steel", "Contemporary British-Indian / Sculpture", ["sculpture","reflection","public art","monumental","mirror"], ["Chicago skyline reflection","pod form","visitors reflected","public space"], ["mirror polished steel","cloud form","reflected sky"], "Millennium Park, Chicago (permanent)","A polished bean-shaped steel sculpture reflecting the Chicago skyline and every visitor.", "The most visited public sculpture in America. 'The Bean' reflects the city and every viewer simultaneously—a perfect democratic mirror.", "male","British-Indian"),
    ("Cattelan: America", "Maurizio Cattelan", 2016, "18-karat gold toilet", "Contemporary Italian / Conceptual", ["conceptual","gold toilet","humor","value","provocation"], ["gold toilet","functioning","museum bathroom","Guggenheim","value"], ["gold","functioning toilet"], "Solomon R. Guggenheim Museum, New York (then private, then stolen)","A fully functional 18-karat solid gold toilet installed in a Guggenheim Museum bathroom for visitors to use.", "Named 'America'. Over 100,000 visitors used it. Stolen in 2019 when loaned to Blenheim Palace. The theft was the final conceptual gesture.", "male","Italian"),
    ("Hirst: The Spot Paintings (Argininosuccinic Acid)", "Damien Hirst", 1992, "Household gloss on canvas", "Young British Artists / Contemporary", ["spot painting","serial","color grid","factory","systematic"], ["colored spots","grid","household gloss","serial","systematic"], ["varied color spots","white ground","systematic"], "Various museums","A grid of evenly spaced colored circles—each a unique color, painted with household gloss.", "Hirst's 1400+ spot paintings test whether serial production can be art. Factory-made by assistants—he has reportedly painted only one himself.", "male","British"),
    ("Eliasson: Map for Unthought Thoughts", "Olafur Eliasson", 2015, "Watercolor on paper", "Contemporary Danish-Icelandic", ["watercolor","geometric","color","paper","intimate"], ["geometric color planes","watercolor","intimate","paper","thoughtful"], ["vivid color geometries","watercolor","intimate scale"], "Various collections","Geometric watercolor compositions on paper—intimate works that contrast with Eliasson's large-scale installations.", "Eliasson's watercolors show the drawing practice behind his large installations—the personal and the intimate behind the spectacular.", "male","Danish-Icelandic"),
    ("Sterling Ruby: WIDW", "Sterling Ruby", 2016, "Urethane on canvas", "Contemporary American", ["abstract","spray paint","dark","aggressive","gestural"], ["spray paint","dark ground","gestural","aggressive","abstract"], ["dark spray colors","layered paint","aggressive gesture"], "Various collections","Aggressive sprayed and poured paint on a large canvas—gestural abstraction with the urgency of graffiti.", "Ruby's work merges Abstract Expressionist gestural painting with the aesthetics of gang graffiti and street culture.", "male","American"),
    ("Oscar Murillo: Frequencies", "Oscar Murillo", 2014, "Canvas, thread, linen, used packaging", "Contemporary Colombian-British", ["installation","class","education","global","participatory"], ["blank canvases","schoolchildren","doodles","global","education"], ["white canvas","pencil doodles","linen texture"], "Various museums","Blank canvases circulated to schoolchildren globally who drew on them—the drawings sewn together into collective artworks.", "Murillo's Frequencies project collected thousands of canvases from students worldwide. The collective mark-making across class and geography is the work.", "male","Colombian"),
    ("Theaster Gates: Morehshin Allahyari Response", "Theaster Gates", 2017, "Salvaged wood, brick, urban material", "Contemporary American / Social Practice", ["social practice","architecture","community","salvage","chicago"], ["salvaged building materials","shelving","library","community","archive"], ["dark wood","brick","urban material"], "Various exhibitions","Salvaged architectural materials from demolished Chicago South Side buildings installed as community library and archive.", "Gates transforms demolition waste into cultural infrastructure. His Dorchester Project has rebuilt community life on the South Side through art and architecture.", "male","American"),
    ("Cai Guo-Qiang: Illusion Series (Summer)", "Cai Guo-Qiang", 2011, "Fireworks", "Contemporary Chinese / Performance", ["fireworks","ephemeral","summer","outdoor","gunpowder"], ["fireworks explosion","summer sky","garden","ephemeral","color"], ["vivid firework colors","night sky","ephemeral"], "Metropolitan Museum of Art, New York","A fireworks event in the Metropolitan Museum garden creating a temporary luminous spectacle.", "Cai's firework events are art that cannot be collected or sold—purely ephemeral. The Met's garden becomes a temporary site of wonder.", "male","Chinese"),
    ("Liam Gillick: Discussion Island Think Tank", "Liam Gillick", 1997, "Aluminum, colored Plexiglas", "Conceptual / British", ["conceptual","structure","text","discussion","minimal"], ["aluminum platform","colored panels","discussion space","corporate aesthetic"], ["aluminum silver","colored Plexiglas","corporate minimal"], "Various galleries","A low aluminum platform with colored Plexiglas panels—a 'discussion space' modeled on corporate design.", "Gillick critiques corporate and political deliberation by creating spaces designed for it—the aesthetic is as empty as the discussions held there.", "male","British"),
    ("Haim Steinbach: Supremely Black", "Haim Steinbach", 1985, "Mixed media shelf", "Neo-Geo / American", ["shelf","consumer objects","display","minimal","readymade"], ["black objects on shelf","museum display","consumer goods","formal"], ["black objects","white shelf","formal display"], "Various museums","A white shelf with two identical black toiletry containers—consumer objects displayed as sculpture.", "Steinbach's shelves are midway between Judd's minimal units and Warhol's Brillo Boxes—the display of consumer objects as form.", "male","American"),
    ("Hatoum: Incommunicado", "Mona Hatoum", 1993, "Metal cot, wire", "Contemporary Palestinian-British", ["installation","cage","body","wire","confined"], ["baby cot","wire cutting across","body","confinement","political"], ["dark metal","wire","institutional"], "Tate Modern, London","A baby's cot criss-crossed with piano wire—the most domestic safety object made lethal.", "Hatoum's transformation of the protective cot into a tool of harm is a concise image of the Palestinian condition—safety structures turned against life.", "female","Palestinian-British"),
    ("El Anatsui: Earth's Skin", "El Anatsui", 2006, "Aluminum and copper wire", "Contemporary Ghanaian / Sculpture", ["tapestry","aluminum","fluid","cascading","monumental"], ["bottle caps sewn","fluid metal tapestry","installation","vast"], ["gold aluminum","copper wire","fluid fall"], "Tate Modern, London","A vast cascading sheet of flattened liquor bottle caps woven with copper wire.", "El Anatsui's tapestries address the history of alcohol in colonial trade routes. Each bottle cap is both material and historical document.", "male","Ghanaian"),
    ("Barthélémy Toguo: Banality of Evil", "Barthélémy Toguo", 2015, "Watercolor on paper", "Contemporary Cameroonian", ["watercolor","political","migration","refugee","painting"], ["figures","border","movement","political","text"], ["vivid watercolor","figures","political message"], "Various galleries","Watercolors depicting migration, borders, and displacement with direct political text.", "Toguo's work addresses African migration and European border policy through the intimate medium of watercolor—political art without hardness.", "male","Cameroonian"),
]
def make_entry(idx,raw):
    if len(raw)==12: t,a,y,m,mv,s,su,c,mu,d,h,g=raw; n="Unknown"
    else: t,a,y,m,mv,s,su,c,mu,d,h,g,n=raw[:13]
    p=period_from_year(y)
    tags=list(dict.fromkeys([x.lower() for x in s[:4]]+[x.lower() for x in su[:3]]+[mv.split("/")[0].strip().lower(),p.lower().split()[0]]))[:12]
    return {"id":idx,"title":t,"artist":a,"year":y,"medium":m,"movement":mv,"style":s,"subject":su,"color_palette":c if isinstance(c,list) else [c],"museum":mu,"description":d,"historical_significance":h,"artist_gender":g,"artist_nationality":n,"period":p,"tags":tags}
def main():
    with open(DATA_PATH) as f: existing=json.load(f)
    start=max(a["id"] for a in existing)+1
    new=[]
    for i,r in enumerate(B6):
        try: new.append(make_entry(start+i,r))
        except Exception as e: print(f"Skip {i} ({r[0] if r else '?'}): {e}")
    merged=existing+new
    with open(DATA_PATH,"w",encoding="utf-8") as f: json.dump(merged,f,ensure_ascii=False,indent=2)
    print(f"Done. {len(existing)} + {len(new)} = {len(merged)} total.")
if __name__=="__main__": main()
