"""Batch 3: adds ~500 more artworks to reach ~1000+ total."""
import json
from pathlib import Path

DATA_PATH = Path("data/artworks.json")

def period_from_year(year):
    if year < 1400: return "Ancient / Medieval"
    elif year < 1500: return "Early Renaissance"
    elif year < 1600: return "High Renaissance / Mannerism"
    elif year < 1700: return "Baroque"
    elif year < 1800: return "Rococo / Neoclassicism"
    elif year < 1850: return "Romanticism"
    elif year < 1900: return "Realism / Impressionism"
    elif year < 1945: return "Modernism"
    elif year < 1980: return "Post-War / Contemporary"
    else: return "Contemporary"

BATCH3 = [
    # ── ADDITIONAL ITALIAN RENAISSANCE & BAROQUE ──────────────────────────
    ("Leonardo da Vinci: Lady with an Ermine", "Leonardo da Vinci", 1490, "Oil on walnut panel", "High Renaissance / Italian", ["portrait","sfumato","psychological","intimate","animal"], ["Cecilia Gallerani","ermine","hands","gaze","fur"], ["dark background","cream skin","white ermine","dark red sleeve"], "Czartoryski Museum, Kraków", "A young woman holds a white ermine and turns her head alertly, her eyes focused on something outside the picture.", "One of only four surviving Leonardo portraits. The ermine is a pun on Cecilia's lover Lodovico Sforza's nickname. Unique among Renaissance portraits for its psychological dynamism.", "male", "Italian"),
    ("Leonardo da Vinci: Salvator Mundi", "Leonardo da Vinci", 1500, "Oil on walnut panel", "High Renaissance / Italian", ["sfumato","religious","gesture","symbolic","mystery"], ["Christ","blessing gesture","crystal orb","frontal","dark"], ["dark background","blue robe","gold","crystal orb"], "Private collection (sold 2017)", "Christ as Savior of the World in Renaissance dress raises his right hand in blessing and holds a crystal sphere representing the cosmos.", "The most expensive painting ever sold ($450.3 million, 2017). Its attribution has been debated. The crystal orb — which should distort the image behind it but doesn't — is a deliberate theological decision.", "male", "Italian"),
    ("Caravaggio: The Supper at Emmaus", "Caravaggio", 1601, "Oil on canvas", "Baroque / Italian", ["chiaroscuro","biblical","dramatic","realistic","tenebrism"], ["Christ","disciples","inn","bread","revelation"], ["dark","warm light","dramatic","food"], "National Gallery, London", "The risen Christ blesses bread at an inn. Two disciples recognize him and recoil in astonishment.", "Caravaggio's tenebrism and psychological realism transformed European painting. The disciples' explosive gestures burst beyond the frame.", "male", "Italian"),
    ("Artemisia Gentileschi: Self-Portrait as the Allegory of Painting", "Artemisia Gentileschi", 1638, "Oil on canvas", "Baroque / Italian", ["self-portrait","allegorical","dynamic","female artist","baroque"], ["woman painting","palette","allegory","self-portrait","dark background"], ["dark","warm flesh","green bodice","palette colors"], "Royal Collection, London", "Gentileschi portrays herself actively painting, her body in dynamic motion — the only self-portrait in the history of art showing an artist actually at work.", "The most radical self-portrait before the modern era. Using her own body to depict the Allegory of Painting (a female figure), she claims her own status as artist.", "female", "Italian"),
    ("Giovanni Battista Tiepolo: The Triumph of Venus", "Giovanni Battista Tiepolo", 1762, "Fresco ceiling", "Rococo / Italian", ["rococo","ceiling fresco","mythological","luminous","theatrical"], ["Venus","clouds","cherubs","sky","triumph"], ["sky blue","gold","cream","theatrical light"], "Würzburg Residenz, Germany", "Venus and her attendants soar through a sky-blue ceiling surrounded by putti and allegorical figures in the finest Rococo ceiling painting.", "Tiepolo's Würzburg ceiling frescoes are the summit of Rococo ceiling painting — vast, luminous, and apparently weightless.", "male", "Italian"),
    ("Andrea Mantegna: The Dead Christ (Lamentation)", "Andrea Mantegna", 1483, "Tempera on canvas", "Early Renaissance / Italian", ["foreshortening","dramatic","religious","innovative","perspective"], ["dead Christ","foreshortened","mourners","stone slab","feet"], ["grey stone","flesh","dark background","cloth"], "Pinacoteca di Brera, Milan", "The dead Christ lies in extreme foreshortening, feet facing the viewer, mourning figures at the sides.", "The most daring perspectival experiment of the Renaissance. Mantegna's radical foreshortening makes the viewer a mourner at the foot of Christ's bier.", "male", "Italian"),
    ("Sandro Botticelli: The Mystical Nativity", "Sandro Botticelli", 1501, "Tempera on canvas", "Early Renaissance / Florentine", ["symbolic","golden","apocalyptic","unusual","religious"], ["nativity","three zones","devils","angels","olive wreaths"], ["gold","blue","red","symbolic zones"], "National Gallery, London", "A three-tiered nativity: angels above in gold, the Holy Family in the center, demons being subdued below.", "Botticelli's most unusual and personal work, painted during the Savonarolan crisis. Contains a cryptic Greek inscription suggesting an apocalyptic reading.", "male", "Italian"),
    ("Pontormo: The Deposition from the Cross", "Jacopo da Pontormo", 1528, "Oil on panel", "Mannerism / Italian", ["mannerist","pastel colors","compressed","swirling","elegant"], ["deposition","Christ","figures","compressed space","pastel"], ["pale blue","pink","green","pastel colors","swirling"], "Santa Felicita, Florence", "Figures in impossibly elegant poses support the dead Christ in pastel colors with no ground line — a weightless, compressed composition.", "The supreme example of Italian Mannerism. The acidic pastel palette and anti-gravitational composition are entirely deliberate departures from Renaissance harmony.", "male", "Italian"),
    ("Bronzino: Allegory with Venus and Cupid", "Agnolo Bronzino", 1545, "Oil on panel", "Mannerism / Italian", ["mannerist","erotic","allegorical","cold color","complex"], ["Venus","Cupid","allegory","symbolic figures","masks"], ["cold flesh","blue","elaborate","allegorical figures"], "National Gallery, London", "Venus and Cupid embrace at the center while allegorical figures of Folly, Time, Pleasure, and Deceit surround them.", "The most complex and sensually provocative Mannerist painting. The figures of Deceit (a girl with a serpent tail) and Jealousy (tearing her hair) are unforgettable.", "male", "Italian"),
    ("Tiepolo: Apollo and the Continents (detail: Europe)", "Giovanni Battista Tiepolo", 1752, "Fresco", "Rococo / Italian", ["rococo","ceiling","allegorical","continents","theatrical"], ["Apollo","Europe","ceiling","allegory","classical figures"], ["sky blue","gold","warm light","celestial"], "Würzburg Residenz, Germany", "The personification of Europe enthroned under Apollo's chariot with classical figures and architecture — one panel of the great staircase ceiling fresco.", "The largest ceiling fresco in the world (677 square meters). Each continent's personification incorporates ethnographic and mythological figures from Tiepolo's imagination.", "male", "Italian"),

    # ── ADDITIONAL DUTCH & FLEMISH ─────────────────────────────────────────
    ("Jan Steen: Doctor's Visit", "Jan Steen", 1663, "Oil on canvas", "Dutch Golden Age", ["genre","humorous","domestic","moralizing","detailed"], ["sick young woman","doctor","lovesickness","domestic","comedy"], ["warm","brown","gold","domestic"], "Mauritshuis, The Hague", "A young woman sits drooping with an indeterminate illness while a doctor checks her pulse — the real diagnosis is lovesickness.", "Steen's doctor paintings embed sly humor in their medical setting. The lovesick patient was a well-known genre moralizing against female weakness.", "male", "Dutch"),
    ("Pieter Brueghel the Younger: Peasant Wedding", "Pieter Brueghel the Younger", 1610, "Oil on panel", "Flemish Baroque", ["genre","festive","peasant","detailed","copy"], ["wedding feast","peasants","tables","food","dancing"], ["warm","earth tones","crowded tables","festive"], "Various collections", "A long table crowded with peasants eating and drinking at an outdoor wedding feast, after the composition of his father.", "Brueghel the Younger made many copies and variants of his father's compositions. The peasant wedding feast became a popular Flemish genre type.", "male", "Flemish"),
    ("Adriaen van Ostade: The Painter in His Workshop", "Adriaen van Ostade", 1663, "Oil on panel", "Dutch Golden Age", ["genre","interior","artist studio","humble","naturalistic"], ["painter","studio","light","easel","everyday"], ["warm golden","earthy","humble studio light"], "Gemäldegalerie, Dresden", "A peasant painter works in a humble workshop with light falling from a single window.", "Van Ostade specialized in the humble interiors of artisans and peasants. His studio self-portrait subverts the grand tradition of studio paintings.", "male", "Dutch"),
    ("Gerrit Dou: The Night School", "Gerrit Dou", 1665, "Oil on panel", "Dutch Golden Age / Fijnschilder", ["fijnschilder","candlelight","detailed","nighttime","intimate"], ["schoolroom","candle","night","children","study"], ["candlelight gold","dark","warm light","intimate"], "Rijksmuseum, Amsterdam", "Children study by candlelight in an intimate night scene of extraordinary painted detail.", "Dou was Rembrandt's first student and founder of the Leiden Fijnschilder (fine painter) tradition — extreme microscopic detail in small formats.", "male", "Dutch"),
    ("Samuel van Hoogstraten: View Down a Corridor (Trompe-l'oeil)", "Samuel van Hoogstraten", 1662, "Oil on canvas", "Dutch Golden Age", ["trompe-l'oeil","illusionistic","perspective","corridor","trick"], ["corridor","door","broom","dog","spatial illusion"], ["warm grey","red","brown","spatial recession"], "Dyrham Park, Gloucestershire", "A painted corridor recedes illusionistically into the distance, with a broom and a dog visible at the far end.", "The most ambitious Dutch trompe-l'oeil painting. Hoogstraten's peepboxes and illusionistic paintings were celebrated throughout Europe.", "male", "Dutch"),
    ("Willem Claesz. Heda: Still Life with Glasses and Tobacco", "Willem Claesz. Heda", 1644, "Oil on panel", "Dutch Golden Age / Still Life", ["still life","monochromatic","tonal","glass","detailed"], ["glasses","pewter","overturned cup","tablecloth","monochrome"], ["silver grey","cream","glass reflection","pewter"], "Rijksmuseum, Amsterdam", "Overturned pewter cup, wine glass, bread, and smoking materials on a table in tonal silver-grey.", "Heda's 'banquet pieces' (ontbijt) reduce color to near-monochrome to focus on material texture — glass, pewter, fabric. A summit of tonal painting.", "male", "Dutch"),
    ("Jan Davidsz. de Heem: Vase of Flowers with a Curtain", "Jan Davidsz. de Heem", 1670, "Oil on canvas", "Dutch Golden Age / Still Life", ["still life","flowers","opulent","detailed","insects"], ["roses","tulips","insects","parrot","curtain"], ["vivid red","white","green","dark background"], "Kunsthistorisches Museum, Vienna", "An extravagant vase of flowers with birds, insects, and a stone niche — botanically impossible (flowers from all seasons together).", "De Heem combined flowers from all seasons in a single impossible bouquet. The insects and bird are memento mori. The most opulent Dutch flower painting.", "male", "Dutch"),

    # ── ADDITIONAL FRENCH PAINTING ─────────────────────────────────────────
    ("Jacques-Louis David: Napoleon in His Study", "Jacques-Louis David", 1812, "Oil on canvas", "Neoclassicism / French", ["portrait","official","propagandistic","interior","detailed"], ["Napoleon","uniform","study","candle","map"], ["dark","cream","gold epaulettes","candlelight"], "National Gallery of Art, Washington D.C.", "Napoleon in his study at 4am, just risen from the desk, his sword at his side and the Code Napoléon on the table.", "David painted Napoleon's ideal: the ruler as tireless worker. The guttering candle and the clock show it is 4:13am — Napoleon has worked all night.", "male", "French"),
    ("Jean-Baptiste-Siméon Chardin: The House of Cards", "Jean-Baptiste-Siméon Chardin", 1737, "Oil on canvas", "French Realism", ["domestic","quiet","childhood","concentrated","intimate"], ["boy","card house","concentration","domestic interior"], ["warm cream","brown","red card table","quiet"], "National Gallery of Art, Washington D.C.", "A boy concentrates on building a house of cards at a table — a study of youth and concentration in warm domestic light.", "Chardin's genre paintings of childhood have a quiet dignity that makes them as moving as his still lifes. Diderot considered him the greatest living painter.", "male", "French"),
    ("Fragonard: The Reader", "Jean-Honoré Fragonard", 1772, "Oil on canvas", "Rococo / French", ["rococo","light","intimate","absorbed","woman"], ["young woman","reading","absorbed","yellow dress","light"], ["yellow dress","soft light","cream","intimate"], "National Gallery of Art, Washington D.C.", "A young woman in yellow sits entirely absorbed in her book, oblivious to the viewer's gaze.", "One of Fragonard's most intimate small paintings. The subject's complete absorption creates a Vermeer-like quality of private space.", "male", "French"),
    ("Gustave Moreau: Jupiter and Semele", "Gustave Moreau", 1895, "Oil on canvas", "Symbolism / French", ["symbolist","opulent","jeweled","mythological","visionary"], ["Jupiter","Semele","divine light","mythological","elaborate"], ["gold","dark","jewel tones","supernatural light"], "Musée Gustave Moreau, Paris", "Jupiter appears to Semele in his full divine form — too much for mortal eyes. Every surface is encrusted with symbolic decoration.", "Moreau's most elaborate painting, worked on for years. The accumulated symbolic detail creates a system as complex as a medieval cathedral.", "male", "French"),
    ("Pierre Puvis de Chavannes: The Sacred Grove", "Pierre Puvis de Chavannes", 1884, "Oil on canvas", "Symbolism / French", ["symbolist","classical","mural-like","serene","pale"], ["muses","sacred grove","classical figures","pale landscape","meditative"], ["pale blue","cream","muted green","classical quiet"], "Art Institute of Chicago", "Classically draped muses gather in a pale grove of trees in a dreamlike landscape of classical serenity.", "Puvis's pale, idealized murals influenced Gauguin, Seurat, and the Symbolists. His decorative classicism created a new public painting for secular spaces.", "male", "French"),

    # ── ADDITIONAL GERMAN ART ─────────────────────────────────────────────
    ("Caspar David Friedrich: The Sea of Ice", "Caspar David Friedrich", 1824, "Oil on canvas", "Romanticism / German", ["sublime","catastrophic","cold","dramatic","landscape"], ["ice floes","shipwreck","arctic","crushed ship","dramatic"], ["blue grey ice","cold white","dark ship remains"], "Kunsthalle Hamburg", "Jagged ice floes have crushed and buried a ship — only the bow visible above the frozen sea in cold grey light.", "Friedrich's most apocalyptic painting. The crushing of the ship by nature's indifferent force is the Romantic sublime at its most extreme.", "male", "German"),
    ("Caspar David Friedrich: Moonrise over the Sea", "Caspar David Friedrich", 1822, "Oil on canvas", "Romanticism / German", ["sublime","nocturnal","meditative","moonlight","back-turned figures"], ["two figures","rocky coast","ships","moon","sea"], ["dark blue","white moon","silver sea","dark figures"], "Alte Nationalgalerie, Berlin", "Two back-turned figures sit on coastal rocks watching ships sail by moonlight. The sky shows both sun and moon.", "The most concentrated of Friedrich's Rückenfigur (back-turned figure) compositions. We look with the figures, not at them — the classic Romantic device.", "male", "German"),
    ("Albrecht Dürer: Young Hare", "Albrecht Dürer", 1502, "Watercolor and gouache on paper", "Northern Renaissance / German", ["naturalistic","detailed","botanical","watercolor","precise"], ["hare","fur","animal study","precise","delicate"], ["warm brown","white fur","paper ground"], "Albertina, Vienna", "A watercolor study of a hare with every individual hair rendered in precise observation from nature.", "The most meticulous animal study of the Renaissance. Dürer's botanical and animal watercolors were centuries ahead of their time in scientific observation.", "male", "German"),
    ("Albrecht Dürer: Melencolia I", "Albrecht Dürer", 1514, "Engraving", "Northern Renaissance / German", ["engraving","symbolic","allegorical","complex","dark humor"], ["winged figure","compass","sphere","sleeping dog","magic square"], ["black","white","crosshatch"], "Various collections", "A winged allegorical figure sits in melancholy surrounded by the tools of geometry and craft — compass, sphere, ladder, magic square.", "One of the most analyzed images in Western art. Hundreds of symbolic interpretations proposed over centuries. The magic square is the first in European art.", "male", "German"),
    ("Friedrich Overbeck: Italia und Germania", "Friedrich Overbeck", 1828, "Oil on canvas", "Nazarene / German", ["nazarene","friendship","classical allegory","German-Italian","idealized"], ["two women","friendship","Italia","Germania","idealized"], ["warm","blue","red","classical dress","friendship"], "Neue Pinakothek, Munich", "Two young women in classical dress — Italia and Germania — sit side by side, their friendship an allegory of German-Italian artistic brotherhood.", "The defining image of the Nazarene Brotherhood, the German equivalent of the Pre-Raphaelites. A manifesto for the renewal of religious painting through Italian models.", "male", "German"),

    # ── ADDITIONAL SPANISH ART ─────────────────────────────────────────────
    ("Francisco de Zurbarán: Saint Francis in Meditation", "Francisco de Zurbarán", 1640, "Oil on canvas", "Spanish Baroque", ["religious","chiaroscuro","meditative","brown monk","symbolic"], ["Francis of Assisi","skull","meditation","brown robe","dark"], ["dark","brown robe","dramatic light","skull"], "National Gallery, London", "Saint Francis kneels in meditative prayer, hooded in brown, holding a skull, bathed in dramatic spotlight.", "Zurbarán's monks are the most austere spiritual images in Baroque painting — sculptural, direct, and absolutely focused on the divine.", "male", "Spanish"),
    ("El Greco: The Adoration of the Shepherds", "El Greco", 1612, "Oil on canvas", "Mannerism / Spanish", ["mannerist","elongated","spiritual","night scene","luminous"], ["nativity","shepherds","divine light","elongated figures","night"], ["night blue","gold","elongated figures","supernatural light"], "Museo del Prado, Madrid", "The infant Christ emits supernatural light in this night nativity — elongated figures swirling in El Greco's distinctive ecstatic manner.", "One of El Greco's last and most personal works — painted for his own burial chapel. The light source is the Christ child himself.", "male", "Greek-Spanish"),
    ("Francisco Goya: Colossus (The Giant)", "Francisco Goya", 1808, "Oil on canvas", "Romanticism / Spanish", ["romantic","mysterious","giant","war","symbolism"], ["giant figure","landscape","panic","small figures","storm"], ["dark","grey storm","looming giant"], "Museo del Prado, Madrid", "A giant figure rises above a panic-stricken landscape, seen from behind. Armies and civilians scatter in all directions.", "Long attributed to Goya, now questioned. Whether by Goya or not, it is the most powerful symbolic image of the Napoleonic war in Spain.", "male", "Spanish"),

    # ── ADDITIONAL 19TH CENTURY ────────────────────────────────────────────
    ("John Constable: Dedham Vale", "John Constable", 1802, "Oil on canvas", "Romanticism / British", ["landscape","pastoral","english","naturalistic","early"], ["Dedham Vale","green fields","trees","Suffolk","cloud sky"], ["green","blue sky","white clouds","earthy"], "Scottish National Gallery, Edinburgh", "A view of Dedham Vale in Suffolk — the 'Constable Country' he painted throughout his career — in fresh naturalistic green.", "Constable's early Dedham Vale established his lifelong subject. His dedication to painting his home landscape was radical in an era of classical idealism.", "male", "British"),
    ("John Everett Millais: Mariana", "John Everett Millais", 1851, "Oil on canvas", "Pre-Raphaelitism / British", ["pre-raphaelite","detailed","melancholic","interior","symbolic"], ["Mariana","embroidery","stained glass","woman","back stretch"], ["blue","red stained glass","gold","purple"], "Tate Britain, London", "Mariana stretches her back at an embroidery frame in a richly decorated medieval interior — waiting forever for Angelo.", "Millais's second major Pre-Raphaelite painting after Ophelia. The botanical and textile detail is extraordinary; the psychological mood of waiting is perfectly captured.", "male", "British"),
    ("Dante Gabriel Rossetti: Beata Beatrix", "Dante Gabriel Rossetti", 1872, "Oil on canvas", "Pre-Raphaelitism / British", ["pre-raphaelite","symbolic","trance","memorial","romantic"], ["Beatrix Portinari","Florence","trance","dove","death"], ["gold","green","red dove","trance state"], "Tate Britain, London", "Beatrice enters a death-trance, a dove delivering poppies (opium/death) to her cupped hands, as Florence shimmers in the background.", "Painted as a memorial to Rossetti's wife Elizabeth Siddal, who died of laudanum overdose. A fusion of Dante's Beatrice and personal grief.", "male", "British"),
    ("Edward Burne-Jones: The Golden Stairs", "Edward Burne-Jones", 1880, "Oil on canvas", "Pre-Raphaelitism / Aestheticism", ["pre-raphaelite","aesthetic","procession","classicism","decoration"], ["women on stairs","flowing dresses","musical instruments","procession"], ["grey stone","white dresses","gold instruments","pale skin"], "Tate Britain, London", "A procession of beautiful young women in white descend a curving staircase carrying musical instruments.", "The summit of the Aesthetic Movement. Burne-Jones said the picture meant nothing — it was pure visual beauty, form, and color. Whistler agreed.", "male", "British"),
    ("Lord Frederic Leighton: Flaming June", "Lord Frederic Leighton", 1895, "Oil on canvas", "Academic Art / Victorian", ["academic","sleeping figure","orange","sensuous","classical"], ["sleeping woman","orange dress","chair","heat","beauty"], ["vivid orange","gold","blue sea","sensuous form"], "Museo de Arte de Ponce, Puerto Rico", "A woman in a fiery orange dress sleeps in a curled position in the summer heat, against a deep blue sea.", "Among the most sensuous Victorian paintings. The acidic orange of the silk was so vivid it was thought to have faded from an even brighter original.", "male", "British"),
    ("Franz von Lenbach: Portrait of Bismarck", "Franz von Lenbach", 1890, "Oil on canvas", "Academic Realism / German", ["portrait","official","dark","psychological","powerful"], ["Bismarck","dark background","intense","power","state"], ["dark brown","cream skin","formal dress"], "Various collections", "Bismarck in three-quarter view against a dark ground, his face registering the iron will of the 'Iron Chancellor'.", "Lenbach painted Bismarck many times — the definitive visual image of Germany's most powerful 19th-century figure.", "male", "German"),

    # ── ADDITIONAL 20TH CENTURY ────────────────────────────────────────────
    ("Tamara de Lempicka: Young Woman in Green", "Tamara de Lempicka", 1927, "Oil on canvas", "Art Deco / Polish", ["art deco","sleek","glamorous","woman","modern"], ["young woman","green scarf","sleek forms","glamour","modern"], ["green","flesh","silver","art deco geometry"], "Centre Pompidou, Paris", "A stylishly dressed young woman in green looks sideways, her smooth form rendered in Art Deco geometric planes.", "De Lempicka is the supreme painter of Art Deco glamour. Her sleek, machine-polished style defined 1920s modernity.", "female", "Polish"),
    ("Balthus: The Room", "Balthus (Balthasar Klossowski)", 1952, "Oil on canvas", "Figurative / French", ["figurative","controversial","interior","sunlight","classical"], ["girl","window","light","cat","domestic"], ["golden sunlight","cream","warm domestic"], "Private collection", "A young figure lies in brilliant sunlight in a sparse room while another figure pulls back a curtain.", "Balthus's paintings of young girls have been consistently controversial. His classical, Courbet-influenced technique is undeniable.", "male", "French"),
    ("Lucian Freud: Naked Portrait", "Lucian Freud", 1972, "Oil on canvas", "Figurative / British", ["figurative","unflinching","nude","intimate","realist"], ["woman lying","nude","vulnerable","unflinching","studio"], ["flesh","cream sheet","warm light"], "Tate Modern, London", "A woman lies fully nude on a studio bed in the most unsparing of Freud's early portraits.", "Freud's early nudes already show his total refusal of idealization. The subject's combination of vulnerability and self-possession is typical.", "male", "German-British"),
    ("Balthus: The Street", "Balthus (Balthasar Klossowski)", 1933, "Oil on canvas", "Figurative / French", ["figurative","flat","paris","uncanny","street scene"], ["Paris street","figures","dreamlike","static","uncanny"], ["flat grey","brown","ordinary street","strange stillness"], "Museum of Modern Art, MoMA", "A Paris street scene with figures who move with eerie, flat, puppet-like precision in an uncanny urban tableau.", "Balthus's early urban paintings have a dreamlike, de Chirico quality. The Street scandalized when exhibited — a man was groping a girl's skirt.", "male", "French"),
    ("Edvard Munch: The Madonna", "Edvard Munch", 1894, "Oil on canvas", "Expressionism / Norwegian", ["symbolist","expressionist","female","eros and death","haunting"], ["naked woman","closed eyes","ecstasy","death","frame of sperm"], ["dark red","flesh","blue","dark swirling"], "National Museum, Oslo", "A naked woman with closed eyes in a moment of ecstasy — her expression hovering between pleasure and death. The lithograph version has a frame of sperm and a fetal figure.", "Munch's 'Madonna' collapses the sacred and erotic. The original frame had sperm images and a small fetal figure — entirely removed in most reproductions.", "male", "Norwegian"),
    ("Edvard Munch: Ashes", "Edvard Munch", 1895, "Oil on canvas", "Symbolism / Norwegian", ["symbolist","melancholic","aftermath","figure","dark"], ["couple","after sex","shame","forest","aftermath"], ["dark green forest","white dress","dark suit","desolation"], "National Museum, Oslo", "A woman in white stands with unbound hair while a man covers his face in the forest after a sexual encounter — an aftermath of shame and desolation.", "Munch's most psychologically subtle treatment of the 'love-death' theme. The couple are estranged the moment after union.", "male", "Norwegian"),
    ("James Ensor: Intrigue", "James Ensor", 1890, "Oil on canvas", "Expressionism / Belgian", ["carnival","masks","crowd","color","grotesque"], ["masked figures","intrigue","crowd","social satire","Flemish carnival"], ["vivid red","yellow","masks","dense crowd"], "Royal Museum of Fine Arts, Antwerp", "A crowd of masked and costumed carnival figures press against each other in a scene of cheerful menace.", "Ensor's masked crowds are predecessors of Expressionism. His Flemish carnival tradition combined with sardonic social critique makes him unique.", "male", "Belgian"),
    ("Emil Nolde: Dance Around the Golden Calf", "Emil Nolde", 1910, "Oil on canvas", "Expressionism / German", ["expressionist","wild","religious","colorful","ecstatic"], ["dancing figures","golden calf","biblical","ecstasy","vivid color"], ["orange","red","dark","vivid dance"], "Staatsgalerie Stuttgart", "Wild figures dance in ecstatic frenzy around a golden calf in explosive expressionist color.", "Nolde's religious paintings were denounced by the Nazis as degenerate — the opposite of his own anti-Semitic politics. The paintings transcend him.", "male", "German"),
    ("August Macke: Lady in Green Jacket", "August Macke", 1913, "Oil on canvas", "Expressionism / German", ["expressionist","colorful","flat","urban","optimistic"], ["woman walking","green jacket","vibrant color","park","figures"], ["vivid green","cream","flat color","optimistic"], "Museum Ludwig, Cologne", "A woman in a vivid green jacket walks through a park with children in a colorful, optimistic Expressionist scene.", "Macke was the most lyrical of the Blaue Reiter artists — his color is joyful where Kirchner's is anguished. Killed in WWI at 27.", "male", "German"),
    ("Franz Marc: The Large Blue Horses", "Franz Marc", 1911, "Oil on canvas", "Expressionism / Blaue Reiter", ["expressionist","animal","blue","spiritual","curved"], ["blue horses","curved forms","harmonious","spiritual","vivid"], ["deep blue","red","green","harmonious curves"], "Walker Art Center, Minneapolis", "Three large blue horses curve together in harmonious animal communion, painted in pure non-naturalistic color.", "Marc used color spiritually: blue = male spirituality, yellow = feminine joy, red = violence. His horse paintings are among the most beloved of Expressionism.", "male", "German"),
    ("Franz Marc: Fate of the Animals", "Franz Marc", 1913, "Oil on canvas", "Expressionism / Blaue Reiter", ["expressionist","apocalyptic","animal","fragmented","dramatic"], ["animals","forest","fragmented","fire","apocalypse"], ["dark","red","blue","fragmented diagonal"], "Kunstmuseum Basel", "Animals are crushed and fragmented by falling trees and fire in a pre-war vision of apocalypse.", "Painted one year before WWI. Marc wrote on the back 'And all being is flaming suffering.' He was killed at Verdun in 1916.", "male", "German"),
    ("Alexei von Jawlensky: Schokko with Red Hat", "Alexei von Jawlensky", 1909, "Oil on cardboard", "Expressionism / Russian-German", ["expressionist","bold color","portrait","German","Russian"], ["woman","red hat","bold color","direct gaze","flat forms"], ["red","vivid blue","green","bold outlines"], "Private collection", "A young woman with a red hat and vivid green eyes looks boldly outward in flat, heavily outlined color.", "Jawlensky's portraits reach toward a spiritual simplification — large eyes, flat color, bold outline — that culminates in his meditation-head series.", "male", "Russian"),
    ("Alexei von Jawlensky: Abstract Head: Sunrise", "Alexei von Jawlensky", 1926, "Oil on board", "Expressionism / Abstract", ["abstract","spiritual","simplified head","color","meditative"], ["simplified face","color","meditation","spiritual","abstract"], ["orange","cream","dark outlines","glowing"], "Various collections", "A simplified face — two lines for nose and brow, oval for eyes — glows in orange and gold against a dark ground.", "Jawlensky's late 'Meditation' series reduced the face to pure spiritual essence — a mandala of simplified human presence.", "male", "Russian"),

    # ── ADDITIONAL SURREALISM ─────────────────────────────────────────────
    ("Paul Delvaux: Sleeping Venus", "Paul Delvaux", 1944, "Oil on canvas", "Surrealism / Belgian", ["surrealist","dreamlike","nocturnal","nude","train station"], ["Venus sleeping","train station","classical figures","night","Belgian"], ["blue night","pale skin","classical architecture","gas lights"], "Tate Modern, London", "A nude Venus sleeps in a train station at night while ghosts of classical figures wander and a skeleton gestures.", "Delvaux's dreamscapes combine the erotic, the nocturnal, and the uncanny in a Belgian art nouveau space. Magritte called him the most surrealist Belgian artist.", "male", "Belgian"),
    ("Kay Sage: Tomorrow Is Never", "Kay Sage", 1955, "Oil on canvas", "Surrealism / American", ["surrealist","architectural","desolate","geometric","metaphysical"], ["draped forms","architectural spaces","mysterious","absence"], ["grey","cream draped","shadow blue","desolate"], "Metropolitan Museum of Art, New York", "Draped geometric forms rise in a desolate architectural space — the drapes suggest both covered furniture and shrouded figures.", "Sage was one of the few American-born Surrealists. Her geometric architectural Surrealism has a uniquely desolate quality unlike any European counterpart.", "female", "American"),
    ("Meret Oppenheim: Object (Luncheon in Fur)", "Meret Oppenheim", 1936, "Cup, saucer and spoon covered in fur", "Surrealism / Swiss", ["object","fur","uncanny","teacup","surrealist sculpture"], ["teacup","saucer","spoon","fur","uncanny"], ["brown fur","domestic white beneath"], "Museum of Modern Art, MoMA", "A teacup, saucer, and spoon lined with the fur of a Chinese gazelle.", "The most concise Surrealist object ever made. The fur's tactile implications in relation to drinking transform a domestic object into something disturbing.", "female", "Swiss"),
    ("Dorothea Tanning: Birthday", "Dorothea Tanning", 1942, "Oil on canvas", "Surrealism / American", ["surrealist","female","fantasy","doorways","creature"], ["woman","open doorways","strange creature","fantasy","halls"], ["dark red","cream","strange creature colors"], "Philadelphia Museum of Art", "Tanning in a fantastical jacket stands before infinite doorways opening on each other, a strange winged creature at her feet.", "The painting that made Tanning famous after Max Ernst saw it on his studio visit. The infinite doorways suggest the Surrealist unconscious.", "female", "American"),
    ("Roberto Matta: The Earth Is a Man", "Roberto Matta", 1942, "Oil on canvas", "Surrealism / Chilean", ["surrealist","cosmic","energetic","geological","large scale"], ["geological forms","energy fields","cosmic","landscape"], ["deep space","orange","blue","explosive"], "Art Institute of Chicago", "Vast geological and cosmic forces erupt in a field of pure energy — the Earth as sentient organism.", "Matta introduced a cosmic geological surrealism to New York that influenced the Abstract Expressionists directly. Pollock acknowledged his influence.", "male", "Chilean"),

    # ── ADDITIONAL ABSTRACT EXPRESSIONISM ────────────────────────────────
    ("Bradley Walker Tomlin: Number 20", "Bradley Walker Tomlin", 1949, "Oil on canvas", "Abstract Expressionism / American", ["abstract","calligraphic","white","gestural","sign-like"], ["white calligraphy","dark ground","marks","signs","abstract"], ["white","dark brown","calligraphic marks"], "Museum of Modern Art, MoMA", "White calligraphic marks float on a dark ground — somewhere between writing and pure gestural mark-making.", "Tomlin's synthesis of Cubist structure and gestural expression created some of the most elegant Abstract Expressionist works.", "male", "American"),
    ("James Brooks: Prana", "James Brooks", 1956, "Oil on canvas", "Abstract Expressionism / American", ["abstract","stained","organic","lyrical","earthy"], ["poured paint","organic form","color field","earthy","lyrical"], ["ochre","grey blue","cream","organic shapes"], "Various collections", "Poured and stained organic forms in earthy ochre and grey suggest landscape and organic life.", "Brooks was among the first to pour and stain paint before Frankenthaler, creating organic abstract fields between Pollock and Color Field.", "male", "American"),
    ("Conrad Marca-Relli: Seated Figure", "Conrad Marca-Relli", 1953, "Canvas collage on canvas", "Abstract Expressionism / American", ["collage","figurative abstraction","canvas on canvas","powerful","monochromatic"], ["figure","torn canvas","monochromatic","gestural","collage"], ["cream","dark grey","torn canvas textures"], "Various collections", "A seated figure assembled from torn pieces of canvas collaged onto canvas — figure and abstraction in one.", "Marca-Relli's torn-canvas collages occupy a unique position between Abstract Expressionism and Cubism.", "male", "American"),

    # ── POP ART INTERNATIONAL ─────────────────────────────────────────────
    ("Richard Hamilton: Just What Is It That Makes Today's Homes So Different, So Appealing?", "Richard Hamilton", 1956, "Collage", "Pop Art / British", ["pop art","collage","consumer culture","irony","first pop"], ["bodybuilder","female","television","consumer goods","modern home"], ["vivid consumer color","collage fragments","flat"], "Kunsthalle Tübingen", "A bodybuilder and a model in a living room crammed with consumer goods — the founding work of British Pop Art.", "The first 'Pop Art' image — the term was coined about this work. Hamilton defined Pop's subject matter: consumer goods as the new gods.", "male", "British"),
    ("Roy Lichtenstein: Whaam!", "Roy Lichtenstein", 1963, "Acrylic on canvas (two panels)", "Pop Art / American", ["pop art","comic book","war","onomatopoeia","bold"], ["fighter jet","missile","explosion","comic book","WHAAM!"], ["red","yellow","blue","Ben-Day dots","black outline"], "Tate Modern, London", "A fighter jet fires a missile; in the right panel the target explodes with the word 'WHAAM!'. Taken directly from a comic book.", "Lichtenstein's two-panel war comic is Pop Art's most spectacular painting. The Ben-Day dot technique transforms commercial illustration into monumental painting.", "male", "American"),
    ("Roy Lichtenstein: Drowning Girl", "Roy Lichtenstein", 1963, "Oil and acrylic on canvas", "Pop Art / American", ["pop art","comic book","female distress","ironic","bold"], ["drowning woman","waves","thought bubble","Brad","distress"], ["blue water","pink face","thought bubble text","Ben-Day"], "Museum of Modern Art, MoMA", "A woman drowns with a thought bubble reading 'I don't care! I'd rather sink than call Brad for help!'", "Lichtenstein transforms the melodrama of romance comics into monumental painting. The ironic emotional overstatement is entirely deadpan.", "male", "American"),
    ("James Rosenquist: F-111", "James Rosenquist", 1965, "Oil on canvas (86-panel)", "Pop Art / American", ["pop art","panoramic","war","consumer culture","large scale"], ["F-111 jet","spaghetti","girl under hair dryer","atomic cloud","consumer goods"], ["vivid consumer colors","orange","blue","white"], "Museum of Modern Art, MoMA", "The F-111 fighter-bomber runs the entire length of a 26-meter canvas, overlaid with consumer images — spaghetti, a girl under a dryer, an atomic blast.", "The longest Pop Art painting. A critique of the military-industrial complex wrapped in consumer imagery. Intended to wallpaper a room.", "male", "American"),
    ("Tom Wesselmann: Great American Nude #57", "Tom Wesselmann", 1964, "Assemblage and oil on canvas", "Pop Art / American", ["pop art","assemblage","nude","consumer","american"], ["nude figure","flat","american flag","consumer goods","assemblage"], ["red white blue","flat flesh","stars and stripes"], "Whitney Museum, New York", "A simplified nude figure in an interior assembled from photographs, patterns, and flat color — American consumerism as erotic landscape.", "Wesselmann's Great American Nudes combine the traditional reclining nude with the American consumer environment in an audacious conflation.", "male", "American"),
    ("Claes Oldenburg: Floor Cake", "Claes Oldenburg", 1962, "Synthetic polymer paint on canvas filled with foam rubber and cardboard", "Pop Art / Swedish-American", ["soft sculpture","food","pop art","oversized","floor piece"], ["giant cake","soft","food","floor sculpture","domestic"], ["cream","pastel colors","soft form"], "Museum of Modern Art, MoMA", "A giant slice of cake made of canvas and foam rubber lies on the floor.", "Oldenburg's soft sculptures transform hard objects into soft ones and ordinary objects into monuments. Floor Cake was the first.", "male", "Swedish-American"),

    # ── MINIMALISM EXPANDED ───────────────────────────────────────────────
    ("Robert Morris: Untitled (L-Beams)", "Robert Morris", 1965, "Painted plywood (later fiberglass)", "Minimalism / American", ["minimal","geometric","L-shape","three positions","space"], ["L-shaped beams","three orientations","space","perception"], ["grey painted surface","simple form"], "Solomon R. Guggenheim Museum, New York", "Three identical L-shaped plywood beams in three different orientations — one upright, one lying flat, one balanced on two ends.", "Morris demonstrated that the same form looks completely different depending on its orientation. Fundamental to understanding how context changes perception.", "male", "American"),
    ("Carl Andre: Lever", "Carl Andre", 1966, "137 firebricks in a row", "Minimalism / American", ["minimal","floor","linear","bricks","horizontal"], ["single row of bricks","floor","horizontal","industrial","simple"], ["red-brown brick","floor"], "National Gallery of Canada, Ottawa", "137 firebricks laid end-to-end in a single horizontal row on the floor — 'sculpture as place', not as form.", "Andre extended from stacks to rows. He said: 'I am concerned with the properties of the material, not the properties of me.' Sculpture as pure place.", "male", "American"),
    ("Sol LeWitt: Wall Drawing #46", "Sol LeWitt", 1970, "Pencil on wall", "Conceptual / Minimalism", ["conceptual","wall drawing","instructions","systematic","geometric"], ["diagonal lines","wall","pencil","instructions","systematic"], ["pencil grey","white wall"], "Various institutions", "All combinations of two lines crossing at right angles drawn in pencil directly on a white wall according to written instructions.", "LeWitt separated concept from execution — the instructions ARE the artwork. Anyone can execute it. This challenges every assumption about artistic authorship.", "male", "American"),
    ("Eva Hesse: Hang Up", "Eva Hesse", 1966, "Acrylic on cloth over wood, steel", "Post-Minimalism / American", ["post-minimal","absurdist","steel loop","fabric","humor"], ["fabric-wrapped frame","long steel loop","empty","absurdist","humorous"], ["grey cloth","steel wire","empty space"], "Art Institute of Chicago", "A large fabric-wrapped rectangular frame with a long steel rod looping out from one corner — functionless, absurd.", "Hesse called it 'the most ridiculous structure I have ever seen'. The comic futility of the looping rod is deliberate. A critique of Minimalism's seriousness.", "female", "American"),
    ("Richard Serra: One Ton Prop (House of Cards)", "Richard Serra", 1969, "Hot rolled lead antimony", "Process Art / Minimalism", ["sculpture","lead","gravity","process","balance"], ["four lead plates","leaning","balanced by gravity","gravity","precarious"], ["dark grey lead"], "Museum of Modern Art, MoMA", "Four massive lead plates leaned against each other, held in place only by gravity — no welds or fasteners.", "Serra began pouring and propping lead as a direct process. The four plates balance in pure tension — removing one plate would collapse the whole.", "male", "American"),
    ("Bruce Nauman: The True Artist Helps the World by Revealing Mystic Truths", "Bruce Nauman", 1967, "Neon tubing", "Conceptual / American", ["neon","text","conceptual","irony","artist statement"], ["neon text","spiral","statement","artist role","irony"], ["warm blue-pink neon","dark gallery"], "Philadelphia Museum of Art", "A neon spiral sign reading 'The True Artist Helps the World by Revealing Mystic Truths' — both sincere and ironic.", "Nauman made this as his first window sign, modeled on a bar neon sign. The statement is simultaneously a genuine credo and a joke about artistic pretension.", "male", "American"),
    ("On Kawara: Today (Dec. 1, 1978)", "On Kawara", 1978, "Liquitex on canvas", "Conceptual / Japanese", ["conceptual","date painting","language","time","austere"], ["date","white text","grey ground","systematic","daily"], ["dark grey ground","white painted date"], "Various collections", "The date 'DEC. 1, 1978' painted in white on a dark grey ground.", "Kawara painted today's date every day he worked — over 2000 paintings since 1966. If he couldn't finish it in one day, he destroyed it.", "male", "Japanese"),

    # ── PROCESS ART & EARTH ART ───────────────────────────────────────────
    ("Andy Goldsworthy: Rowan Leaves and Holes", "Andy Goldsworthy", 1987, "Rowan leaves arranged on stone", "Land Art / British", ["land art","ephemeral","natural materials","circle","site specific"], ["rowan leaves","circle","holes","stone","temporary"], ["red orange leaves","grey stone","natural patterns"], "Documentation photograph", "Rowan leaves arranged in an interlocking pattern around natural holes in a stone, photographed and allowed to disperse.", "Goldsworthy works with natural materials and gravity. His works are inherently temporary; only the photograph survives.", "male", "British"),
    ("Richard Long: A Line Made by Walking", "Richard Long", 1967, "Photograph of grass flattened by walking", "Land Art / British", ["land art","walking","minimal","photograph","body"], ["line in grass","walking","body","documentation","simple"], ["green grass","grey flattened stripe"], "Tate Modern, London", "A photograph of a straight line in long grass made by repeatedly walking back and forth.", "Long's first major land art work — one of the simplest and most radical. The body moving through landscape as the medium of art.", "male", "British"),
    ("Nancy Holt: Sun Tunnels", "Nancy Holt", 1976, "Concrete tunnels in desert", "Land Art / American", ["land art","astronomical","desert","concrete","light"], ["four tunnels","Utah desert","solstice","star holes","light beams"], ["concrete grey","desert gold","light beams"], "Great Basin Desert, Utah (permanent)", "Four large concrete cylinders in the Utah desert aligned to the summer and winter solstice sunrise and sunset, with star-pattern holes.", "Holt created a monument to astronomical time in the American desert. The tunnels frame the landscape and mark the passage of cosmic time.", "female", "American"),

    # ── NEO-GEO & APPROPRIATION ───────────────────────────────────────────
    ("Jeff Koons: Three Ball Total Equilibrium Tank", "Jeff Koons", 1985, "Glass tank, distilled water, sodium chloride, three basketballs", "Neo-Geo / American", ["neo-geo","basketball","equilibrium","tank","conceptual"], ["basketballs","suspended","water tank","equilibrium","science"], ["clear water","orange basketballs","steel tank"], "Private collection", "Three basketballs suspended at exact mid-point in a tank of sodium chloride solution — neither rising nor sinking.", "Koons's most conceptually pure work. The equilibrium is precise — temperature changes can disturb it. About the moment of perfect balance.", "male", "American"),
    ("Sherrie Levine: After Walker Evans", "Sherrie Levine", 1981, "Photograph (rephotography)", "Appropriation Art / American", ["appropriation","rephotography","authorship","original","conceptual"], ["Great Depression farmer wife","rephotography","Walker Evans copy","authorship"], ["black and white photograph"], "Various collections", "Photographs of Dorothea Lange and Walker Evans's Depression-era documentary photographs, re-photographed without alteration.", "Levine's rephotography attack on originality and male artistic authority launched the Pictures Generation. 'Who owns an image?' asked with precise force.", "female", "American"),
    ("Richard Prince: Untitled (Cowboy)", "Richard Prince", 1989, "Chromogenic print (rephotography)", "Appropriation Art / American", ["appropriation","cowboy","marlboro man","american myth","rephotography"], ["Marlboro cowboy","western landscape","rephotographed","american myth"], ["western blue sky","earth tones","rephotography quality"], "Solomon R. Guggenheim Museum, New York", "A Marlboro cigarette advertisement rephotographed and enlarged — the cowboy as pure American myth.", "Prince's Cowboys expose the power of advertising images to create mythology. The work was at the center of copyright law debates for decades.", "male", "American"),

    # ── YBA & BRITISH CONTEMPORARY ────────────────────────────────────────
    ("Tracey Emin: My Bed", "Tracey Emin", 1998, "Mattress, bedding, objects", "Young British Artists", ["installation","autobiography","bed","confessional","objects"], ["unmade bed","vodka bottles","stained sheets","personal objects"], ["cream sheets","personal detritus","bedroom"], "Tate Modern, London", "The artist's actual unmade bed with used tissues, empty vodka bottles, and personal debris from a depressive episode.", "Exhibited at the Turner Prize, 1999. Two performance artists had sex in the bed at the Tate. Emin's raw autobiography defined YBA confessionalism.", "female", "British"),
    ("Jake & Dinos Chapman: Great Deeds Against the Dead", "Jake & Dinos Chapman", 1994, "Fibreglass, mixed media", "Young British Artists", ["sculpture","horror","goya reference","war","grotesque"], ["mutilated figures","tree","war atrocity","after Goya"], ["flesh","grey","tree brown","horror"], "Various collections", "Life-sized fibreglass figures of mutilated and impaled soldiers — a three-dimensional realization of Goya's Disasters of War print.", "The Chapmans make Goya's printed atrocities real and physical. Their sculpture escalates the horror of war imagery into tangible presence.", "male", "British"),
    ("Sam Taylor-Wood: Pietà", "Sam Taylor-Wood", 2001, "C-print photograph", "Contemporary British", ["photograph","religious","nude","male body","devotion"], ["man cradling another man","pietà","male nude","contemporary reworking"], ["warm flesh","dark background","studio"], "Various collections", "Two men in a pietà composition — one supporting the other's body — in a contemporary reworking of the Renaissance lamentation.", "Taylor-Wood uses the pietà format (also used by Mapplethorpe) to explore male devotion, physical care, and mourning in the AIDS era.", "female", "British"),

    # ── ADDITIONAL SOUTH AMERICAN ─────────────────────────────────────────
    ("Lygia Clark: Bichos (Creatures)", "Lygia Clark", 1960, "Hinged aluminum panels", "Neo-Concretism / Brazilian", ["kinetic","sculpture","participatory","hinged","interactive"], ["aluminum panels","hinged","creature","interactive","movement"], ["silver aluminum","geometric hinged"], "Various museums", "Hinged aluminum panels that can be folded and unfolded by the viewer into unlimited configurations — a 'living organism' of metal.", "Clark's Bichos (Creatures) require viewer participation to exist. They launch Brazilian Neo-Concretism and participatory art simultaneously.", "female", "Brazilian"),
    ("Hélio Oiticica: Parangolé Cape 18", "Hélio Oiticica", 1968, "Fabric, plastic, burlap, paint", "Neo-Concretism / Brazilian", ["participatory","wearable art","color","performance","carnival"], ["cape","wearable","samba","color","movement"], ["vivid color","fabric","wearable"], "Various museums", "A multilayered fabric cape worn and danced in — art only exists when worn and moved by the body.", "Oiticica's Parangolés (capes/banners) must be worn to exist. He brought samba dancers from Rio's favelas into the art space. Art as lived experience.", "male", "Brazilian"),
    ("Antonio Dias: Nota Sobre a Morte Inesperada (Note on an Unexpected Death)", "Antonio Dias", 1965, "Acrylic, vinyl emulsion on canvas", "Neo-Concretism / Brazilian", ["pop art","social commentary","political","flat","dark"], ["flat figures","crime scene","violence","outline","political"], ["black","cream","red","flat comic style"], "Museum of Modern Art, Rio de Janeiro", "Flat comic-book-style figures in a crime scene or violent event rendered in black, cream, and red.", "Dias's work confronts the violence of Brazilian military dictatorship through pop imagery. Among the most politically radical Brazilian art of the 1960s.", "male", "Brazilian"),

    # ── ADDITIONAL JAPANESE CONTEMPORARY ─────────────────────────────────
    ("Yayoi Kusama: Infinity Mirror Room — Phalli's Field", "Yayoi Kusama", 1965, "Mirrors, stuffed cotton forms", "Installation / Japanese", ["installation","repetition","infinity","mirrors","dots"], ["mirror room","stuffed phalli","polka dots","infinite repetition"], ["white with red dots","mirror infinity"], "Various museums (re-exhibited)", "A mirror room filled with soft white stuffed fabric protrusions covered in red polka dots, multiplied to infinity.", "Kusama's first infinity room — the obsessive repetition mirrors her psychological condition. Polka dots and infinity rooms became her trademark.", "female", "Japanese"),
    ("Yoshitomo Nara: Knife Behind Back", "Yoshitomo Nara", 2000, "Acrylic on canvas", "Neo-Pop / Japanese", ["neo-pop","child figure","cute but sinister","blade","japanese"], ["child","big eyes","knife behind back","cute and dark","japanese"], ["cream","dark background","childlike"], "Various collections", "A large-eyed child with a hidden knife behind their back stares with an ambiguous expression.", "Nara's child figures are simultaneously cute and threatening. They embody the rage beneath Japanese social conformity.", "male", "Japanese"),
    ("Motohiko Odani: Rompers", "Motohiko Odani", 2003, "Video installation", "Contemporary Japanese", ["video","body","grotesque","transformation","japanese"], ["horse-headed figure","landscape","movement","hybrid body"], ["earthy naturalistic","uncanny"], "Various museums", "Video of a figure in a horse-head mask running through a landscape — human and animal in uncanny combination.", "Odani's work explores the transformation of the body through mythology, desire, and horror in a uniquely Japanese aesthetic framework.", "male", "Japanese"),

    # ── ADDITIONAL INDIAN & SOUTH ASIAN ──────────────────────────────────
    ("Raza: Saurashtra", "S.H. Raza", 1983, "Acrylic on canvas", "Indian Abstract / Contemporary", ["abstract","bindu","meditative","color field","india"], ["bindu point","radiating patterns","geometric","spiritual"], ["deep red","black","gold","radiating circles"], "Tate Modern, London", "Concentric circles radiate from a central black bindu (point) in deep red and gold — a cosmological meditation.", "Raza's Bindu series developed the ancient Hindu cosmological concept of the origin point into pure abstract painting.", "male", "Indian"),
    ("Bhupen Khakhar: Yayati", "Bhupen Khakhar", 1987, "Oil on canvas", "Indian Modernism / Figurative", ["figurative","mythological","gay identity","indian","narrative"], ["Yayati figure","old age","youth","mythology","personal"], ["warm ochre","Indian palette","figurative"], "Tate Modern, London", "The mythological king Yayati, who exchanged his old age for his son's youth, rendered in Khakhar's distinctive Indian figurative style.", "Khakhar's use of Indian mythology to explore identity and aging is uniquely personal and political. He was diagnosed HIV-positive around this time.", "male", "Indian"),

    # ── ADDITIONAL CHINESE ──────────────────────────────────────────────
    ("Fang Lijun: Series 2 No. 2", "Fang Lijun", 1992, "Oil on canvas", "Cynical Realism / Chinese", ["cynical realism","bald figures","humor","political","large scale"], ["bald men","yawning","political","humor","nihilism"], ["blue sky water","bald flesh","large scale"], "Various collections", "Oversized bald-headed figures yawn and grin in a blue void — a cynical response to post-Tiananmen disillusion.", "Cynical Realism's defining image. The bald yawning man became the visual symbol of post-1989 Chinese nihilism and disenchantment.", "male", "Chinese"),
    ("Liu Xiaodong: Hotbed No. 1", "Liu Xiaodong", 2005, "Oil on canvas", "Chinese Realism / Figurative", ["realist","contemporary","social","documentary","figurative"], ["construction workers","sleeping","tile","labor","china"], ["warm flesh","earth","contemporary realistic"], "Various collections", "Chinese construction workers sleep together on a concrete floor in their working clothes.", "Liu Xiaodong's documentary-style oil paintings capture the lives of workers, migrants, and ordinary people in contemporary China with unflinching realism.", "male", "Chinese"),

    # ── ADDITIONAL MIDDLE EASTERN & NORTH AFRICAN ─────────────────────────
    ("Dia al-Azzawi: Sabra and Shatila Massacre", "Dia al-Azzawi", 1982, "Mixed media on paper", "Contemporary Iraqi", ["political","expressionist","tragedy","massacre","arab"], ["massacre","screaming figures","dark","political","arabic calligraphy"], ["dark red","black","white pain","fragmented"], "Various collections", "Anguished figures in dark expressionist brushwork commemorate the Sabra and Shatila massacre of Palestinian refugees.", "Al-Azzawi is the Arab world's most important political artist. This work responding to the 1982 massacre is his most powerful statement.", "male", "Iraqi"),
    ("Mona Hatoum: Map (clear)", "Mona Hatoum", 2015, "Clear glass marbles", "Contemporary Palestinian-British", ["installation","glass","map","displacement","fragile"], ["world map","glass marbles","floor","fragile","displacement"], ["clear glass","floor","transparent"], "Various museums", "A map of the world made from clear glass marbles on the floor — fragile, transparent, easily broken or disrupted.", "Hatoum's glass map embodies the fragility of borders and national identity — one wrong step destroys the whole world.", "female", "Palestinian-British"),

    # ── ADDITIONAL PERFORMANCE & BODY ART ────────────────────────────────
    ("Marina Abramović: The Artist Is Present", "Marina Abramović", 2010, "Performance", "Performance Art / Serbian", ["performance","durational","silence","presence","MoMA"], ["artist seated","visitors opposite","silence","duration","endurance"], ["gallery white","two chairs","silent presence"], "Museum of Modern Art, MoMA (736 hours over 3 months)", "Abramović sat silently at a table in MoMA's atrium for 736 hours over three months. Visitors sat opposite her one at a time.", "Over 1400 people sat opposite Abramović during the performance; many wept. The longest solo performance by a museum artist. Redefines what art can do.", "female", "Serbian"),
    ("Marina Abramović: Rhythm 0", "Marina Abramović", 1974, "Performance", "Performance Art / Serbian", ["performance","durational","danger","passive body","transgression"], ["passive artist","72 objects","audience action","6 hours","gun"], ["gallery white","table of objects","body"], "Studio Morra, Naples", "Abramović stood passively for 6 hours while the public used 72 objects (including a loaded gun and knife) on her body.", "The most disturbing performance ever staged. The public escalated to violence — cutting her clothes, pressing the gun to her throat. She wept at the end.", "female", "Serbian"),
    ("Chris Burden: Shoot", "Chris Burden", 1971, "Performance (documentation)", "Performance Art / American", ["performance","danger","shooting","self-inflicted","political"], ["artist shot","rifle","arm","documented","risk"], ["video documentation black white"], "F Space, Santa Ana, California", "Burden had a friend shoot a rifle bullet through his left arm in a gallery.", "The most extreme act of self-inflicted harm in art history. Burden's body-risk performances confronted the Vietnam War's indifference to physical damage.", "male", "American"),
    ("Carolee Schneemann: Meat Joy", "Carolee Schneemann", 1964, "Performance", "Performance Art / American", ["performance","feminist","body","sensory","ritual"], ["raw meat","paint","performers","celebration","body"], ["flesh colors","red raw meat","performance documentation"], "Judson Memorial Church, New York", "Performers writhed together in raw fish, chickens, sausages, and wet paint in an ecstatic body-celebration performance.", "Schneemann's celebration of the body, sexuality, and sensory joy was deliberately opposite to Minimalism's cool rationality. The defining feminist performance work.", "female", "American"),
    ("Vito Acconci: Following Piece", "Vito Acconci", 1969, "Performance (documentation)", "Conceptual Art / American", ["performance","following","urban","surveillance","documentation"], ["following strangers","New York streets","documentation","surveillance"], ["photographic documentation","urban grey"], "Various collections", "For 23 days Acconci followed random strangers through New York City until they entered a private space.", "A precursor of surveillance art. Following makes the artist invisible as author while making the stranger the involuntary subject.", "male", "American"),

    # ── ADDITIONAL CERAMICS & CRAFTS AS ART ─────────────────────────────
    ("Lucie Rie: Stoneware Bowl with Green Interior", "Lucie Rie", 1960, "Stoneware", "Studio Pottery / British", ["ceramic","modernist","elegant","simple","refined"], ["bowl","green glaze","simple form","studio pottery","refined"], ["parchment","green interior","simple elegant form"], "Victoria and Albert Museum, London", "A small stoneware bowl with a luminous green interior glaze and parchment exterior.", "Rie was the greatest studio potter of the 20th century. Her forms distill centuries of pottery traditions into pure modernist refinement.", "female", "Austrian-British"),
    ("Hans Coper: Spade Form", "Hans Coper", 1970, "Stoneware", "Studio Pottery / German-British", ["ceramic","sculptural","modernist","form","abstract"], ["spade form","stoneware","white textured","sculptural"], ["white textured stoneware","burnished dark"], "Tate Modern, London", "A spade-shaped stoneware vessel combining a burnished dark body and a textured white neck.", "Coper's sculptures turn pottery into pure sculpture. His forms are entirely invented — no historical ceramic tradition uses these shapes.", "male", "German-British"),
    ("Shoji Hamada: Tenmoku Glazed Bottle", "Shoji Hamada", 1960, "Stoneware with iron glaze", "Mingei / Japanese", ["mingei","folk pottery","tenmoku","rich glaze","japanese"], ["bottle form","iron glaze","simple shape","japanese folk"], ["deep tenmoku brown","iridescent glaze"], "Various collections", "A bottle with a deep tenmoku (iron-rich) glaze in dark brown with iridescent surface variation.", "Hamada and Yanagi founded the Japanese Mingei (Folk Art) movement. Their celebration of anonymous craft against fine-art hierarchy was radical.", "male", "Japanese"),

    # ── STREET ART & URBAN ────────────────────────────────────────────────
    ("Banksy: Girl with Balloon", "Banksy", 2002, "Stencil spray paint on wall", "Street Art / British", ["street art","stencil","hope","loss","iconic"], ["girl","red heart balloon","reaching","loss","hope"], ["black stencil","red balloon","brick wall"], "Various walls, London (original destroyed/shredded)", "A small girl reaches for a red heart-shaped balloon drifting away on the wind — the most reproduced street art image in history.", "When the canvas version sold at Sotheby's for £1 million (2018), it shredded itself. The shredded version sold for £18.6 million in 2021.", "unknown", "British"),
    ("Jean-Michel Basquiat: Hollywood Africans", "Jean-Michel Basquiat", 1983, "Acrylic and oil stick on canvas", "Neo-Expressionism / American", ["neo-expressionist","text","race","hollywood","graffiti"], ["text","palm tree","three figures","race in hollywood","history"], ["yellow background","black text","drawn figures"], "Whitney Museum, New York", "Three figures with crowns and text including 'Tobacco', 'Sugar Cane', 'What is Gangsterism' against a yellow ground.", "Basquiat addresses race and representation in Hollywood while visiting Los Angeles with fellow graffiti artists Rammellzee and Toxic.", "male", "American"),
    ("Os Gemeos: Untitled mural (Tate Modern)", "Os Gemeos", 2008, "Spray paint on canvas/wall", "Street Art / Brazilian", ["street art","mural","dreamlike","yellow figures","brazilian"], ["yellow figures","dreamlike","large scale","Brazilian","narrative"], ["yellow","blue","cream","vivid spray paint"], "Tate Modern exterior, London", "Enormous yellow-skinned characters in flowing costumes from Os Gemeos's unique dreamlike visual vocabulary.", "Os Gemeos (The Twins) are the most internationally recognized Brazilian street artists. Their yellow-skinned characters come from their grandmother's stories.", "male", "Brazilian"),
    ("Shepard Fairey: Hope (Barack Obama)", "Shepard Fairey", 2008, "Screen print", "Street Art / American", ["poster","political","stencil","presidential","iconic"], ["Obama portrait","HOPE","red blue cream","political poster"], ["red","cream","blue","bold graphic"], "Various collections", "Barack Obama's face in red, cream, and blue stencil with the word 'HOPE' below — the most recognizable political image of the 21st century.", "Made as a viral street art image, it became the visual symbol of the Obama campaign. Legal battles followed over its photographic source.", "male", "American"),

    # ── ADDITIONAL AFRICAN ART ────────────────────────────────────────────
    ("Malian Bogolanfini (Mudcloth)", "Dogon weavers", 1920, "Cotton cloth with fermented mud", "West African / Malian", ["textile","geometric","ritual","male identity","indigenous"], ["geometric patterns","mud dye","black white","hunting ceremony"], ["dark brown mud","cream cotton","geometric pattern"], "Various collections", "Cotton cloth with geometric patterns applied in fermented mud on a cream ground.", "Bogolan (mudcloth) was worn by hunters and used in initiation ceremonies. Its bold geometric patterns have influenced global fashion and design.", "unknown", "Malian"),
    ("Kente Cloth (Asante Royal Kente)", "Asante weavers, Ghana", 1900, "Silk and cotton weave", "Akan / West African", ["textile","royal","geometric","colorful","ceremonial"], ["warp-and-weft strips","royal colors","geometric","ceremony"], ["gold","red","green","black","brilliant silk"], "Various collections", "Royal Kente cloth in brilliant silk strips of gold, green, red, and black in complex geometric patterns.", "Kente was originally only for Asante royalty. The yellow-gold signifies royalty and wealth; the green fertility. Now globally recognized as an African cultural symbol.", "unknown", "Ghanaian"),
    ("Yoruba Gelede Mask", "Yoruba carvers, Nigeria", 1880, "Carved and painted wood", "Yoruba / West African", ["mask","ceremonial","female power","painted","carved"], ["female mask","carved superstructure","painted details","ceremony"], ["painted ochre","black","natural wood","painted"], "British Museum, London", "A Yoruba gelede mask with a carved female face surmounted by an elaborate carved tableau of figures and animals.", "Gelede ceremonies honor female spiritual power ('the Mothers'). The elaborate superstructure above the face is a narrative carved world.", "unknown", "Nigerian"),
    ("Ndebele House Painting", "Ndebele women painters, South Africa", 1950, "Mineral paint on mud house wall", "South African Indigenous", ["architectural","geometric","colorful","female art","mural"], ["geometric patterns","house wall","bold color","ceremony"], ["vivid primary colors","geometric","white outline"], "Various locations, Mpumalanga", "Ndebele house walls painted with bold geometric patterns in vivid primary colors, renewed seasonally by women.", "Ndebele mural painting is an exclusively female art form. The bold geometric patterns encode social information and cultural identity.", "female", "South African"),
    ("Himba Otjize Body Art", "Himba women, Namibia", 1990, "Ochre and butterfat on body", "Namibian Indigenous", ["body art","ochre","performative","cultural","female"], ["body","ochre","cultural identity","red ochre","female ritual"], ["deep red ochre","skin"], "Himba territory, Namibia (living practice)", "Himba women mix red ochre pigment with butterfat and apply it daily to skin and hair — a living body art practice.", "Himba body art is simultaneously cosmetic, cultural, and spiritual. The ochre is called 'otjize' and represents the red color of earth and blood.", "female", "Namibian"),

    # ── ADDITIONAL OCEANIC ────────────────────────────────────────────────
    ("Malanggans (Malangan) Funerary Carving", "New Ireland carvers", 1900, "Carved and painted wood", "Melanesian / Pacific", ["carved","ceremonial","mortuary","intricate","pacific"], ["carved openwork","funeral ceremony","abstract figures","bird","spirit"], ["red","black","white","natural pigments"], "Various museums worldwide", "An intricately carved openwork funerary figure combining human, bird, and fish elements in a complex spiritual narrative.", "New Ireland's malangan carvings are among the most technically complex in the Pacific. Each is made for a specific funeral ceremony and then abandoned.", "unknown", "Papua New Guinean"),
    ("Sepik River Figure", "Sepik carvers, Papua New Guinea", 1880, "Carved wood with shells and pigment", "Papua New Guinea / Pacific", ["carved","ritual","ancestor","power","spirit"], ["ancestor figure","carved","spirit","ceremonial","shells"], ["dark wood","shell inlay","natural pigments"], "Various museums", "A standing ancestor figure with shell-inlaid eyes and elaborate surface decoration from the Sepik River artistic tradition.", "Sepik River art is among the most formally inventive in the Pacific. The spirit figures embody ancestors who can be consulted in ritual contexts.", "unknown", "Papua New Guinean"),
    ("Hawaiian Feather Cape (Ahu'ula)", "Hawaiian crafters", 1780, "Feathers on plant fiber netting", "Hawaiian / Pacific", ["textile","featherwork","royal","red yellow","ceremonial"], ["red yellow feathers","crescent shape","royal cape","mana"], ["vivid red","yellow feathers","black pattern"], "Bishop Museum, Honolulu", "A royal feather cape of brilliant red and yellow bird feathers in geometric patterns on plant-fiber netting — one of the most significant royal objects.", "Hawaiian feather capes embodied the sacred power (mana) of the chief. The red and yellow feathers from native birds took decades to accumulate.", "unknown", "Hawaiian"),

    # ── ADDITIONAL CONTEMPORARY ────────────────────────────────────────────
    ("Wolfgang Tillmans: Lighter", "Wolfgang Tillmans", 1999, "C-print", "Contemporary Photography / German", ["photograph","abstract darkroom","light","subtle","large format"], ["abstract light forms","darkroom chemistry","print","large scale"], ["varied pink","cream","abstract light"], "Various collections", "A large-format abstract photograph produced by exposing photographic paper directly to light — no camera, no subject.", "Tillmans's darkroom abstractions expand photography beyond the image. The chemistry and light create unpredictable forms.", "male", "German"),
    ("Luc Tuymans: The Secretary of State", "Luc Tuymans", 2005, "Oil on canvas", "Contemporary Belgian / Figurative", ["pale","muted","figurative","political","uncanny"], ["Condoleezza Rice","portrait","pale","political","confrontational"], ["pale grey","skin tone","muted","stark"], "Zeno X Gallery, Antwerp", "A blurry, pale portrait of Condoleezza Rice based on a news photograph — confrontational in its monumental scale.", "Tuymans's deliberately 'bad' painting technique creates an unsettling distance. His portraits of political power feel like photographic evidence in a crime case.", "male", "Belgian"),
    ("Neo Rauch: Patrol", "Neo Rauch", 2000, "Oil on canvas", "Contemporary Figurative / German", ["figurative","surrealist","dreamlike","DDR aesthetic","patrol"], ["patrolling figures","dreamlike landscape","socialist realist aesthetics"], ["muted ochre","grey","DDR palette","dreamlike"], "Various collections", "Figures in grey-blue uniforms patrol a dreamlike landscape from an indeterminate historical moment.", "Rauch's patrol figures inhabit a temporal suspension — they could be from the 1950s or an imagined future. Haunted by East German history.", "male", "German"),
    ("Peter Doig: Echo Lake", "Peter Doig", 1998, "Oil on canvas", "Contemporary Figurative / British", ["figurative","landscape","reflective","nocturnal","atmospheric"], ["policeman","lake","reflection","trees","night"], ["dark water","white reflection","forest dark","solitary figure"], "Tate Modern, London", "A lone figure — possibly a policeman — stands at a dark lake whose still surface reflects white figures in the trees.", "One of Doig's most haunting lake paintings — the reflected 'figures' are birch trees, but they look like the dead. Memory, film, and landscape fused.", "male", "British"),
    ("Neo Rauch: Führungskraft (Leader)", "Neo Rauch", 2009, "Oil on canvas", "Contemporary Figurative / German", ["figurative","dreamlike","power","worker","strange narrative"], ["figure in work clothes","strange tools","power","dreamlike"], ["ochre","grey","muted socialist palette"], "Various collections", "A figure in East German work clothes holds strange implements in a landscape of ambiguous industrial and natural forms.", "Rauch's 'leader' is both a parody of socialist heroism and a meditation on the human desire for meaning in labor.", "male", "German"),
    ("Dana Schutz: Frank from Observation", "Dana Schutz", 2002, "Oil on canvas", "Contemporary American / Figurative", ["figurative","imaginary figure","painterly","color","humor"], ["Frank","invented man","eating himself","paint","humor"], ["vivid color","gestural brushwork","flesh paint"], "Saatchi Collection, London", "A man eats himself while painting — Schutz's ongoing character Frank invented as the last person on earth who must create his own audience.", "Schutz invented Frank as a thought experiment: the last man alive must create art to be seen by no one. Her painterly humor is unique in contemporary figuration.", "female", "American"),
    ("Lisa Brice: Untitled (After Morisot)", "Lisa Brice", 2019, "Enamel on canvas", "Contemporary South African-British", ["figurative","female gaze","blue","bathers","repainting"], ["women bathers","blue enamel","Morisot reference","female subjects","contemporary"], ["blue enamel","darker flesh","intimate"], "Various collections", "Women bathers in blue enamel — an homage to Morisot and Degas's bather subjects seen through a female lens.", "Brice repaints classic female subjects from female Old Master and Impressionist painters through a contemporary feminist lens.", "female", "South African"),
    ("Tschabalala Self: Bodega Run", "Tschabalala Self", 2017, "Fabric, acrylic, flashe on canvas", "Contemporary American / Figurative", ["figurative","black female body","fabric collage","narrative","urban"], ["black woman figure","bodega","fabric","urban","powerful presence"], ["vivid color","fabric collage","expressive"], "Pilar Corrias Gallery, London", "A large black female figure moves through an urban space, her body assembled from fabric collage and paint.", "Self's figures celebrate black female bodies in public urban space. Her fabric-and-paint technique makes the figures simultaneously painted and sculptural.", "female", "American"),
    ("Jordan Casteel: Visible Man", "Jordan Casteel", 2014, "Oil on canvas", "Contemporary American / Figurative", ["figurative","black subjects","observation","intimate","oil"], ["man in chair","intimate portrait","direct gaze","domestic"], ["warm ochre","cream","direct intimate portrait"], "Various collections", "A man in a domestic setting painted in warm oil with a direct, intimate gaze.", "Casteel paints the people of her Harlem community in an act of radical seeing and celebration. Her portraits insist on the visibility and fullness of black life.", "female", "American"),
    ("Amy Sherald: Miss Everything (Unsuppressed Deliverance)", "Amy Sherald", 2013, "Oil on canvas", "Contemporary American / Figurative", ["figurative","grey skin","confrontational","american","celebration"], ["woman","grey monochrome skin","vivid dress","direct gaze","portrait"], ["vivid dress color","grey skin","dark background"], "Smithsonian American Art Museum", "A woman in a vivid dress with grey-toned skin gazes directly at the viewer in complete self-possession.", "Sherald's grey-toned skin removes the racial coding from her subjects — making them universal while centering specifically Black American experience.", "female", "American"),
    ("Henry Taylor: B'rer Rabbit — In Dreams", "Henry Taylor", 2020, "Acrylic on canvas", "Contemporary American / Figurative", ["figurative","black culture","loose","autobiographical","political"], ["figure in bed","dream","acrylic looseness","race","interior"], ["cream","skin tones","gestural acrylic"], "Various collections", "A figure in a domestic bed scene rendered in loose, gestural acrylic — a meditation on rest, dreaming, and vulnerability.", "Taylor's paintings of Black American domestic and public life are rendered with a spontaneous gestural directness that refuses idealization.", "male", "American"),
]

def make_entry(idx, raw):
    if len(raw) == 12:
        title, artist, year, medium, movement, style, subject, colors, museum, desc, hist, gender = raw
        nationality = "Unknown"
    else:
        title, artist, year, medium, movement, style, subject, colors, museum, desc, hist, gender, nationality = raw[:13]
    period = period_from_year(year)
    tags = list(dict.fromkeys(
        [s.lower() for s in style[:4]] +
        [s.lower() for s in subject[:3]] +
        [movement.split("/")[0].strip().lower(), period.lower().split(" ")[0]]
    ))[:12]
    return {
        "id": idx, "title": title, "artist": artist, "year": year,
        "medium": medium, "movement": movement, "style": style,
        "subject": subject,
        "color_palette": colors if isinstance(colors, list) else [colors],
        "museum": museum, "description": desc, "historical_significance": hist,
        "artist_gender": gender, "artist_nationality": nationality,
        "period": period, "tags": tags,
    }

def main():
    with open(DATA_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)
    start_id = max(a["id"] for a in existing) + 1
    new_entries = []
    for i, raw in enumerate(BATCH3):
        try:
            new_entries.append(make_entry(start_id + i, raw))
        except Exception as e:
            print(f"  Skip {i} ({raw[0] if raw else '?'}): {e}")
    merged = existing + new_entries
    with open(DATA_PATH, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print(f"Done. {len(existing)} existing + {len(new_entries)} new = {len(merged)} total.")

if __name__ == "__main__":
    main()
