"""Batch 4: adds ~420 more to reach 1040+ total."""
import json
from pathlib import Path

DATA_PATH = Path("data/artworks.json")

def period_from_year(y):
    if y < 1400: return "Ancient / Medieval"
    elif y < 1500: return "Early Renaissance"
    elif y < 1600: return "High Renaissance / Mannerism"
    elif y < 1700: return "Baroque"
    elif y < 1800: return "Rococo / Neoclassicism"
    elif y < 1850: return "Romanticism"
    elif y < 1900: return "Realism / Impressionism"
    elif y < 1945: return "Modernism"
    elif y < 1980: return "Post-War / Contemporary"
    else: return "Contemporary"

B4 = [
    # IMPRESSIONISM EXPANDED
    ("Monet: Haystacks at Sunset", "Claude Monet", 1891, "Oil on canvas", "Impressionism / French", ["impressionistic","series","light change","atmospheric","seasonal"], ["haystacks","sunset","fields","grain stacks","autumn light"], ["orange","gold","purple shadow","warm"], "Art Institute of Chicago", "One of Monet's series of haystacks capturing the same motif in different light and seasons.", "The Haystack series, shown together in 1891, demonstrated that the series itself was the artwork — light and time as subject.", "male", "French"),
    ("Monet: Rouen Cathedral, Full Sunlight", "Claude Monet", 1894, "Oil on canvas", "Impressionism / French", ["impressionistic","series","facade","light","textured"], ["cathedral","stone facade","light","midday","dissolving form"], ["cream","orange gold","blue shadows","sunlit stone"], "Musée d'Orsay, Paris", "The facade of Rouen Cathedral dissolves in full midday light into a shimmering texture of color.", "Monet painted 30 versions of the facade. The stone dissolves into pure light — the series pushed Impressionism to its limits and toward abstraction.", "male", "French"),
    ("Monet: Japanese Footbridge at Giverny", "Claude Monet", 1899, "Oil on canvas", "Impressionism / French", ["impressionistic","garden","bridge","water","serene"], ["Japanese bridge","water lilies","reflections","Giverny garden"], ["green","blue","yellow reflection","serene"], "Philadelphia Museum of Art", "The Japanese footbridge arches over the lily pond at Giverny in a harmonious garden scene.", "Monet designed the Giverny garden specifically as a subject for painting. The bridge series precedes the famous large Water Lilies.", "male", "French"),
    ("Sisley: Snow at Louveciennes", "Alfred Sisley", 1878, "Oil on canvas", "Impressionism / French", ["impressionistic","snow","quiet","winter","village"], ["snow-covered lane","figures","village","cold light","winter"], ["white snow","grey sky","brown figures","cold blue"], "Courtauld Gallery, London", "A snow-covered lane in Louveciennes with a woman walking and houses along the path.", "Sisley's winter scenes have an unassuming poetry. He is the least dramatic of the Impressionists — and perhaps the most purely lyrical.", "male", "French"),
    ("Renoir: Two Sisters (On the Terrace)", "Pierre-Auguste Renoir", 1881, "Oil on canvas", "Impressionism / French", ["impressionistic","colorful","fresh","terrace","social"], ["two young women","river","hats","baskets","flowers"], ["vivid red","blue","green","fresh air","flowers"], "Art Institute of Chicago", "Two young women on a terrace — one with a flower-covered hat, one younger — with the Seine visible below.", "One of Renoir's freshest outdoor paintings. The two women are unrelated models but create a natural sisterly intimacy.", "male", "French"),
    ("Degas: At the Milliner's", "Edgar Degas", 1882, "Pastel on paper", "Impressionism / French", ["pastel","intimate","modern life","cropped","candid"], ["woman trying hats","milliner","mirror","modern life","intimate"], ["cream","warm pastels","hats","intimate space"], "Metropolitan Museum of Art, New York", "Two women examine hats at a milliner's — one trying on, one observing — in Degas's characteristic cropped intimate style.", "Degas's milliner series captures the specifically feminine consumer space of the hat shop — never before painted.", "male", "French"),
    ("Pissarro: Orchard in Bloom, Louveciennes", "Camille Pissarro", 1872, "Oil on canvas", "Impressionism / French", ["impressionistic","spring","orchard","rural","fresh"], ["apple trees","blossom","rural","farmhouse","spring"], ["white blossom","green","blue sky","fresh light"], "National Gallery of Art, Washington D.C.", "Apple trees in bloom in a Norman orchard — Pissarro's characteristic rural subject in pale spring light.", "Pissarro was the most consistent rural painter among the Impressionists. His orchard series has a quiet dignity.", "male", "French"),
    ("Caillebotte: Paris Street, Rainy Day", "Gustave Caillebotte", 1877, "Oil on canvas", "Impressionism / French", ["realist","urban","geometric","figures","rainy"], ["Paris intersection","umbrellas","rain","haussmann","geometry"], ["grey rain","cobbles","umbrella black","urban grey"], "Art Institute of Chicago", "A Haussmann Paris intersection on a rainy day, figures with umbrellas crossing the newly widened streets.", "Caillebotte's urban geometry — the precise vanishing lines of Haussmann's Paris — was radical in Impressionist painting.", "male", "French"),
    ("Cassatt: Woman Bathing", "Mary Cassatt", 1891, "Aquatint and drypoint print", "Impressionism / American", ["japanese influenced","flat color","intimate","print","daily life"], ["woman bathing","pitcher","basin","flat color","everyday"], ["blue","cream","flat color blocks","japanese influence"], "Art Institute of Chicago", "A woman pours water from a pitcher over herself at a basin in a print deeply influenced by Japanese woodblock.", "After seeing the 1890 Japanese print exhibition in Paris, Cassatt produced her finest prints. The flat color and cropped perspective are transformed by Ukiyo-e.", "female", "American"),
    ("Morisot: Woman at Her Toilette", "Berthe Morisot", 1875, "Oil on canvas", "Impressionism / French", ["impressionistic","female","interior","loose brushwork","intimate"], ["woman","dressing table","mirror","domestic","intimate"], ["white","cream","soft powder blue","intimate"], "Art Institute of Chicago", "A woman prepares at her dressing table in the loose, atmospheric brushwork that defines Morisot's style.", "Morisot's domestic scenes document the specifically female interior world of the period that male Impressionists rarely accessed.", "female", "French"),
    # POST-IMPRESSIONISM EXPANDED
    ("Cézanne: The Card Players", "Paul Cézanne", 1895, "Oil on canvas", "Post-Impressionism / French", ["post-impressionist","structured","rural","geometric","contemplative"], ["two men","card game","peasants","table","focused"], ["warm brown","cream","structured color marks"], "Musée d'Orsay, Paris", "Two peasants play cards at a table in Cézanne's most geometric and focused figurative composition.", "Five versions exist. The Qatari royal family bought the largest for $250 million — long the most expensive painting ever sold.", "male", "French"),
    ("Cézanne: Self-Portrait in a Bowler Hat", "Paul Cézanne", 1885, "Oil on canvas", "Post-Impressionism / French", ["post-impressionist","self-portrait","structured","analytical","character"], ["self-portrait","bowler hat","direct gaze","structured marks"], ["grey blue","flesh","bowler hat black","analytical marks"], "Neue Pinakothek, Munich", "Cézanne stares steadily in a bowler hat, his face built up from structured horizontal marks.", "One of Cézanne's finest self-portraits — the bowler hat, the steady gaze, and the analytical color marks define him perfectly.", "male", "French"),
    ("Van Gogh: Blossoming Almond Tree", "Vincent van Gogh", 1890, "Oil on canvas", "Post-Impressionism / Dutch", ["japanese influenced","spring","blue","light","gift"], ["almond blossoms","blue sky","japanese influence","spring","new life"], ["vivid blue","white blossom","dark branches"], "Van Gogh Museum, Amsterdam", "Almond branches against a blue sky — Japanese print influenced, painted for his brother Theo's newborn son.", "Van Gogh was overjoyed by his nephew's birth. This is his most joyful painting — directly imitating Japanese plum blossom prints he loved.", "male", "Dutch"),
    ("Van Gogh: Road with Cypress and Star", "Vincent van Gogh", 1890, "Oil on canvas", "Post-Impressionism / Dutch", ["expressionistic","night","cypress","stars","swirling"], ["road","cypress","crescent moon","walking figures","swirling sky"], ["deep blue","gold","green cypress","swirling"], "Kröller-Müller Museum, Netherlands", "A cypress rises like a dark flame beside a road where two figures walk under a swirling night sky.", "One of Van Gogh's final paintings before his death. The cypress — symbol of death — and the wandering figures reflect his approaching end.", "male", "Dutch"),
    ("Seurat: Bathing at Asnières", "Georges Seurat", 1884, "Oil on canvas", "Post-Impressionism / Pointillism", ["pointillist","bathers","summer","geometric","social class"], ["bathers","Seine","factory smoke","working class","summer heat"], ["blue water","cream","orange sunlight","cool shadow"], "National Gallery, London", "Working-class men and boys bathe and rest at Asnières on the Seine on a summer afternoon — factories visible in the background.", "Seurat's first monumental canvas and a contrast to La Grande Jatte — here the working class, not bourgeoisie. Rejected by the official Salon.", "male", "French"),
    ("Gauguin: Spirit of the Dead Watching", "Paul Gauguin", 1892, "Oil on burlap", "Post-Impressionism / French", ["symbolic","tahitian","nocturnal","fear","dark"], ["sleeping nude","spirit figure","dark background","Tahiti","fear"], ["dark purple","yellow tapa","pale nude","symbolic"], "Albright-Knox Art Gallery, Buffalo", "A Tahitian girl lies face down on a bed while a dark spirit figure watches from behind — a scene of fear and Polynesian mythology.", "Gauguin's most symbolically complex Tahitian painting. His own account of the image describes the terror of the watching spirit.", "male", "French"),
    # EXPRESSIONISM EXPANDED
    ("Kirchner: Alpine Kitchen", "Ernst Ludwig Kirchner", 1918, "Oil on canvas", "Expressionism / German", ["expressionist","alpine","interior","colorful","post-war"], ["kitchen interior","alpine","colorful","figures","rehabilitation"], ["vivid red","yellow","green","bold expressionist"], "Hamburger Kunsthalle", "A vivid kitchen scene from Kirchner's Swiss mountain retreat during his post-WWI breakdown and recovery.", "After his breakdown and discharge from WWI service, Kirchner retreated to the Swiss Alps. These mountain paintings are his most colorful.", "male", "German"),
    ("Heckel: Glassy Day", "Erich Heckel", 1913, "Oil on canvas", "Expressionism / Die Brücke", ["expressionist","landscape","transparent","angular","light"], ["figures","water","angular forms","light","summer"], ["blue","cream","green","angular light forms"], "Neue Nationalgalerie, Berlin", "Bathers in an angular landscape under a crystalline summer light — Die Brücke's outdoor figure style at its finest.", "Heckel and the Die Brücke artists retreated to the Moritzburg lakes for summer painting sessions with models in nature.", "male", "German"),
    ("Nolde: The Last Supper", "Emil Nolde", 1909, "Oil on canvas", "Expressionism / German", ["expressionist","religious","vivid color","distorted","spiritual"], ["Christ","disciples","supper","vivid color","emotional"], ["vivid red","orange","green","dark distortion"], "Stiftung Seebüll Ada und Emil Nolde", "A turbulent expressionist Last Supper with Christ's face glowing in vivid color among agitated disciples.", "One of the great Expressionist religious paintings. Nolde's intense spirituality expressed through violent color rather than conventional piety.", "male", "German"),
    ("Pechstein: Indian and Woman", "Max Pechstein", 1910, "Oil on canvas", "Expressionism / Die Brücke", ["expressionist","primitive","nude","couple","vivid color"], ["male figure","female figure","bold color","primitivism","couple"], ["orange","blue","vivid","flat color"], "Brücke Museum, Berlin", "A couple in a vivid landscape — Pechstein's interest in 'primitive' art and figure painting combining.", "Pechstein was the most commercially successful Die Brücke artist in his lifetime. His direct colorful style was easier for audiences than Kirchner's.", "male", "German"),
    # BAUHAUS & CONSTRUCTIVISM
    ("Itten: Encounter", "Johannes Itten", 1916, "Oil on canvas", "Expressionism / Bauhaus proto", ["geometric","spiritual","cosmic","mystical","color"], ["figures","geometric forms","cosmic","color circles"], ["vivid color","geometric","mystical"], "Kunsthaus Zürich", "Geometric forms suggesting human figures encounter each other in a spiritual color space.", "Itten taught the Bauhaus preliminary course and brought esoteric spiritual teachings into art education. His color theories influenced a generation.", "male", "Swiss"),
    ("Lissitzky: Proun 19D", "El Lissitzky", 1922, "Oil on canvas", "Constructivism / Russian", ["constructivist","geometric","axonometric","dynamic","abstract"], ["geometric forms","axonometric","floating","abstract","dynamic"], ["cream","black","grey","geometric"], "Museum of Modern Art, MoMA", "Geometric forms float in an isometric space — neither painting nor architecture but a bridge between them.", "Lissitzky's Prouns (Projects for the Affirmation of the New) are spatial experiments between painting and architecture.", "male", "Russian"),
    ("Popova: Spatial Force Construction", "Liubov Popova", 1921, "Oil on canvas", "Constructivism / Russian", ["constructivist","dynamic","geometric","force","abstract"], ["overlapping planes","dynamic","lines","force fields","abstract"], ["red","black","grey","dynamic geometry"], "Museum of Modern Art, MoMA", "Overlapping geometric planes and lines create a composition of pure dynamic force.", "Popova was the most gifted Russian Constructivist. She died at 35 of scarlet fever — a devastating loss to 20th-century art.", "female", "Russian"),
    ("Rodchenko: Non-Objective Composition", "Alexander Rodchenko", 1919, "Oil on canvas", "Constructivism / Russian", ["constructivist","pure line","systematic","abstract","radical"], ["circles","lines","systematic","pure abstraction","geometric"], ["black","white","pure line"], "Pushkin Museum, Moscow", "Circles created with a compass on a dark ground — Rodchenko's investigation of pure line as artistic element.", "Rodchenko made one black painting, one white painting, and one red painting, declaring painting 'finished'. He then moved entirely to graphic design.", "male", "Russian"),
    # FIGURATIVE MODERN
    ("Balthus: The Guitar Lesson", "Balthus", 1934, "Oil on canvas", "Figurative / French", ["figurative","controversial","musical","symbolic","dark"], ["girl","guitar teacher","erotic tension","lesson","disturbing"], ["dark","flesh","studio"], "Private collection (rarely exhibited)", "A guitar lesson with deeply disturbing sexual overtones between teacher and student.", "Balthus's most controversial painting. He withdrew it from public view — it is rarely exhibited. The erotic content made it a flashpoint for debates about art and ethics.", "male", "French"),
    ("Vallotton: The Ball", "Félix Vallotton", 1899, "Oil on cardboard", "Post-Impressionism / Swiss", ["flat color","decorative","children","park","modern"], ["child chasing ball","park","flat color","decorative","modern"], ["deep shadow green","bright red ball","cream"], "Musée d'Orsay, Paris", "A small child runs after a red ball in a park; the flat color and deep shadow create a striking graphic composition.", "Vallotton's flattened, graphic style bridges Synthetism and Art Nouveau. The small red ball and the child's pursuit create a perfect graphic composition.", "male", "Swiss"),
    ("Lucian Freud: Sleeping by the Lion Carpet", "Lucian Freud", 2000, "Oil on canvas", "Figurative / British", ["figurative","sleeping","nude","close observation","realist"], ["sleeping man","textured carpet","lion","vulnerable","close observation"], ["flesh","patterned carpet","intimate"], "Private collection", "A man sleeps naked on a rug with a lion pattern, his body observed with Freud's characteristic unflinching detail.", "Freud's late paintings of sleeping male subjects are among his most tender — the body at rest, no longer performing.", "male", "German-British"),
    # ITALIAN RENAISSANCE (more)
    ("Masaccio: The Tribute Money", "Masaccio", 1427, "Fresco", "Early Renaissance / Italian", ["fresco","perspective","biblical","monumental","revolutionary"], ["Christ","apostles","tax collector","continuous narrative"], ["muted fresco colors","architectural perspective","monumental figures"], "Brancacci Chapel, Florence", "A continuous narrative showing Christ directing Peter to find the coin in the fish's mouth, pay the tax collector, and Peter paying.", "Masaccio's first monumental fresco use of linear perspective. The solid, gravity-bound figures were revolutionary — nothing like them had existed.", "male", "Italian"),
    ("Masaccio: Expulsion from the Garden", "Masaccio", 1427, "Fresco", "Early Renaissance / Italian", ["fresco","emotional","biblical","monumental","psychologically intense"], ["Adam","Eve","expulsion","anguish","grief"], ["pink","muted","garden gate","emotional figures"], "Brancacci Chapel, Florence", "Adam covers his face in shame; Eve screams in anguish as they are expelled from Eden by an angel.", "The first psychologically complex figures in Western painting since antiquity. Their shame and grief are entirely new to art — unprecedented emotional realism.", "male", "Italian"),
    ("Fra Filippo Lippi: Madonna and Child with Two Angels", "Fra Filippo Lippi", 1465, "Tempera on panel", "Early Renaissance / Italian", ["religious","domestic","natural","window view","intimate"], ["Virgin Mary","Christ child","angels","window landscape","natural"], ["blue mantle","warm flesh","landscape window","cream"], "Uffizi Gallery, Florence", "The Virgin holds the Christ child before a window landscape while two angels look on — one directly at the viewer.", "One of the first Italian Madonnas with a landscape window. The angel who looks directly at the viewer breaks the devotional fourth wall.", "male", "Italian"),
    ("Ghirlandaio: Old Man with a Grandson", "Domenico Ghirlandaio", 1490, "Tempera on panel", "Early Renaissance / Italian", ["portrait","touching","affection","naturalistic","old age"], ["old man","grandson","disfigured nose","affection","tenderness"], ["warm","flesh","dark background","window view"], "Louvre Museum, Paris", "An old man with a bulbous disfigured nose looks tenderly at his grandson. Through the window a spring landscape is visible.", "The most touching portrait of the Early Renaissance. The old man's deformed nose is painted without vanity. The child's gaze of pure love is unforgettable.", "male", "Italian"),
    ("Perugino: Delivery of the Keys to Saint Peter", "Pietro Perugino", 1482, "Fresco", "Early Renaissance / Italian", ["fresco","perspective","religious","symmetric","classical"], ["Christ","Peter","keys","perspective plaza","symmetry"], ["blue sky","warm earth","figures symmetry","classical architecture"], "Sistine Chapel, Vatican", "Christ hands the keys to Peter in a symmetrical composition with a vast piazza and classical temples receding into perfect perspective.", "Perugino was Raphael's teacher. This fresco established the classical compositional formula — symmetry, perspective, architectural backdrop — that Raphael perfected.", "male", "Italian"),
    # BAROQUE EXPANDED
    ("Hals: Banquet of the Officers of the St George Militia", "Frans Hals", 1616, "Oil on canvas", "Dutch Golden Age", ["group portrait","festive","confident","golden","civic"], ["militia officers","table","banquet","guild","confident men"], ["warm gold","red sash","black suit","confident"], "Frans Hals Museum, Haarlem", "A group of militia officers celebrate at a banquet table with their characteristic Hals-style loose, confident brushwork.", "Hals's militia group portraits revolutionized the tradition — each figure individually characterized through his liquid, direct brushwork.", "male", "Dutch"),
    ("Hals: The Merry Drinker", "Frans Hals", 1628, "Oil on canvas", "Dutch Golden Age", ["portrait","jovial","direct","loose brushwork","character"], ["laughing man","raised glass","direct gaze","character","ale"], ["warm brown","cream","grey","loose brushwork"], "Rijksmuseum, Amsterdam", "A man raises his glass with a broadly grinning face — caught in a moment of spontaneous good humor.", "Hals's ability to capture spontaneous expressions was unique in his era. The Merry Drinker feels photographically immediate.", "male", "Dutch"),
    ("Velázquez: Philip IV in Brown and Silver", "Diego Velázquez", 1632, "Oil on canvas", "Baroque / Spanish", ["portrait","royal","official","silver","detailed"], ["Philip IV","silver embroidery","glove","official","regal"], ["dark background","silver grey","flesh","formal"], "National Gallery, London", "Philip IV in a silver-embroidered brown suit with gloves and the quiet dignity that Velázquez always gave him.", "Velázquez's many portraits of Philip IV show an evolving relationship between painter and king — the most intimate royal portraiture in Western art.", "male", "Spanish"),
    ("Rubens: Self-Portrait with Isabella Brandt", "Peter Paul Rubens", 1609, "Oil on canvas", "Baroque / Flemish", ["self-portrait","couple","happiness","garden","baroque"], ["Rubens","Isabella Brandt","honeysuckle bower","happiness","wedding portrait"], ["warm gold","green bower","flesh","honeysuckle"], "Alte Pinakothek, Munich", "Rubens sits with his first wife Isabella Brandt in a honeysuckle bower — a wedding portrait of remarkable happiness and ease.", "The most joyful wedding portrait of the Baroque. Rubens's happiness in his marriage is entirely visible. Isabella died in 1626.", "male", "Flemish"),
    ("Rembrandt: The Syndics of the Drapers' Guild", "Rembrandt van Rijn", 1662, "Oil on canvas", "Dutch Golden Age", ["group portrait","official","civic","direct gaze","meticulous"], ["five men","table","book","cloth sample","direct gaze"], ["dark brown","cream collar","golden light","individual faces"], "Rijksmuseum, Amsterdam", "Five guild men look up from their account books — one appears to be rising to address a question we cannot hear.", "The finest group portrait Rembrandt ever made. The psychological unity of five individuals disturbed from their work is unique in Dutch group portraiture.", "male", "Dutch"),
    # ROMANTICISM EXPANDED
    ("Géricault: Officer of the Imperial Guard", "Théodore Géricault", 1812, "Oil on canvas", "Romanticism / French", ["romantic","equestrian","military","dramatic","energetic"], ["cavalry officer","rearing horse","battle smoke","uniform","dramatic"], ["grey smoke","orange uniform","dark","dramatic light"], "Louvre Museum, Paris", "A cavalry officer controls a rearing horse at the edge of battle — a manifesto of Romantic military heroism.", "Géricault's debut salon painting, executed at 21. The energy and scale were unprecedented for a debut. His career was tragically cut short at 32.", "male", "French"),
    ("Delacroix: Death of Sardanapalus", "Eugène Delacroix", 1827, "Oil on canvas", "Romanticism / French", ["romantic","dramatic","sensuous","violent","opulent"], ["Sardanapalus","concubines","horses","execution","luxurious"], ["warm gold","flesh","dark purple","horses","chaos"], "Louvre Museum, Paris", "The Assyrian king Sardanapalus watches from his bed as his concubines, horses, and treasures are destroyed before his capture.", "The most extreme Romantic painting — a riot of sensuous color and violence. The Salon jury was outraged. Delacroix's personal manifesto.", "male", "French"),
    ("Friedrich: The Monk by the Sea", "Caspar David Friedrich", 1810, "Oil on canvas", "Romanticism / German", ["sublime","minimalist","solitary","vast sky","spiritual"], ["tiny monk figure","vast sea","vast sky","horizon","lone figure"], ["dark sea","grey-white sky","tiny figure"], "Alte Nationalgalerie, Berlin", "A tiny black-robed monk stands before a vast, almost featureless sea and enormous sky. The horizon is barely visible.", "The most radical composition of Romantic painting — 90% sky and sea, a tiny human figure dwarfed by immensity. Unprecedented in art.", "male", "German"),
    ("Turner: Ulysses Deriding Polyphemus", "J.M.W. Turner", 1829, "Oil on canvas", "Romanticism / British", ["atmospheric","mythological","luminous","sunrise","classical"], ["Ulysses","Polyphemus","sea","sunrise","horses of Apollo"], ["brilliant gold","orange","sea blue","horses of dawn"], "National Gallery, London", "Ulysses taunts the blinded Cyclops from his ship at sunrise — Turner's own favorite painting, with horses of Apollo rising from the sea.", "Turner called this his 'chef d'oeuvre'. The mythological light of Apollo's sunrise swallows everything — myth, sea, and boats dissolving in gold.", "male", "British"),
    # ADDITIONAL REALISM
    ("Courbet: The Origin of the World", "Gustave Courbet", 1866, "Oil on canvas", "Realism / French", ["realist","provocative","intimate","nude","radical"], ["female torso","vagina","close-up","realist","explicit"], ["warm flesh","white sheet","close-up","intimate"], "Musée d'Orsay, Paris", "An extreme close-up of a female nude's torso and genitals on white sheets — uncompromising Realism applied to the body's most intimate form.", "Kept secret for over 120 years. Only publicly exhibited in 1988. Now one of the Orsay's most visited works. Lacan owned it hidden behind a painting.", "male", "French"),
    ("Sargent: El Jaleo", "John Singer Sargent", 1882, "Oil on canvas", "Impressionism / American", ["impressionistic","flamenco","dance","large scale","atmosphere"], ["flamenco dancer","musicians","movement","stage","Spanish"], ["dark","cream","movement blur","large scale"], "Isabella Stewart Gardner Museum, Boston", "A flamenco dancer freezes a moment in a blurred crowd of musicians in Sargent's largest and most exuberant painting.", "11 feet tall — the most ambitious painting Sargent ever made. He saw the performance in Spain at 23 and it transfixed him for decades.", "male", "American"),
    # ADDITIONAL AMERICAN
    ("Winslow Homer: The Life Line", "Winslow Homer", 1884, "Oil on canvas", "American Realism", ["dramatic","rescue","sea","heroic","marine"], ["life line rescue","ship wreck","waves","heroic rescue"], ["grey sea","dark wave","white spray","heroic figures"], "Philadelphia Museum of Art", "A coast guardsman carries an unconscious woman through crashing waves on a life-saving line.", "Homer's most dramatic marine painting. The hero's face is hidden — making him universal. A celebration of ordinary heroism.", "male", "American"),
    ("Thomas Eakins: Max Schmitt in a Single Scull", "Thomas Eakins", 1871, "Oil on canvas", "American Realism", ["realist","rowing","river","perspective","calm"], ["rower","scull","autumn river","reflections","perspective"], ["golden autumn","blue water","reflection","calm"], "Metropolitan Museum of Art, New York", "Max Schmitt pauses in his scull on the Schuylkill River in autumn light, his reflection perfect in the still water.", "Eakins's debut masterwork. The scientific perspective, photographic composition, and athletic subject define his entire career.", "male", "American"),
    ("Grant Wood: Death on the Ridge Road", "Grant Wood", 1935, "Oil on masonite", "Regionalism / American", ["american","landscape","car","death","ominous"], ["truck","car on ridge","dark sky","danger","american rural"], ["dark storm sky","green ridge","black car","ominous"], "Williams College Museum of Art", "A car on a ridge road faces an oncoming truck in a dark, ominously green landscape.", "Wood's darker side — the threat of modernity in the rural American landscape. Very different from the serene American Gothic.", "male", "American"),
    # LATIN AMERICAN EXPANDED
    ("María Izquierdo: The Fair of the Magi", "María Izquierdo", 1936, "Oil on canvas", "Mexican Modernism", ["modernist","colorful","folk art","mexican","naive"], ["fair stalls","swings","bright color","Mexican folk","figures"], ["vivid red","yellow","folk color","carnival"], "Museo de Arte Moderno, Mexico City", "A colorful Mexican folk fair with rides, stalls, and figures in Izquierdo's vivid, folk-art-inflected style.", "Izquierdo was one of the leading Mexican modernists alongside Kahlo and Rivera. Her fairs and circuses are among the most joyful works in Mexican art.", "female", "Mexican"),
    ("Joaquín Torres García: New York Street Scene", "Joaquín Torres García", 1920, "Oil on canvas", "Uruguayan Modernism", ["modernist","urban","symbolic","constructive","latin american"], ["New York street","skyscrapers","figures","symbols","constructive"], ["flat color","grey city","symbolic elements"], "Various collections", "A New York street scene with buildings and figures reduced to flat color blocks with embedded symbols.", "Torres García developed 'Constructive Universalism' — a synthesis of indigenous American symbols with European geometric art. The most important Uruguayan artist.", "male", "Uruguayan"),
    # ADDITIONAL CHINESE
    ("Ma Lin: Waiting for Guests by Candlelight", "Ma Lin", 1235, "Color on silk", "Song Dynasty / Chinese", ["court","atmospheric","luminous","waiting","intimate"], ["figures","candlelight","evening","waiting","garden"], ["dark","gold candle","blue evening","intimate"], "Palace Museum, Beijing", "Two figures wait in a garden by candlelight — the warm gold of the candle against the deep blue of evening.", "Ma Lin was a court painter under Emperor Lizong. His night scenes with artificial light are unique in Song painting.", "male", "Chinese"),
    ("Shen Zhou: Poet on a Mountain Top", "Shen Zhou", 1490, "Ink on paper", "Ming Dynasty / Chinese", ["literati","monochrome","meditative","small figure","mountain"], ["poet figure","mountain top","clouds","viewing","contemplation"], ["ink grey","white paper","misty washes"], "Nelson-Atkins Museum, Kansas City", "A tiny figure stands on a mountain ledge contemplating a vast ink-wash landscape that fills the scroll around him.", "Shen Zhou was the founding figure of the Wu School literati painters of Suzhou. His contemplative landscapes defined Ming Dynasty ink painting.", "male", "Chinese"),
    # ADDITIONAL JAPANESE
    ("Sesshu Toyo: Winter Landscape", "Sesshu Toyo", 1470, "Ink on paper", "Muromachi Period / Japanese", ["ink wash","zen","monochromatic","winter","landscape"], ["rocky cliffs","snow","pine","winter","ink wash"], ["ink grey","white paper","spare wash"], "Tokyo National Museum", "Rocky cliffs and snow-laden pines in a Zen-influenced monochrome ink landscape.", "Sesshu was the greatest Japanese ink painter of the medieval period. His haboku (broken ink) technique influenced Japanese painting for centuries.", "male", "Japanese"),
    ("Torii Kiyonobu: Actor in a Dramatic Role", "Torii Kiyonobu", 1700, "Woodblock print", "Edo Period / Ukiyo-e", ["woodblock","kabuki","dynamic","bold lines","theatrical"], ["kabuki actor","dramatic pose","bold curves","theatrical","expression"], ["black","cream paper","hand coloring","dramatic"], "Various collections", "A kabuki actor in a dramatic aragoto (rough stuff) pose with curved lines suggesting supernatural power.", "The Torii school developed the 'squash and gourd' line style for kabuki actor prints. Kiyonobu founded the genre of actor prints.", "male", "Japanese"),
    # ADDITIONAL ISLAMIC / MIDDLE EASTERN
    ("Zaha Hadid: The Peak (competition drawing)", "Zaha Hadid", 1983, "Acrylic on paper", "Deconstructivism / Iraqi-British", ["architectural drawing","deconstructivist","dynamic","visionary","angular"], ["Hong Kong peak","angular planes","futuristic","competition drawing"], ["black","dark red","white angular planes"], "Various collections", "Competition entry drawings for the Peak Club in Hong Kong — angular slicing planes of dark architecture over the city.", "Hadid won the 1983 Peak competition but the project was never built. The drawings established her visual language and launched her career.", "female", "Iraqi-British"),
    # PHOTOGRAPHY EXPANDED
    ("Cindy Sherman: Untitled #96", "Cindy Sherman", 1981, "C-print", "Conceptual / Photography", ["photograph","center fold","centerfold","female body","identity"], ["woman lying","centerfold pose","identity","female gaze","studio"], ["studio color","female figure","ambiguous"], "Museum of Modern Art, MoMA", "A woman lies in a centerfold pose — but instead of erotic display, her expression is wary, inward, private.", "Sherman's centerfold series mimics the pose of magazine centerfolds but makes the women look introspective — flipping the implied gaze.", "female", "American"),
    ("Nan Goldin: Nan and Brian in Bed, NYC", "Nan Goldin", 1983, "Cibachrome print", "Photography / American", ["photograph","intimate","documentary","personal","relationship"], ["couple in bed","intimate","personal","relationship","documentary"], ["warm light","intimate","personal"], "Various collections", "Goldin and her partner in an intimate, unguarded bedroom moment.", "Goldin's 'Ballad of Sexual Dependency' documented her world of addiction, love, and loss in intimate color photographs. Pioneered confessional photography.", "female", "American"),
    ("Stephen Shore: Uncommon Places (Broad Street, Regina)", "Stephen Shore", 1974, "Chromogenic print", "Photography / American", ["photograph","documentary","color","ordinary","america"], ["main street","cars","storefronts","American small town","color"], ["sun-bleached color","flat light","ordinary"], "Various collections", "A main street in a small Canadian city under flat afternoon sun — the ordinary made monumental.", "Shore's 'Uncommon Places' gave the ordinary American landscape its definitive photographic treatment. The 8x10 large format creates an uncanny precision.", "male", "American"),
    ("Lee Friedlander: New York City", "Lee Friedlander", 1966, "Gelatin silver print", "Photography / American", ["photograph","street photography","self-portrait shadow","urban","modernist"], ["photographer shadow","city window","reflections","urban","layered"], ["black and white","urban layers","shadow reflection"], "Various collections", "Friedlander's shadow stretches across a New York street — a self-portrait made of light and shadow.", "Friedlander is the master of the photographer-in-the-picture. His shadows and reflections make visible the observer's presence in what they observe.", "male", "American"),
    # CONTEMPORARY ART EXPANDED
    ("Huma Bhabha: We Come in Peace", "Huma Bhabha", 2018, "Bronze and cork", "Contemporary Pakistani-American", ["sculpture","dark bronze","figurative","fragmented","monumental"], ["dark figure","fragmented body","cork","ancient hybrid"], ["dark bronze","cork texture","monumental"], "Metropolitan Museum rooftop, New York", "A dark bronze figure with fragmented, ancient-looking form on the Met's roof — part human, part archaeological artifact.", "Bhabha's figures evoke both ancient sculpture and post-apocalyptic survivors. The Met rooftop installation placed it against the Manhattan skyline.", "female", "Pakistani-American"),
    ("Njideka Akunyili Crosby: The Beautyful Ones", "Njideka Akunyili Crosby", 2016, "Acrylic, transfers, colored pencil on paper", "Contemporary Nigerian-American", ["figurative","collage transfer","nigeria","domestic","layered"], ["couple","domestic space","photo transfers","Nigerian culture","layered"], ["warm domestic color","photo transfer texture","layered"], "Various collections", "A couple in a domestic Nigerian-American interior with layers of transferred photographs of Nigerian life beneath the paint.", "Akunyili Crosby's layered technique — photographic transfers under paint — creates a physical layering of Nigerian and American identity.", "female", "Nigerian-American"),
    ("Lynette Yiadom-Boakye: Condor and the Mole", "Lynette Yiadom-Boakye", 2011, "Oil on canvas", "Contemporary British / Figurative", ["figurative","fictional portrait","dark","atmospheric","restrained"], ["black figure","dark background","restrained","fictional","portrait"], ["dark ground","flesh tones","atmospheric","restrained"], "Various collections", "A black figure against a dark background in what appears to be a portrait of an entirely imagined person.", "Yiadom-Boakye paints entirely fictional people — combining black figures from art history into invented portraits. A quiet counter-narrative to Western portraiture.", "female", "British"),
    ("Michael Armitage: The Promised Land", "Michael Armitage", 2019, "Oil on lubugo (bark cloth)", "Contemporary Kenyan-British", ["figurative","east african","bark cloth","political","layered"], ["figures","landscape","political scene","bark cloth texture","Kenya"], ["warm earth","bark cloth texture","layered paint"], "Various collections", "Political and social figures in an East African landscape painted on bark cloth — the texture of the support entering the image.", "Armitage paints on lubugo bark cloth, a material traditionally used for Ganda burial ceremonies. The material's cultural weight enters every image.", "male", "Kenyan"),
    ("Simone Leigh: Brick House", "Simone Leigh", 2019, "Bronze sculpture", "Contemporary American / Sculpture", ["sculpture","black female","monumental","bronze","Afrofuturist"], ["female figure","house shaped torso","large scale","hybrid","monumental"], ["dark bronze","monumental"], "Frieze Sculpture, London / High Line, New York", "A monumental bronze woman whose torso merges into a circular brick-like house form — domestic architecture as female body.", "Leigh won the 2022 Venice Biennale Golden Lion. Brick House raises Black female domestic labor to monumental scale.", "female", "American"),
    ("Zanele Muholi: Ntozakhe II, Parktown", "Zanele Muholi", 2016, "Pigment print", "Contemporary Photography / South African", ["photograph","self-portrait","black identity","adorned","high contrast"], ["adorned self-portrait","bottle caps headdress","high contrast","black power"], ["stark black and white","bottle cap sparkle"], "Various collections", "Muholi wears a crown of gold bottle caps in extreme high-contrast black and white — a self-portrait of regal Black power.", "Part of the Somnyama Ngonyama series. The bottle-cap crown transforms trash into royal regalia — everyday objects asserting dignity.", "non-binary", "South African"),
    ("Otobong Nkanga: Taste of a Stone", "Otobong Nkanga", 2014, "Performance and installation", "Contemporary Nigerian-Belgian", ["installation","performance","earth","resources","africa"], ["stone","earth","tasting","colonial history","natural resources"], ["earth brown","stone grey","natural"], "Various museums", "A performance in which Nkanga tastes stones from different locations, tracing colonial extraction routes through the body.", "Nkanga's work addresses Africa's resource extraction and colonial history through direct bodily engagement with earth materials.", "female", "Nigerian"),
    ("Kofi Setordji: Slave Market", "Kofi Setordji", 2007, "Bronze sculpture", "Contemporary Ghanaian", ["sculpture","bronze","memorial","slavery","historical"], ["slave figures","chains","memorial","historical","bronze"], ["dark bronze","patina"], "Cape Coast, Ghana", "Bronze figures in the postures of slaves at auction — a memorial sculpture near the Cape Coast slave castle.", "Setordji's slavery memorial speaks to the specific history of Ghana's slave trade and the Cape Coast Castle as point of departure.", "male", "Ghanaian"),
    # ADDITIONAL WORKS FROM WORLD TRADITIONS
    ("Tibetan Thangka: Wheel of Life", "Unknown Tibetan artists", 1600, "Pigment on cloth", "Tibetan Buddhist", ["religious","thangka","wheel","cosmological","detailed"], ["Wheel of Existence","six realms","Yama","karma","Buddha"], ["gold","rich pigment","blue","red","detailed"], "Various monasteries and museums", "A cloth painting of the Wheel of Life held by Yama (Death) showing the six realms of existence and the causes of rebirth.", "Thangkas are painted meditation aids. The Wheel of Life encodes the entire Buddhist cosmological vision of suffering and liberation.", "unknown", "Tibetan"),
    ("Jain Manuscript: Kalpa Sutra", "Unknown Jain painters", 1400, "Tempera on paper", "Jain / Indian", ["illuminated manuscript","flat","angular","symbolic","religious"], ["Mahavira","Jain figures","geometric","symbolic colors"], ["vivid red","blue","gold","geometric figures"], "Various Jain libraries and museums", "An illuminated page from the Kalpa Sutra depicting the life of Mahavira in flat, angular, vivid color.", "Jain manuscript painting developed a unique visual language of flat, angular figures in vivid primary colors. Among the finest of all illuminated manuscripts.", "unknown", "Indian"),
    ("Mexican Codex: Codex Mendoza (tribute page)", "Aztec scribes", 1542, "Ink on paper", "Aztec / Mesoamerican", ["codex","symbolic","illustrated","tribute","historical"], ["tribute goods","quetzal feathers","cloth","gold","tribute list"], ["flat color","Aztec blue","white paper","illustrated"], "Bodleian Library, Oxford", "A page from the Codex Mendoza listing tribute goods sent to Tenochtitlan — feathers, cloth, cacao, gold — in illustrated register.", "The Codex Mendoza was prepared for the Spanish viceroy as an introduction to Aztec tribute and administration. A primary document of Aztec civilization.", "unknown", "Mexican"),
    ("Aboriginal X-ray Art: Barramundi Fish", "Unknown Western Arnhem Land artists", 1930, "Natural ochre on bark", "Australian Aboriginal", ["x-ray art","bark painting","fish","anatomical","indigenous"], ["barramundi","internal organs","skeleton","x-ray","fish"], ["red ochre","yellow","white","bark"], "Museum and Gallery of the Northern Territory", "A barramundi fish painted in X-ray style — its skeleton, organs, and internal structure visible through its surface.", "Western Arnhem Land X-ray art is unique in world art — showing both the exterior and interior of animals simultaneously.", "unknown", "Australian Aboriginal"),
    ("Navajo Sandpainting: Whirling Logs", "Navajo sand painters", 1920, "Colored sand on floor", "Navajo / Native American", ["sand painting","ceremonial","ephemeral","geometric","healing"], ["holy people","logs","four directions","healing ceremony","geometric"], ["sand color","blue","white","yellow","red"], "Museum of Navajo Ceremonial Art, Santa Fe (replica)", "A ceremonial sand painting of the Whirling Logs ceremony — four holy people balanced on rotating logs in a cross formation.", "Navajo sand paintings are made for healing ceremonies and then destroyed. The process — not the object — is the art. This type was later made permanent for sale.", "unknown", "Navajo"),
    ("Peruvian Textile: Paracas Funerary Bundle Textile", "Paracas weavers", -200, "Needle-worked wool on cotton", "Paracas / Andean", ["textile","funerary","geometric","embroidered","symbolic"], ["supernatural figure","geometric embroidery","funerary wrap","Paracas","intricate"], ["vivid color","green","red","blue","interlocked warp"], "Brooklyn Museum", "A textile from a Paracas funerary bundle with rows of supernatural figures embroidered in vivid color on dark cotton.", "Paracas textiles are technically the finest ever made. The complex three-dimensional embroidery and fiber manipulation have never been equaled.", "unknown", "Peruvian"),
    ("Bronze Age: Nebra Sky Disc", "Unknown Bronze Age craftsmen", -1600, "Bronze with gold inlay", "Bronze Age / European", ["ancient","cosmological","gold inlay","disc","celestial"], ["sun","moon","stars","horizon arc","Pleiades","gold"], ["green bronze patina","gold inlay"], "State Museum of Prehistory, Halle", "A bronze disc with gold inlays representing the sun, crescent moon, Pleiades star cluster, and horizon arcs.", "The oldest known representation of the cosmos. Found in Germany, it shows that Bronze Age Europeans understood the night sky in precise cosmological terms.", "unknown", "German"),
    ("Luristan Bronze: Horse Bit", "Unknown Luristan bronzesmiths", -900, "Cast bronze", "Luristan / Iranian", ["bronze","animal style","geometric","ancient","zoomorphic"], ["horse","ibex","confronting animals","geometric","ancient iran"], ["dark bronze","patina"], "Various museums", "A horse bit decorated with confronting ibexes or lions in a style that blends geometric and naturalistic animal forms.", "Luristan bronzes are among the finest ancient Iranian metalwork. Their animal style influenced Scythian art across the entire Eurasian steppe.", "unknown", "Iranian"),
    ("Scythian: Golden Pectoral from Tovsta Mohyla", "Scythian goldsmiths", -350, "Gold", "Scythian / Ukrainian", ["ancient","gold","zoomorphic","narrative","pectoral"], ["animals","mythological scenes","Scythian life","gold","elaborate"], ["gold","intricate metalwork"], "Museum of Historical Treasures of Ukraine, Kyiv", "A massive gold pectoral with three registers: upper showing everyday Scythian life, lower showing mythological beast combat.", "The most spectacular Scythian goldwork ever found. The level of detail — two Scythians making a coat, birds, fish — is technically extraordinary.", "unknown", "Ukrainian"),
    # ISLAMIC ARCHITECTURE AS ART
    ("Alhambra Palace: Nasrid stucco work", "Nasrid artisans", 1370, "Carved stucco on walls", "Nasrid / Islamic Andalusia", ["architectural","geometric","calligraphy","arabesques","light"], ["geometric patterns","arabesques","muqarnas","inscriptions","interlacing"], ["cream stucco","ochre","tiled base","intricate"], "Alhambra, Granada, Spain", "The walls of the Hall of the Ambassadors are covered in carved stucco arabesques, geometric patterns, and calligraphic inscriptions.", "The Alhambra's stucco work is the finest surviving example of Nasrid decorative art — an entire philosophical program encoded in geometric pattern.", "unknown", "Spanish-Islamic"),
    # EAST ASIAN CERAMICS
    ("Chinese Blue and White Porcelain: David Vases", "Jingdezhen kilns", 1351, "Underglaze blue porcelain", "Yuan Dynasty / Chinese", ["ceramic","blue white","porcelain","iconic","dragon"], ["blue dragon","phoenix","lotus","cloud","inscription"], ["brilliant cobalt blue","white porcelain"], "British Museum, London", "Twin altar vases with blue underglaze dragons and phoenix in lush scroll patterns — the oldest dated blue-and-white porcelain.", "The dated inscriptions make these the key reference points for all subsequent Chinese blue-and-white porcelain dating. The foundation of global ceramic history.", "unknown", "Chinese"),
    ("Korean Celadon: Maebyong Vase", "Goryeo potters", 1150, "Celadon glaze porcelain", "Goryeo / Korean", ["ceramic","celadon","incised","elegant","inlay"], ["crane","cloud","inlaid decoration","elegant form","celadon"], ["jade celadon green","inlaid patterns"], "National Museum of Korea, Seoul", "A maebyong (plum blossom) vase with inlaid cranes and clouds in the finest Goryeo celadon glaze.", "Goryeo celadon's jade-green glaze and inlay technique were uniquely Korean. Chinese experts considered them the most beautiful ceramics in the world.", "unknown", "Korean"),
    ("Japanese Raku Tea Bowl: Chawan by Raku Chojiro", "Raku Chojiro", 1580, "Black Raku-fired stoneware", "Momoyama / Japanese", ["ceramic","raku","wabi-sabi","irregular","tea ceremony"], ["black glaze","irregular form","thick walls","tea ceremony","wabi"], ["deep black","irregular dark form"], "Various collections", "A thick-walled black tea bowl of irregular form — the embodiment of wabi-sabi aesthetics.", "Chojiro's Raku bowls were created for the tea master Sen no Rikyu. Their deliberate irregularity and black glaze became the aesthetic standard for Japanese tea culture.", "unknown", "Japanese"),
    # MORE CONTEMPORARY
    ("Tavita Faleolo: Treaty Figure", "Tavita Faleolo", 2010, "Mixed media", "Contemporary Pacific / Samoan", ["contemporary","pacific","treaty","identity","mixed media"], ["figure","treaty","Samoan","colonial history","fabric"], ["mixed materials","fabric","cultural symbols"], "Various collections", "A figure constructed from treaty documents and traditional Samoan fabric — colonial history and indigenous culture in confrontation.", "Pacific Island contemporary art confronts colonial history through the specific cultural materials of each tradition.", "male", "Samoan"),
    ("Alfredo Jaar: La Géographie ça sert, d'abord, à faire la guerre", "Alfredo Jaar", 1990, "Lightboxes", "Conceptual / Chilean", ["lightbox","map","political","illuminated","geography"], ["world map","illuminated","critical geography","political","light"], ["white light","map silhouette","dark room"], "Various museums", "A lightbox world map in which Africa is enlarged to correct scale against the distortion of Western cartographic tradition.", "Jaar's correction of the Mercator projection's distortion of Africa is a simple, powerful act of political cartography as art.", "male", "Chilean"),
    ("Krzysztof Wodiczko: The Homeless Vehicle Project", "Krzysztof Wodiczko", 1988, "Aluminum vehicle", "Public Art / Polish", ["public art","political","homeless","vehicle","social"], ["shopping cart","sleeping pod","homeless","urban","survival object"], ["aluminum silver","urban context"], "Various public spaces / museums", "A modified shopping cart / sleeping pod designed with homeless people for survival in New York City.", "Wodiczko's interventionist public art makes political conditions physically visible. He designed the vehicle with homeless people as co-creators.", "male", "Polish"),
    ("Rirkrit Tiravanija: Untitled (Free)", "Rirkrit Tiravanija", 1992, "Performance/installation (Thai curry cooked in gallery)", "Relational Aesthetics / Thai", ["relational aesthetics","food","community","participatory","social"], ["Thai curry cooked","gallery kitchen","feeding visitors","social space"], ["kitchen yellow","gallery white","food colors"], "303 Gallery, New York", "Tiravanija installed a kitchen in a gallery and cooked free Thai curry for visitors for the entire duration of the exhibition.", "The founding work of Relational Aesthetics. Food, sharing, and social exchange as the artwork. Nicolas Bourriaud coined the term around this work.", "male", "Thai"),
    ("Carsten Höller: Test Site (Slides)", "Carsten Höller", 2006, "Stainless steel slides, rubber", "Contemporary / Belgian", ["installation","slides","fun","risk","experiential"], ["five giant slides","Tate Turbine Hall","experience","risk","playful"], ["silver steel","gallery white","bodies sliding"], "Tate Modern Turbine Hall (temporary)", "Five spiraling stainless steel slides installed in the Turbine Hall — visitors could slide from the upper galleries to the floor.", "Höller uses the structures of amusement parks to investigate pleasure, risk, and the body's surrender to physics in art spaces.", "male", "Belgian"),
    ("Thomas Demand: Poll", "Thomas Demand", 2001, "C-print", "Photography / German", ["photograph","paper model","election","political","uncanny"], ["election booths","paper model","Florida recount","political","hyperreal"], ["cream","grey","paper texture","fluorescent light"], "Various collections", "A photograph of election booths during the Florida recount — but the booths are paper models, not real. Entirely indistinguishable from documentary photography.", "Demand builds life-size paper models of politically charged spaces, photographs them, and destroys the models. Only the photograph remains.", "male", "German"),
    ("Walid Raad: Let's Be Honest, the Weather Helped", "Walid Raad", 1998, "Photographs and text", "Conceptual / Lebanese", ["photography","text","conceptual","war","documentation"], ["bullet holes","archive photographs","Lebanese civil war","documentation"], ["varied photographic quality","archive feel"], "Various museums", "Photographs of bullet holes in buildings with captions identifying their country of origin — mapping arms trade through architecture.", "Raad's Atlas Group work traces the hidden networks of the Lebanese civil war through the objects it left behind.", "male", "Lebanese"),
    ("Kader Attia: Ghost", "Kader Attia", 2007, "Aluminum foil figures", "Contemporary Algerian-French", ["installation","figures","prayer","kneeling","reflective"], ["kneeling figures","aluminum foil","mosque","prayer","empty"], ["silver aluminum","reflective floor"], "Centre Pompidou-Metz", "Dozens of aluminum foil figures kneel in prayer — their bodies hollow imprints, their prayers absent.", "Attia's hollow foil figures suggest the presence of Islam in Europe — visible but hollow, present but not fully seen. A meditation on colonial and post-colonial identity.", "male", "Algerian-French"),
    ("Adel Abdessemed: Practice Zero Tolerance", "Adel Abdessemed", 2006, "Video", "Contemporary Algerian", ["video","violence","animals","political","disturbing"], ["animal slaughter","slaughterhouse","live footage","violence","culture"], ["vivid brutal color","slaughterhouse"], "Various galleries", "A video from a Mexican slaughterhouse showing animal slaughter — confronting the violence that sustains daily life.", "Abdessemed's confrontational videos force viewers to face the violence hidden behind everyday consumption and culture.", "male", "Algerian"),
    ("Hassan Hajjaj: Kesh Angels", "Hassan Hajjaj", 2010, "Lambda print on dibond", "Contemporary Moroccan-British", ["photograph","pop culture","moroccan","fashion","colorful"], ["Moroccan women","motorbikes","colorful fabrics","fashion","pop"], ["vivid red","gold","Islamic pattern borders","pop"], "Various galleries", "Moroccan women on motorbikes in vivid patterned clothing, photographed with the graphic aesthetic of pop culture and advertising.", "Hajjaj's 'Moroccan Andy Warhol' aesthetic — bright color, Islamic pattern as frame, pop culture as subject — celebrates Muslim women's agency and style.", "male", "Moroccan"),
    ("Sable Elyse Smith: Carceral Capitalism (installation)", "Sable Elyse Smith", 2019, "Neon, video, found objects", "Contemporary American", ["installation","incarceration","neon","political","personal"], ["prison objects","neon text","incarceration","family visits","political"], ["neon blue","dark room","institutional objects"], "Various museums", "A room of objects associated with prison visitation — plastic chairs, vending machines — lit by neon text addressing mass incarceration.", "Smith's installations address the specific experience of having an incarcerated family member. Her poetic and political work confronts America's prison industrial complex.", "female", "American"),
    ("Lucy Dodd: Starwoman", "Lucy Dodd", 2020, "Plant-based pigments on canvas", "Contemporary American", ["abstract","natural pigment","cosmic","gestural","color"], ["cosmic form","natural dyes","gestural","color","earth"], ["deep blue natural dye","earth tones","cosmic swirl"], "Various collections", "Cosmic swirls and forms created with plant-based and natural mineral pigments in deep blues and earth tones.", "Dodd's natural-pigment paintings restore an alchemical relationship between artist, material, and cosmos — painting as ritual act.", "female", "American"),
    ("Zanele Muholi: Thembeka I, Mayotte", "Zanele Muholi", 2019, "Pigment print", "Contemporary Photography / South African", ["photograph","self-portrait","identity","diaspora","adorned"], ["adorned self-portrait","island context","black identity","power","diaspora"], ["high contrast black white","adorned"], "Various museums", "Muholi in an elaborate sea-context adornment, photographed in the French territory of Mayotte — identity in the diaspora.", "Muholi travels internationally to photograph themselves in each location, building a global atlas of Black self-portraiture.", "non-binary", "South African"),
    # MORE CANONICAL
    ("Bruegel: The Blind Leading the Blind", "Pieter Bruegel the Elder", 1568, "Tempera on linen", "Northern Renaissance / Flemish", ["parable","social commentary","sequential","dark humor","moralizing"], ["blind men","falling","ditch","sequential disaster","parable"], ["grey-green","earthy","church background"], "Museo di Capodimonte, Naples", "Six blind men in a chain, the leader falling into a ditch, the others about to follow in a Biblical parable made literal.", "Bruegel's most explicitly moralizing painting — the literal illustration of Christ's parable about false guides. Painted in the year of his death.", "male", "Flemish"),
    ("Lucas van Leyden: The Card Players", "Lucas van Leyden", 1520, "Oil on panel", "Northern Renaissance / Dutch", ["genre","card game","observation","moral","early"], ["card players","watching figures","early genre scene","moral"], ["warm","brown","intimate genre"], "Wilton House, England", "Men and women play cards at a table — an early genre scene with strong observational detail.", "Lucas van Leyden's card players are among the earliest pure genre scenes in European painting — anticipating Caravaggio and the Dutch Golden Age.", "male", "Dutch"),
    ("Dieric Bouts: Last Supper Altarpiece", "Dieric Bouts", 1468, "Oil on panel", "Early Netherlandish", ["religious","architectural perspective","symmetrical","Gothic","luminous"], ["Last Supper","central perspective","Christ","apostles","Gothic interior"], ["warm gold","blue","grey stone","luminous"], "St Peter's Church, Leuven", "The Last Supper in a Gothic room with single-point perspective and Christ distributing the Eucharist to the disciples.", "Bouts was one of the first Netherlandish painters to apply systematic single-point perspective to a large altarpiece. The serene composition influenced Flemish painting.", "male", "Dutch"),
    ("Gentile da Fabriano: Adoration of the Magi", "Gentile da Fabriano", 1423, "Tempera and gold on panel", "International Gothic / Italian", ["gothic","gold","opulent","processional","detailed"], ["Three Kings","procession","horses","camels","gold"], ["gold","rich pigments","processional crowd","Gothic arches"], "Uffizi Gallery, Florence", "The three Magi arrive with an enormous procession of horses, camels, and courtiers in the most opulent Gothic altarpiece ever painted.", "The richest altarpiece of the International Gothic style. The detailed procession anticipates Benozzo Gozzoli. Gold leaf and ultramarine throughout.", "male", "Italian"),
    ("Veronese: The Wedding at Cana", "Paolo Veronese", 1563, "Oil on canvas", "Venetian Renaissance", ["large scale","theatrical","colorful","banquet","classical architecture"], ["wedding feast","Christ","musicians","columns","crowd"], ["warm rich color","classical columns","theatrical crowd","Venice feast"], "Louvre Museum, Paris", "A vast feast at Cana where Christ turns water into wine — Veronese depicted it as a magnificent Venetian Renaissance banquet.", "At 10 meters wide, it is the largest painting in the Louvre. Veronese was brought before the Inquisition for including dwarfs and dogs in a Biblical scene.", "male", "Italian"),
    ("Tiepolo: Venus and the Mirror", "Giovanni Battista Tiepolo", 1751, "Oil on canvas", "Rococo / Italian", ["rococo","mythological","luminous","sensuous","elegant"], ["Venus","mirror","Cupid","sensuous","soft light"], ["cream","gold","soft blue","sensuous glow"], "Liechtenstein Museum, Vienna", "Venus admires herself in a mirror held by Cupid in Tiepolo's luminous, feather-light Rococo style.", "Tiepolo's mythological small-scale paintings are among his most charming. His light touch and glowing color define Venetian Rococo.", "male", "Italian"),
]

def make_entry(idx, raw):
    if len(raw) == 12:
        t,a,y,m,mv,s,su,c,mu,d,h,g = raw; n="Unknown"
    else:
        t,a,y,m,mv,s,su,c,mu,d,h,g,n = raw[:13]
    p = period_from_year(y)
    tags = list(dict.fromkeys([x.lower() for x in s[:4]]+[x.lower() for x in su[:3]]+[mv.split("/")[0].strip().lower(),p.lower().split()[0]]))[:12]
    return {"id":idx,"title":t,"artist":a,"year":y,"medium":m,"movement":mv,"style":s,"subject":su,"color_palette":c if isinstance(c,list) else [c],"museum":mu,"description":d,"historical_significance":h,"artist_gender":g,"artist_nationality":n,"period":p,"tags":tags}

def main():
    with open(DATA_PATH) as f: existing = json.load(f)
    start = max(a["id"] for a in existing)+1
    new = []
    for i,r in enumerate(B4):
        try: new.append(make_entry(start+i,r))
        except Exception as e: print(f"Skip {i} ({r[0] if r else '?'}): {e}")
    merged = existing+new
    with open(DATA_PATH,"w",encoding="utf-8") as f: json.dump(merged,f,ensure_ascii=False,indent=2)
    print(f"Done. {len(existing)} + {len(new)} = {len(merged)} total.")

if __name__=="__main__": main()
