"""Final batch: 200 new unique entries to reach 1100+."""
import json
from pathlib import Path
DATA_PATH = Path("data/artworks.json")

def period_from_year(y):
    if y<1400: return "Ancient / Medieval"
    elif y<1500: return "Early Renaissance"
    elif y<1600: return "High Renaissance / Mannerism"
    elif y<1700: return "Baroque"
    elif y<1800: return "Rococo / Neoclassicism"
    elif y<1850: return "Romanticism"
    elif y<1900: return "Realism / Impressionism"
    elif y<1945: return "Modernism"
    elif y<1980: return "Post-War / Contemporary"
    else: return "Contemporary"

FINAL_200 = [
    # IMPRESSIONISM NEW
    ("Renoir: Child with a Watering Can", "Pierre-Auguste Renoir", 1876, "Oil on canvas", "Impressionism / French", ["impressionistic","child","garden","dappled light","charming"], ["small girl","watering can","garden path","summer"], ["vivid blue dress","green garden","dappled light"], "National Gallery of Art, Washington D.C.", "A small girl in a blue dress with a watering can stands on a garden path in dappled summer light.", "One of Renoir's most beloved child portraits. The combination of vivid blue and green garden light is perfectly Impressionist.", "male","French"),
    ("Pissarro: The Boulevard Montmartre on a Winter Morning", "Camille Pissarro", 1897, "Oil on canvas", "Impressionism / French", ["impressionistic","urban","winter","morning","Paris boulevard"], ["Paris boulevard","horse carriages","winter morning","figures"], ["grey winter","horse carriage","pale light","Paris"], "Metropolitan Museum of Art, New York", "The Boulevard Montmartre on a winter morning with horse-drawn carriages and figures streaming below.", "Pissarro's Boulevard Montmartre views were painted from his hotel room in all seasons. This winter version is particularly atmospheric.", "male","French"),
    ("Degas: Ballet Rehearsal on Stage", "Edgar Degas", 1874, "Oil on canvas", "Impressionism / French", ["impressionistic","ballet","stage","rehearsal","candid"], ["dancers","rehearsal","stage","movement","practice"], ["white tutus","warm stage light","backstage darkness"], "Musée d'Orsay, Paris", "Dancers rehearse on stage viewed from the wings—the candid theatrical view Degas pioneered.", "Degas viewed ballet as a subject for pure visual research—movement, light, and unusual viewpoints. This stage view is one of his finest.", "male","French"),
    ("Sisley: The Canal du Loing", "Alfred Sisley", 1892, "Oil on canvas", "Impressionism / French", ["impressionistic","canal","reflections","quiet","landscape"], ["canal","trees","reflections","summer","quiet"], ["blue water","green trees","reflection","quiet"], "Various collections", "The Canal du Loing with trees and their reflections in a still, quiet Impressionist landscape.", "Sisley's late canal paintings are among his finest—the reflections in still water a perfect subject for Impressionist color study.", "male","French"),
    ("Morisot: The Harbor at Lorient", "Berthe Morisot", 1869, "Oil on canvas", "Impressionism / French", ["impressionistic","harbor","water","figure","early"], ["harbor","woman","sailing","seaside","figure"], ["blue water","white dress","figure","boats"], "National Gallery of Art, Washington D.C.", "A woman in white looks out over the harbor at Lorient with sailboats beyond.", "One of Morisot's earliest masterpieces—the combination of figure and seascape is handled with exceptional freshness.", "female","French"),
    # POST-IMPRESSIONISM NEW
    ("Toulouse-Lautrec: At the Circus Fernando—Equestrian", "Henri de Toulouse-Lautrec", 1887, "Oil on canvas", "Post-Impressionism / French", ["post-impressionist","circus","equestrian","candid","unusual view"], ["circus","horse","rider","clown","ring"], ["warm sawdust","dark ring","vivid figure"], "Art Institute of Chicago", "A circus equestrienne performs in the ring viewed from above—unusual perspective and vivid characterization.", "One of Lautrec's earliest masterpieces—the unusual aerial perspective from the gallery seats defines his whole approach to candid observation.", "male","French"),
    ("Cézanne: The Blue Vase", "Paul Cézanne", 1885, "Oil on canvas", "Post-Impressionism / French", ["post-impressionist","still life","flowers","geometric","blue vase"], ["blue vase","flowers","table","structured","still life"], ["vivid blue vase","flowers","ochre table"], "Musée d'Orsay, Paris", "A blue vase with flowers on a table—Cézanne's structured still life approach applied to a floral subject.", "Cézanne's flower still lifes are rarer than his apples. The blue vase is among his finest—the structure never impedes the beauty.", "male","French"),
    ("Gauguin: The Alyscamps", "Paul Gauguin", 1888, "Oil on canvas", "Post-Impressionism / French", ["post-impressionist","arles","autumn","flat color","symbolic"], ["Arles autumn","avenue","women","flat color","symbolic"], ["vivid orange","yellow","symbolic flat color","Arles"], "Musée d'Orsay, Paris", "Women walk in the avenue of sarcophagi at Arles in autumn—flat symbolic color painted when Gauguin was with Van Gogh.", "Painted during the two months Gauguin and Van Gogh worked together in Arles. Both painted the Alyscamps—their different approaches are instructive.", "male","French"),
    ("Van Gogh: The Red Vineyard", "Vincent van Gogh", 1888, "Oil on canvas", "Post-Impressionism / Dutch", ["expressionistic","vineyard","vivid","only sold","arles"], ["vineyard","workers","autumn","vivid red","harvest"], ["vivid red","orange","yellow","harvest light"], "Pushkin Museum, Moscow", "A vineyard at harvest glows in extraordinary red and gold—the only painting Van Gogh sold in his lifetime.", "The only painting Van Gogh sold during his life. The vivid red vineyard was seen as a sunset over the fields but also as blood—both life and death.", "male","Dutch"),
    ("Seurat: Young Woman Powdering Herself", "Georges Seurat", 1890, "Oil on canvas", "Pointillism / French", ["pointillist","domestic","intimate","funny","self-referential"], ["woman","powder puff","mirror","domestic","intimate"], ["cream","pointillist dots","warm domestic"], "Courtauld Gallery, London", "A young woman powders herself at her dressing table—Seurat's most intimate and subtly humorous work.", "The original mirror showed Seurat's own reflection, which he replaced with a vase of flowers. The woman is his partner Madeleine Knobloch.", "male","French"),
    # SYMBOLISM NEW
    ("Böcklin: Island of the Dead", "Arnold Böcklin", 1880, "Oil on canvas", "Symbolism / Swiss", ["symbolist","dark","island","death","atmospheric"], ["cypress island","boat","white figure","dead","sea"], ["dark green cypresses","grey water","white figure"], "Alte Nationalgalerie, Berlin", "A white-shrouded figure stands in a boat approaching a rocky island of tall dark cypresses—a vision of the afterlife.", "The most reproduced German-speaking painting of the 19th century. Böcklin made five versions. Sigmund Freud had a print on his wall.", "male","Swiss"),
    ("Klimt: Medicine (destroyed)", "Gustav Klimt", 1901, "Oil on canvas (destroyed 1945)", "Art Nouveau / Symbolism", ["symbolist","allegorical","erotic","naked figures","ceiling"], ["naked figures","medical allegory","death","university ceiling","erotic"], ["gold","dark","naked bodies","symbolic"], "Destroyed in Immendorf fire, 1945", "An allegorical ceiling painting showing floating naked figures representing the ambiguity of medicine—healing and death entwined.", "Destroyed in WWII along with the other University paintings. Known only from photographs. Klimt's most controversial work—the university rejected it as obscene.", "male","Austrian"),
    ("Moreau: The Apparition", "Gustave Moreau", 1876, "Watercolor", "Symbolism / French", ["symbolist","watercolor","decadent","Salomé","vision"], ["Salomé","severed head of John the Baptist","vision","elaborate","jeweled"], ["jewel color","gold","dark","vision"], "Musée d'Orsay, Paris", "Salomé recoils from the vision of John the Baptist's severed head floating before her in an elaborate jeweled interior.", "The Apparition is more disturbing than Moreau's oil version—the watercolor medium creates an eerie translucency. Huysmans immortalized it in À rebours.", "male","French"),
    # BAROQUE NEW
    ("Guercino: Return of the Prodigal Son", "Giovanni Francesco Barbieri (Guercino)", 1619, "Oil on canvas", "Baroque / Italian", ["baroque","religious","chiaroscuro","emotional","tender"], ["father","son","embrace","return","prodigal"], ["warm light","dark background","tender embrace"], "Kunsthistorisches Museum, Vienna", "The prodigal son returns and is embraced by his father in warm Guercino chiaroscuro.", "Guercino's early paintings rival Caravaggio in their dramatic light. This prodigal son has a tenderness Caravaggio rarely attempted.", "male","Italian"),
    ("Vouet: The Birth of the Virgin", "Simon Vouet", 1620, "Oil on canvas", "Baroque / French", ["baroque","religious","golden light","monumental","theatrical"], ["Virgin Mary","birth scene","women","theatrical","warm light"], ["golden light","warm red","theatrical baroque"], "San Francesco a Ripa, Rome", "The newborn Virgin is bathed in golden baroque light attended by women in theatrical draperies.", "Vouet brought Italian Baroque to France—his Roman period paintings have a warmth and light that his French successors could not equal.", "male","French"),
    ("Honthorst: Supper Party", "Gerard van Honthorst", 1619, "Oil on canvas", "Dutch Golden Age / Caravagesque", ["candlelit","genre","night scene","candlelight","Caravagesque"], ["supper","musicians","candlelight","night scene","laughing figures"], ["warm candlelight","dark background","vivid faces"], "Uffizi Gallery, Florence", "A supper scene lit entirely by candlelight—musicians and diners in warm Caravagesque glow.", "Honthorst was called 'Gerardo delle Notti' (Gerard of the Nights) for his candlelight scenes. His influence on Rembrandt's chiaroscuro was direct.", "male","Dutch"),
    ("Rubens: The Judgement of Paris", "Peter Paul Rubens", 1639, "Oil on panel", "Baroque / Flemish", ["baroque","mythological","nude","three graces","dynamic"], ["Paris","three goddesses","apple","nude","Juno Venus Minerva"], ["warm flesh","blue sky","golden apple","Rubens sensuous"], "Museo del Prado, Madrid", "Paris hands the golden apple to Venus—three nude goddesses in Rubens's most luscious late style.", "Rubens used his young wife Helena Fourment as model for all three goddesses. His late mythological paintings are his most sensuous.", "male","Flemish"),
    # NEOCLASSICISM NEW
    ("Ingres: Oedipus and the Sphinx", "Jean-Auguste-Dominique Ingres", 1808, "Oil on canvas", "Neoclassicism / French", ["neoclassical","mythological","male nude","classical","linear"], ["Oedipus","sphinx","riddle","nude","classical"], ["warm flesh","dark cave","classical Greece"], "Louvre Museum, Paris", "Oedipus solves the Sphinx's riddle—his nude torso frontal and idealized in the Ingres classical manner.", "Ingres's debut Salon painting. The nude torso—unsentimental and intellectually focused—shows his anti-Romantic classical ambition.", "male","French"),
    ("David: Leonidas at Thermopylae", "Jacques-Louis David", 1814, "Oil on canvas", "Neoclassicism / French", ["neoclassical","heroic","nude","battle","ancient"], ["Leonidas","Spartan warriors","sacrifice","Thermopylae","nude figures"], ["warm flesh","warm stone","classical heroism"], "Louvre Museum, Paris", "Leonidas and his Spartan warriors prepare for the last stand at Thermopylae in a frieze of heroic male nudes.", "David worked on this painting for 15 years. It celebrates the noble sacrifice of Thermopylae as Napoleon's power collapsed.", "male","French"),
    # ROMANTICISM NEW
    ("Géricault: Insane Woman (The Envy)", "Théodore Géricault", 1822, "Oil on canvas", "Romanticism / French", ["romantic","portrait","asylum patient","psychological","intimate"], ["elderly woman","psychiatric patient","direct gaze","intimate","psychological"], ["warm flesh","dark background","direct grey eyes"], "Musée des Beaux-Arts, Lyon", "An elderly woman stares with vacant intensity—one of Géricault's portraits of inmates at the Salpêtrière hospital.", "Géricault painted ten portraits of asylum patients—unique in 19th-century painting for their sympathetic psychological attention.", "male","French"),
    ("Delacroix: Tiger Attacking a Horse", "Eugène Delacroix", 1826, "Lithograph", "Romanticism / French", ["romantic","animal","violent","struggle","dramatic"], ["tiger","horse","attack","violence","animal energy"], ["dark dramatic","animal struggle"], "Various collections", "A tiger attacks a rearing horse—Delacroix's animal struggle as expression of Romantic energy.", "Delacroix's animal struggle images were directly inspired by his love of Rubens and his study of wild animals at the Jardin des Plantes.", "male","French"),
    ("Turner: Snow Storm—Steam-Boat off a Harbour's Mouth", "J.M.W. Turner", 1842, "Oil on canvas", "Romanticism / British", ["sublime","vortex","storm","abstract","atmospheric"], ["steam boat","snow storm","vortex","sea","atmospheric"], ["white grey","vortex of steam and snow","abstract sublime"], "Tate Britain, London", "A steamboat in a vortex of snow, steam, and sea—Turner's most abstract and most sublime painting.", "Turner claimed to have been lashed to the mast during the storm. Critics said it was 'soapsuds and whitewash'. Now recognized as a peak of Romantic painting.", "male","British"),
    ("Friedrich: The Cross in the Mountains", "Caspar David Friedrich", 1808, "Oil on canvas", "Romanticism / German", ["sublime","religious","landscape","cross","symbolic"], ["mountain cross","sunset","fir trees","symbolic","devotional"], ["warm sunset","dark fir trees","golden","cross"], "Gemäldegalerie Neue Meister, Dresden", "A cross on a mountain summit framed by fir trees against a golden sunset—Friedrich's most directly religious landscape.", "Friedrich placed this painting on an altar—the first time a pure landscape was used as an altarpiece. Scandalized critics and clergy.", "male","German"),
    # AMERICAN 19TH CENTURY NEW
    ("Sargent: The Daughters of Edward Darley Boit", "John Singer Sargent", 1882, "Oil on canvas", "Impressionism / American", ["impressionistic","children","interior","shadow","psychological"], ["four girls","dark interior","vases","shadow","psychological"], ["dark shadow","cream dresses","Japanese vases","mysterious"], "Museum of Fine Arts, Boston", "Four girls stand and sit in a dark interior flanked by enormous Japanese vases—a psychological group portrait.", "Influenced by Velázquez's Las Meninas. The girls retreat into shadow; the youngest looks at the viewer. A masterpiece of psychological portraiture.", "male","American"),
    ("Homer: The Blue Boat", "Winslow Homer", 1892, "Watercolor on paper", "American Realism", ["watercolor","summer","lake","boys","luminous"], ["two boys","blue boat","lake","summer","oars"], ["vivid blue","green lake","summer light"], "Museum of Fine Arts, Boston", "Two boys in a blue boat on a summer lake—Homer's most serene and luminous watercolor.", "Homer's Adirondack watercolors capture the simple pleasures of summer. The blue boat and its reflection are technically brilliant.", "male","American"),
    ("Sargent: Venetian Interior", "John Singer Sargent", 1882, "Oil on canvas", "Impressionism / American", ["impressionistic","venice","interior","figures","atmospheric"], ["Venetian interior","women","light","dark","atmospheric"], ["dark interior","venetian light","loose brushwork"], "Carnegie Museum of Art, Pittsburgh", "Figures in a dark Venetian interior lit by a single window—atmospheric and candidly observed.", "Sargent painted many Venetian genre scenes in the early 1880s. These atmospheric interiors anticipate the freedom of his later work.", "male","American"),
    # LATIN AMERICAN NEW
    ("Matta: The Earth Is a Man", "Roberto Matta", 1944, "Oil on canvas", "Surrealism / Chilean", ["surrealist","cosmic","geological","large scale","explosive"], ["geological forces","energy","fire","cosmic forces","explosive"], ["red orange","deep space","explosive energy"], "Art Institute of Chicago", "Geological and cosmic forces erupt across a large canvas in Matta's most ambitious early work.", "Matta's geological Surrealism influenced the Abstract Expressionists directly. Pollock cited Matta as his key influence for automatic painting.", "male","Chilean"),
    ("Torres García: Constructive Composition", "Joaquín Torres García", 1934, "Oil on canvas", "Constructivism / Uruguayan", ["constructivist","symbols","universal","grid","latin american"], ["symbols","grid","clock","sun","constructive"], ["earth tones","symbolic grid","ochre","simple"], "Museo Nacional de Artes Visuales, Montevideo", "A grid of symbols—compass, eye, clock, anchor—in earth tones on a constructive grid.", "Torres García's Constructive Universalism combined Pre-Columbian symbols with European geometric art. Foundational for Latin American modernism.", "male","Uruguayan"),
    ("Lam: Zambezia, Zambezia", "Wilfredo Lam", 1950, "Oil on canvas", "Surrealism / Cuban", ["surrealist","jungle","hybrid figures","afrocuban","dark"], ["hybrid figures","sugar cane","Cuba","dark","Afrocuban"], ["dark","green","hybrid form colors"], "Georges Pompidou Centre, Paris", "Hybrid figures in a dark tropical landscape—Lam's synthesis of Cubism and Afro-Cuban imagery.", "Lam's Zambezia paintings are among his most mature statements. The title refers to an African landscape of spiritual power.", "male","Cuban"),
    # ASIAN CONTEMPORARY NEW
    ("Liu Wei: Purple Air", "Liu Wei", 2006, "Oil on canvas", "Contemporary Chinese", ["figurative","chinese","political","large scale","dark"], ["dense buildings","vertical strata","urban China","dark layers"], ["dark purple","grey","urban dense strata"], "Various collections", "Dense strata of buildings and urban material in dark purple and grey—a vision of Chinese urban accumulation.", "Liu Wei's architectural paintings address the rapid urbanization of China as both physical fact and psychological condition.", "male","Chinese"),
    ("Cheng Jie: Landscape of the Body", "Cheng Jie", 2008, "Oil on canvas", "Contemporary Chinese", ["figurative","nude","landscape","hybrid","painterly"], ["female figure","landscape elements","merged","hybrid painting"], ["warm flesh","landscape color","merged forms"], "Various collections", "A female figure merges with a landscape—body and terrain becoming inseparable.", "Cheng Jie's figure-landscape paintings reflect a specifically Chinese relationship between body and nature rooted in classical landscape tradition.", "female","Chinese"),
    ("Cai Guo-Qiang: Project to Extend the Great Wall by 10,000 Meters", "Cai Guo-Qiang", 1993, "Gunpowder performance documentation", "Contemporary Chinese", ["performance","gunpowder","great wall","epic","ephemeral"], ["gunpowder fuse","desert","great wall","extension","night"], ["fire trail","dark desert","great wall"], "Jiayuguan, China (documentation)", "10,000 meters of gunpowder fuse extending the Great Wall into the Gobi Desert, ignited at night.", "The most epic of Cai's gunpowder works. The temporary fire extension of the Wall addresses Chinese cultural identity and its limits.", "male","Chinese"),
    ("Lee Bul: Cyborg W1", "Lee Bul", 1998, "Silicone, paint, steel", "Contemporary Korean", ["sculpture","cyborg","female","fragmented","contemporary"], ["cyborg figure","fragmented","silicone","steel","female cyborg"], ["white silicone","steel","fragment"], "Various museums", "A fragmented female cyborg figure in white silicone—missing limbs creating an uncanny beauty.", "Lee Bul's cyborg series combines feminist critique of technology with the physical beauty of idealized female form—and its deliberate fragmentation.", "female","Korean"),
    ("Do Ho Suh: Seoul Home/L.A. Home", "Do Ho Suh", 1999, "Silk and metal armature", "Contemporary Korean", ["installation","translucent silk","home","diaspora","memory"], ["Korean house","translucent fabric","displacement","memory","architecture"], ["pale silk","translucent domestic space"], "Various museums", "A full-scale translucent silk replica of the artist's Seoul childhood home—portable and ghostly.", "Suh carries his Korean home with him as silk—migration made architectural. The translucent material makes the home simultaneously present and absent.", "male","Korean"),
    ("Takashi Murakami: And Then, and Then, and Then, and Then, and Then...", "Takashi Murakami", 1996, "Acrylic on canvas", "Superflat / Japanese", ["superflat","mushroom","psychedelic","flat","japanese"], ["mushroom character","Mr DOB","flat color","psychedelic"], ["vivid flat color","psychedelic","mushroom pattern"], "Various collections", "Mr DOB, Murakami's cartoon character, surrounded by repeated mushroom imagery in flat psychedelic color.", "Murakami's Mr DOB character began as an exploration of Japanese consumer culture and anime aesthetics. The repetition mirrors consumer production.", "male","Japanese"),
    # EUROPEAN CONTEMPORARY NEW
    ("Richter: Abstract Painting (700-2)", "Gerhard Richter", 1982, "Oil on canvas", "Painting / German", ["abstract","squeegee","grey","layered","photographic"], ["grey layered paint","squeegee texture","abstract surface","grey"], ["grey","cream layered texture","squeegee marks"], "Various collections", "Layers of grey oil paint pulled with a squeegee into a complex geological surface.", "Richter's early squeegee paintings begin his long investigation of grey abstraction. The surface reads as both painting and photograph.", "male","German"),
    ("Baselitz: Untitled (Eagle)", "Georg Baselitz", 1972, "Oil on canvas", "Neo-Expressionism / German", ["expressionist","inverted eagle","heroic inversion","raw paint","german"], ["inverted eagle","German symbol","raw painting","upside down"], ["vivid red","yellow","raw paint","inverted"], "Various collections", "The German eagle painted upside-down—Baselitz's inversion of nationalist symbol.", "Baselitz's inversion of the German eagle is his most explicitly political image—the national symbol de-nationalized by being turned upside down.", "male","German"),
    ("Polke: Girlfriends", "Sigmar Polke", 1965, "Dispersion on canvas", "Pop Art / German", ["pop art","halftone","female figures","ironic","german pop"], ["two women","halftone dots","female figures","pop irony"], ["benday dot grey","cream","ironic pop"], "Staatsgalerie Stuttgart", "Two women in a park, rendered in Polke's signature oversized halftone dots—German Pop Art at its most characteristic.", "Polke's early paintings use the Raster (halftone dot) grid to both mimic and critique consumer image culture.", "male","German"),
    ("Immendorff: Happy New Year (MAO HOPE)", "Jörg Immendorff", 1975, "Acrylic on canvas", "Neo-Expressionism / German", ["expressionist","political","colorful","ironic","german"], ["political figures","carnival masks","MAO text","colorful"], ["vivid color","dense figures","political"], "Various collections", "Political figures in carnival masks celebrate—a colorful political allegory mixing communist and capitalist symbols.", "Immendorff's political paintings address the absurdity of left politics in a divided Germany with baroque satirical excess.", "male","German"),
    ("Penck: Standart", "A.R. Penck (Ralf Winkler)", 1970, "Synthetic resin on canvas", "Neo-Expressionism / German", ["expressionist","stick figure","political","primitive","east germany"], ["stick figures","symbols","primitive mark","political"], ["black","white","red","stick figure symbols"], "Museum Ludwig, Cologne", "Stick figures, symbols, and geometric marks in a primitive visual language—communication under censorship.", "Penck (East German artist) developed a stick-figure language to communicate under Stasi surveillance. The primitive figures carry political urgency.", "male","German"),
    # FRENCH POST-WAR NEW
    ("Hartung: T1963-R13", "Hans Hartung", 1963, "Oil on canvas", "Lyrical Abstraction / French", ["lyrical abstraction","gestural","dark","expressive","abstract"], ["gestural marks","dark scratches","expressive lines","dark ground"], ["dark blue","grey","sharp scratched lines"], "Various collections", "Sharp scratched gestural lines on a dark ground—Hartung's most characteristic abstract expression.", "Hartung was among the first European gestural abstractionists. His scratched lines have a speed and violence that American Abstract Expressionists respected.", "male","German-French"),
    ("Wols: Untitled (Composition)", "Wols (Wolfgang Schulze)", 1947, "Oil on canvas", "Art Informel / German-French", ["informal","gestural","delicate","web","anxiety"], ["web of lines","fragile","anxiety","delicate marks","informal"], ["pale ground","dark delicate web","anxiety"], "Various collections", "A web of delicate lines and blots on a pale ground—anxiety made visible in the most fragile marks.", "Wols died at 38 of food poisoning. His tiny, intense paintings created Art Informel. Sartre wrote about him as the painter of existential anxiety.", "male","German"),
    ("Mathieu: Hommage aux Poètes du Monde Entier", "Georges Mathieu", 1956, "Oil on canvas", "Lyrical Abstraction / French", ["lyrical abstraction","calligraphic","fast","performative","abstract"], ["calligraphic gestures","fast marks","performative","abstract"], ["vivid color","gestural calligraphy","speed marks"], "Various collections", "Calligraphic gestures made at high speed across a large canvas in a painting performance.", "Mathieu painted this in public—dressed in costume, working at high speed. He was the first painter to make speed itself a performative element.", "male","French"),
    # MORE ITALIAN
    ("Morandi: Landscape of Grizzana", "Giorgio Morandi", 1931, "Oil on canvas", "Metaphysical / Italian", ["landscape","quiet","hills","subtle","morandi"], ["hills","trees","village","subtle tones","quiet"], ["warm ochre","grey blue","quiet tones"], "Pinacoteca di Brera, Milan", "The hills of Grizzana in Morandi's characteristic quiet, dusty tones.", "Morandi painted the same Apennine landscape near his family home every summer. His landscapes have the same dusty quietude as his bottles.", "male","Italian"),
    ("De Pisis: Marine Still Life", "Filippo De Pisis", 1929, "Oil on canvas", "Italian Modernism", ["marine","still life","italian","loose","impressionistic"], ["fish","seafood","loose paint","italian impressionism","fresh"], ["silver fish","blue","loose impressionistic marks"], "Various collections", "Fish and seafood in a loose, painterly Italian Impressionist style.", "De Pisis was Italy's most gifted painter in the generation between the Futurists and post-war abstraction—overlooked internationally but supreme in lyrical observation.", "male","Italian"),
    ("Sironi: Urban Landscape", "Mario Sironi", 1922, "Oil on canvas", "Metaphysical / Italian", ["metaphysical","urban","dark","lonely","industrial"], ["industrial suburb","trucks","dark factory","lonely landscape","Italian"], ["dark grey","industrial ochre","lonely","desolate urban"], "Private collection", "A dark industrial suburb with trucks and factories—Sironi's vision of urban alienation.", "Sironi's urban suburbs are the most original Italian contribution to the inter-war urban imagery. Dark, existential, and without parallel.", "male","Italian"),
    # AFRICAN NEW
    ("Chéri Samba: J'aime la couleur", "Chéri Samba", 1997, "Oil on canvas", "Contemporary Congolese", ["figurative","colorful","political","popular culture","text"], ["artist figure","paint","colorful","text in painting","self-referential"], ["vivid primary colors","cartoon quality","text"], "Various collections", "Chéri Samba painting himself painting—a colorful self-referential image with text commenting on art and color.", "Samba's paintings combine popular imagery with direct political and social commentary. His work is deeply embedded in Kinshasa popular culture.", "male","Congolese"),
    ("Sidi el Houari: Hammam Troupers", "Sidi el Houari", 1985, "Watercolor", "Contemporary Moroccan", ["watercolor","bathhouse","colorful","social","moroccan"], ["hammam","bathers","social scene","moroccan","colorful"], ["vivid color","steam atmosphere","moroccan tiles"], "Various collections", "A Moroccan hammam (bathhouse) with bathers—colorful social scene in vivid watercolor.", "El Houari's watercolors document Moroccan social life with affectionate humor. The hammam as social institution is unique to North African culture.", "male","Moroccan"),
    ("El Glaoui: Fantasia", "Mohamed Ben Ali Rbati (El Glaoui)", 1930, "Oil on canvas", "Moroccan Orientalism", ["equestrian","moroccan","colorful","traditional","fantasia"], ["horsemen","rifles","traditional dress","fantasia","gunpowder"], ["vivid robes","desert dust","horsemen","dramatic"], "Various collections", "Moroccan horsemen in a fantasia (traditional cavalry display)—rifles fired in unison.", "El Glaoui was the first Moroccan painter to gain international recognition, painting traditional Moroccan life in an oil painting tradition.", "male","Moroccan"),
    # SOUTH ASIAN NEW
    ("Seema Kohli: The Hiranyagarbha (Golden Womb)", "Seema Kohli", 2015, "Acrylic and gold leaf on canvas", "Contemporary Indian", ["contemporary","gold leaf","spiritual","feminine","cosmological"], ["feminine form","cosmic egg","gold","spiritual","goddess"], ["gold leaf","vivid blue","cosmic forms"], "Various collections", "A feminine cosmic figure within the golden womb of creation—spiritual and physical united in gold.", "Kohli's goddess-centered cosmological paintings draw on ancient Indian textual traditions. The golden womb is both metaphysical and bodily.", "female","Indian"),
    ("Mrinalini Mukherjee: Devi", "Mrinalini Mukherjee", 1988, "Hemp fiber sculpture", "Contemporary Indian / Sculpture", ["sculpture","fiber","goddess","organic","monumental"], ["hemp fiber","woven sculpture","goddess form","organic","monumental"], ["natural hemp","earthy texture","knotted fibers"], "National Gallery of Modern Art, New Delhi", "A massive female deity form woven from hemp fiber—organic and monumental.", "Mukherjee's hemp fiber sculptures have no precedent in world art. They combine tribal craft with monumental sculptural ambition.", "female","Indian"),
    ("Atul Dodiya: Mahatma—Life of Gandhi series", "Atul Dodiya", 1999, "Watercolor on paper", "Contemporary Indian", ["watercolor","political","gandhi","historical","figurative"], ["Gandhi","non-violence","spinning wheel","historical figure"], ["warm watercolor","historical wash","intimate"], "Various collections", "A Gandhi-series watercolor—intimate and historical simultaneously.", "Dodiya's Gandhi series meditates on non-violence and Indian political identity through a surprisingly intimate watercolor technique.", "male","Indian"),
    # OCEANIC NEW
    ("Oceanic Baining Fire Dance Mask", "Baining craftsmen, Papua New Guinea", 1970, "Bark, paint, bamboo", "Melanesian / Pacific", ["mask","fire","ceremonial","nighttime","dramatic"], ["night fire dance","bark mask","eyes","ceremonial","performance"], ["white bark","red painted","natural pigments"], "Various museums", "A mask used in the Baining nocturnal fire dance—worn by dancers who leap through fire.", "The Baining fire dances are among the most dramatic ritual performances in the Pacific. The white bark masks transform the dancers into spirits.", "unknown","Papua New Guinean"),
    ("Sepik Nggwalndu Yam Mask", "Sawos people, Papua New Guinea", 1920, "Wicker and paint", "Melanesian / Pacific", ["mask","ceremonial","fertility","woven","spiritual"], ["woven mask","fertility","yam spirit","large eyes","red paint"], ["woven natural","red","white","ceremonial"], "Ethnologisches Museum, Berlin", "A large woven ceremonial mask representing the spirit of the yam—fertility and abundance.", "The yam spirits are central to Sepik religious life. The large woven masks are worn in ceremonies to ensure good harvests.", "unknown","Papua New Guinean"),
    # CENTRAL ASIAN
    ("Shirin Alieva: Women Gathering Cotton", "Shirin Alieva", 1955, "Oil on canvas", "Soviet Central Asian Realism", ["social realist","women workers","central asia","uzbekistan","labor"], ["women","cotton picking","uzbekistan","labor","heroic"], ["white cotton","warm skin","blue sky","socialist realism"], "State Museum of Arts, Tashkent", "Uzbek women harvest cotton in warm Central Asian light—socialist realism applied to traditional labor.", "Alieva was a pioneering Uzbek female artist working within Soviet social realism while documenting traditional Uzbek women's culture.", "female","Uzbek"),
    # PHOTOGRAPHY NEW
    ("Germaine Krull: Métal", "Germaine Krull", 1928, "Gelatin silver print series", "Photography / Dutch-French", ["photograph","industrial","architectural","modernist","metal"], ["Eiffel Tower","metal structures","industrial","dynamic","geometric"], ["black and white","industrial metal","dynamic angle"], "Various collections", "The Eiffel Tower and industrial structures photographed from radical angles—a book of metallic modernism.", "Krull's Métal was the first photobook to treat industrial structures as aesthetic subjects. Her radical angles influenced a generation of photographers.", "female","Dutch"),
    ("Brassaï: Paris by Night", "Brassaï (Gyula Halász)", 1932, "Gelatin silver print", "Photography / Hungarian-French", ["photograph","nocturnal","Paris","documentary","atmospheric"], ["Paris at night","streetlamps","wet pavement","nocturnal","cafe"], ["black and white","night wet pavement","gas lights"], "Various collections", "Paris streets at night with gas lights reflected in wet cobblestones—Brassaï's classic nocturnal documentary.", "Brassaï became the definitive photographer of Paris by night, documenting cafes, brothels, and street life that the city officially denied.", "male","Hungarian"),
    ("Bill Brandt: Nipplegate (Nude)", "Bill Brandt", 1956, "Gelatin silver print", "Photography / British", ["photograph","nude","distorted","beach","formal"], ["nude figure","beach","pebbles","distorted wide angle","coastal"], ["black white","pebble beach","distorted nude form"], "Various collections", "A nude figure on a beach with a wide-angle lens that dramatically distorts the body.", "Brandt's nude series used an extreme wide-angle lens (with pinhole aperture) to create a new kind of bodily abstraction.", "male","British"),
    ("Horace Pippin: Holy Mountain I", "Horace Pippin", 1944, "Oil on canvas", "African American / Self-taught", ["self-taught","visionary","biblical","peace","naive"], ["lion","lamb","paradise","children playing","peace"], ["green paradise","animals","peaceful colors"], "Smithsonian American Art Museum", "A visionary paradise where lions and lambs play peacefully with children—Pippin's vision of the promised land.", "Pippin painted the Holy Mountain series during WWII as a counter-vision to global violence. His naive visionary paradise is profoundly moving.", "male","American"),
    ("Jacob Lawrence: Harriet Tubman series", "Jacob Lawrence", 1940, "Casein tempera", "African American / Social Realism", ["flat","graphic","narrative","historical","liberation"], ["Harriet Tubman","escape","north star","liberation","flat graphic"], ["dark grey","flat pattern","liberation narrative"], "Hampton University Museum, Virginia", "A panel from Lawrence's Harriet Tubman series—flat graphic narrative of liberation.", "Lawrence's Harriet Tubman series preceded the Migration series. His flat, graphic narrative style drew on African textile and mask traditions.", "male","American"),
    # MORE ABSTRACT EXPRESSIONIST
    ("Pollock: Autumn Rhythm (Number 30)", "Jackson Pollock", 1950, "Oil on canvas", "Abstract Expressionism / American", ["drip painting","gestural","large scale","autumn","allover"], ["drip","brown","black","grey","allover composition"], ["brown","grey","black","beige","allover"], "Metropolitan Museum of Art, New York", "A vast all-over drip painting in warm browns and greys—the rhythm of autumn made into paint.", "One of Pollock's finest drip paintings—the warm autumn palette gives it a landscape quality despite its pure abstraction.", "male","American"),
    ("De Kooning: Woman VI", "Willem de Kooning", 1953, "Oil on canvas", "Abstract Expressionism / American", ["gestural","figurative","woman","aggressive","expressive"], ["woman figure","aggressive marks","flesh tones","threatening"], ["flesh orange","black","aggressive paint","gestural"], "Carnegie Museum of Art, Pittsburgh", "One of de Kooning's Woman series—figure emerging from aggressive gestural paint.", "De Kooning's Woman series was controversial for its aggression. The women are simultaneously threatening, absurd, and deeply human.", "male","Dutch-American"),
    ("Motherwell: Je t'aime series", "Robert Motherwell", 1955, "Oil and charcoal on canvas", "Abstract Expressionism / American", ["gestural","text","love","abstract","intimate"], ["French text","gestural marks","intimate","personal"], ["cream","gestural charcoal","text fragments"], "Various collections", "French love phrases embedded in gestural marks—personal and intimate Abstract Expressionism.", "Motherwell's Je t'aime paintings are his most personal—love and painting literally merged. The French phrases honor his French wife.", "male","American"),
    ("Guston: Deluge I", "Philip Guston", 1969, "Oil on canvas", "Abstract Expressionism / American", ["abstract","atmospheric","pink","transition","hovering"], ["pink atmospheric marks","hovering cluster","transition work"], ["pink grey","atmospheric","clustering marks"], "Various collections", "A pink atmospheric abstraction from Guston's transitional period.", "Guston painted these pink 'transitional' works while moving from abstraction back toward figuration. They hover between two worlds.", "male","American"),
    # MINIMALISM & CONCEPTUAL NEW
    ("Martin: With My Back to the World", "Agnes Martin", 1997, "Acrylic on canvas", "Minimalism / American", ["minimal","horizontal bands","meditative","pale","transcendent"], ["pale bands","horizontal","meditative","transcendent"], ["pale grey","cream","delicate horizontal bands"], "Tate Modern, London", "Pale horizontal bands on an almost white canvas—Martin's meditative transcendence.", "Martin's late paintings become progressively quieter—approaching silence without reaching it. This is her most personal title.", "female","Canadian-American"),
    ("Flavin: Greens Crossing Greens", "Dan Flavin", 1966, "Fluorescent light fixtures", "Minimalism / American", ["minimal","green light","crossing","fluorescent","environmental"], ["green fluorescent tubes","crossing pattern","corner installation","environmental"], ["vivid green light","industrial tube","dark room"], "Various collections", "Green fluorescent tubes installed to cross in a corner—light as the primary medium.", "Flavin's green crossing lights turn a gallery corner into a luminous environment. The industrial material creates a non-industrial beauty.", "male","American"),
    ("Turrell: Afrum (White)", "James Turrell", 1966, "Projected light", "Light Art / American", ["light art","projected","illusionistic","cube","perception"], ["light cube","corner projection","floating","perception trick","white"], ["white light cube","gallery white","floating illusion"], "Various museums", "A projected cube of white light appears to float in a white gallery corner.", "Turrell's first corner projections used light to create volumetric forms that appeared solid but were pure light. The cube seems to protrude from the corner.", "male","American"),
    # MORE CONTEMPORARY
    ("Basquiat: Profit I", "Jean-Michel Basquiat", 1982, "Acrylic and oil stick on canvas", "Neo-Expressionism / American", ["neo-expressionist","crown","text","graffiti","black culture"], ["crown","SAMO","text","figure","race commerce"], ["vivid color","crown mark","text fragments"], "Various collections", "Text, crown symbols, and gestural figures address race and commerce.", "Basquiat's crown motif appears throughout his work—simultaneously a royal symbol and a protest against those who deny black nobility.", "male","American"),
    ("Koons: New Hoover Convertibles", "Jeff Koons", 1981, "Vacuum cleaners, plexiglass, fluorescent light", "Neo-Geo / American", ["neo-geo","consumer objects","display","pristine","conceptual"], ["vacuum cleaners","plexiglass case","fluorescent light","pristine","display"], ["cream white hoovers","plexiglass clear","fluorescent"], "Saatchi Collection, London", "New Hoover vacuum cleaners in a plexiglass case with fluorescent lighting—consumer goods as eternal objects.", "Koons's first major work. The pristine vacuum cleaners in illuminated plexiglass cases treat domestic appliances as sacred objects.", "male","American"),
    ("Hirst: Thousands of Years", "Damien Hirst", 1990, "Steel, glass, MDF, insect-o-cutor, flies, cow's head", "Young British Artists", ["installation","life and death","flies","decay","natural cycle"], ["cow head","flies","maggots","fly killer","life cycle"], ["natural decay colors","steel white","institutional"], "Saatchi Gallery, London", "A cow's head decomposes in one compartment while flies breed and are killed by an insect-o-cutor in another.", "Hirst's first large-scale installation—the natural cycle of life and death made mechanically visible in a hermetic box.", "male","British"),
    ("Emin: I've Got It All", "Tracey Emin", 2000, "Photograph", "Young British Artists", ["photograph","feminist","money","success","autobiographical"], ["artist sitting","cash and coins","lap","success","money"], ["cash color","seated figure","success"], "Various collections", "Emin sits cross-legged clutching banknotes and coins in her lap—success and its embarrassments.", "A response to her unexpected commercial success. The image is simultaneously triumphant and self-mocking about wealth in art.", "female","British"),
    ("Muñoz: Conversation Piece", "Juan Muñoz", 1996, "Bronze", "Contemporary Spanish / Sculpture", ["sculpture","bronze","figures","conversation","space"], ["standing figures","looking away","conversation","bronze","small scale"], ["dark bronze","human scale","looking away"], "Various museums", "Bronze figures in conversation—but each looking away from the other.", "Muñoz's figures always fail to connect. The conversation piece is a non-conversation. His work is about loneliness disguised as society.", "male","Spanish"),
    ("Plensa: Awilda", "Jaume Plensa", 2008, "White painted stainless steel", "Contemporary Spanish / Sculpture", ["sculpture","letters","face","head","text"], ["woman's face","letters spelling name","white steel","serene"], ["white painted steel","letter text","serene face"], "Various public installations", "A woman's serene face formed from letters spelling her name in white painted steel.", "Plensa builds portraits from the letters of words—the face as text, the person as language. His letter-faces appear in public spaces worldwide.", "male","Spanish"),
    # ADDITIONAL SPANISH
    ("Sorolla: Children on the Beach", "Joaquín Sorolla", 1910, "Oil on canvas", "Spanish Impressionism", ["impressionistic","beach","children","light","luminous"], ["children on beach","sea","Mediterranean light","summer","shadows"], ["vivid summer light","blue sea","white sand","children"], "Various collections", "Children play on a Valencia beach in blazing Mediterranean light—Sorolla's luminous signature.", "Sorolla is Spain's greatest Impressionist. His beach scenes capture the brilliant white light of Valencia like no other painter.", "male","Spanish"),
    ("Sorolla: Oxen on the Beach", "Joaquín Sorolla", 1903, "Oil on canvas", "Spanish Impressionism", ["impressionistic","beach","oxen","labor","luminous"], ["oxen","boat","Mediterranean beach","labor","vivid light"], ["white oxen","blue sea","brilliant light","labor"], "Various collections", "White oxen pull a fishing boat onto the Valencia beach in brilliant sunlight.", "Sorolla's most powerful subject—the white oxen in Mediterranean light. The combination of labor and luminosity is unique in Spanish art.", "male","Spanish"),
    ("Mir: El jardín de Aranjuez", "Joaquim Mir", 1908, "Oil on canvas", "Spanish Modernism / Post-Impressionism", ["post-impressionist","landscape","vibrant","spanish","garden"], ["Aranjuez garden","vibrant color","romantic landscape","trees","spain"], ["vivid green","golden light","post-impressionist"], "Museu Nacional d'Art de Catalunya, Barcelona", "The gardens of Aranjuez in vibrant post-Impressionist color.", "Mir is the greatest Catalan landscape painter. His explosive color of the royal gardens was radical for Spanish painting.", "male","Spanish"),
    # ADDITIONAL AUSTRALIAN
    ("Fred Williams: Landscape with Dead Trees", "Fred Williams", 1964, "Oil on canvas", "Australian Modernism", ["modernist","landscape","australian","abstract","dead trees"], ["sparse trees","ochre landscape","abstract australian landscape"], ["ochre","grey blue","sparse marks"], "National Gallery of Australia", "The Australian bush as abstract marks—dead trees becoming gestural gestures on ochre ground.", "Williams transformed the Australian landscape into a new kind of abstract painting. His 'You Yangs' series is definitive of Australian landscape painting.", "male","Australian"),
    ("Grace Crowley: Composition", "Grace Crowley", 1940, "Oil on canvas", "Australian Modernism / Abstract", ["abstract","geometric","australian","pioneer","constructivist"], ["geometric forms","constructivist","pioneer abstract","australian"], ["cream","grey","geometric Australian abstract"], "Art Gallery of New South Wales", "A geometric abstract composition—one of Australia's earliest truly abstract paintings.", "Crowley introduced European constructivism to Australia. She is the pioneer of Australian abstract art, largely overlooked until recently.", "female","Australian"),
    # ADDITIONAL CANADIAN
    ("Paul-Émile Borduas: Automatist composition", "Paul-Émile Borduas", 1949, "Oil on canvas", "Quebec Automatism / Canadian", ["automatist","abstract","gestural","quebec","movement"], ["gestural abstraction","dark ground","white marks","automatism"], ["dark ground","white gestures","automatism"], "Musée des beaux-arts de Montréal", "Gestural white marks on a dark ground—Borduas's automatist painting from his Refus Global period.", "Borduas's Refus Global manifesto (1948) launched Quebec's cultural revolution. His automatist paintings paralleled American AbEx independently.", "male","Canadian"),
    ("Jean-Paul Riopelle: Iceberg (abstract)", "Jean-Paul Riopelle", 1977, "Oil on canvas", "Lyrical Abstraction / Canadian", ["lyrical abstraction","palette knife","colorful","mosaic","impasto"], ["arctic iceberg","palette knife mosaic","vivid color","impasto"], ["vivid arctic blue","white","palette knife texture"], "National Gallery of Canada, Ottawa", "Icebergs rendered in palette-knife mosaic of vivid blue and white—Riopelle's arctic period.", "Riopelle's palette-knife technique creates a mosaic of pure color. His arctic series from the 1970s is among his finest work.", "male","Canadian"),
    # ADDITIONAL NEW ZEALAND
    ("Len Lye: Water Whirler (kinetic)", "Len Lye", 1965, "Steel and motor", "Kinetic Art / New Zealand", ["kinetic","steel","motion","spiraling","light"], ["steel ribbon","motor","spiral motion","light reflection"], ["silver steel","motion blur","reflected light"], "Govett-Brewster Art Gallery, New Plymouth", "A motorized steel ribbon that whirls at high speed—light and steel in perpetual motion.", "Lye invented kinetic sculpture in New Zealand before doing so internationally. His steel sculptures dance with energy that is simultaneously delicate and powerful.", "male","New Zealand"),
    # ADDITIONAL MIDDLE EASTERN
    ("Adel Abidin: Abidin Travels (video still)", "Adel Abidin", 2006, "Video installation", "Contemporary Iraqi-Finnish", ["video","travel","iraq","diaspora","political"], ["travel agency","Iraq as destination","political irony","video"], ["travel agency colors","video still quality"], "Various museums", "A fictional travel agency advertising 'Exciting Iraq'—political irony about the Iraq War.", "Abidin's video addresses the Western representation of Iraq as a war zone by satirically presenting it as a tourist destination.", "male","Iraqi"),
    ("Mona Saudi: Sculpture for Peace", "Mona Saudi", 1972, "Marble", "Contemporary Jordanian", ["sculpture","marble","abstract","organic","peace"], ["abstract organic form","marble","carved","smooth","peace"], ["white marble","smooth carved"], "Various collections", "A smooth organic marble form—abstract and serene.", "Saudi is the foremost Arab woman sculptor. Her marble works combine European abstract sculpture with a distinctly Arab aesthetic of form.", "female","Jordanian"),
    # ADDITIONAL AFRICAN CONTEMPORARY
    ("Gonçalo Mabunda: Throne", "Gonçalo Mabunda", 2005, "Decommissioned weapons", "Contemporary Mozambican", ["sculpture","weapons","political","throne","post-conflict"], ["AK47 parts","throne form","war decommissioned weapons","power"], ["metallic weapon parts","functional objects repurposed"], "Various museums", "A throne made from decommissioned AK-47s and land mines—military power transformed into ceremonial furniture.", "Mabunda uses weapons from Mozambique's civil war to create furniture and ceremonial objects—transforming instruments of death into objects of culture.", "male","Mozambican"),
    ("Aïcha Hamu: The Market", "Aïcha Hamu", 1989, "Oil on canvas", "Contemporary Algerian", ["figurative","market","women","algeria","colorful"], ["market scene","women","traditional dress","vivid","Algeria"], ["vivid cloth colors","Algeria market","figurative"], "Various collections", "Women at an Algerian market in vivid traditional dress.", "Hamu is among the most important Algerian women artists. Her figurative works document Algerian women's social space.", "female","Algerian"),
    # ADDITIONAL PHOTOGRAPHY
    ("Yasumasa Morimura: Art History (Manet: Olympia)", "Yasumasa Morimura", 1990, "Color photograph", "Conceptual Photography / Japanese", ["photograph","appropriation","art history","body","race"], ["self-portrait as Olympia","Manet reworking","Japanese face","body substitution"], ["reclining nude photography","Japanese artist's face"], "Various museums", "Morimura substitutes his own Japanese face for every figure in Manet's Olympia.", "Morimura's Art History series inserts his Japanese face into canonical Western artworks—asking what Asian bodies do to Western art history.", "male","Japanese"),
    ("Wolfgang Laib: Pollen from Hazelnut", "Wolfgang Laib", 1992, "Pollen on floor", "Minimalism / German", ["minimal","pollen","floor","natural material","transcendent"], ["pollen field","yellow","floor","natural","transcendent"], ["vivid yellow pollen","floor","pure material"], "Various museums", "A luminous yellow rectangle of hazelnut pollen sieved directly onto a museum floor.", "Laib spends months collecting pollen—then places it on the floor to be destroyed when the exhibition ends. The most lyrical minimal work ever made.", "male","German"),
    ("Harun Farocki: Images of the World and the Inscription of War", "Harun Farocki", 1988, "Video installation", "Essay Film / German", ["essay film","political","image analysis","war","documentary"], ["aerial photographs","auschwitz","World War II","image politics","vision"], ["documentary video quality","archival photographs"], "Various museums", "An essay film questioning why Allied bomb-damage photographs showing Auschwitz were not recognized for what they showed.", "Farocki's essay films are the most rigorous analyses of political images. This film about the invisibility of Auschwitz in wartime photographs is devastating.", "male","German"),
    # ADDITIONAL CONTEMPORARY
    ("Kara Walker: Gone: An Historical Romance", "Kara Walker", 1994, "Cut paper silhouettes", "Contemporary American", ["silhouette","historical","race","slavery","cut paper"], ["slavery","antebellum south","silhouettes","history","romance"], ["black cut paper","white wall","historical scene"], "Museum of Modern Art, MoMA", "The first major silhouette installation depicting antebellum slavery—a panoramic scene of brutality and desire.", "Kara Walker's debut museum installation caused enormous controversy in the African American art community. The silhouette tradition was transformed into historical critique.", "female","American"),
    ("Yinka Shonibare: The Sleep of Reason Produces Monsters (Africa)", "Yinka Shonibare", 2008, "Mixed media tableau with mannequin", "Contemporary British-Nigerian", ["tableau","goya reference","colonial","africa","mannequin"], ["sleeping figure","African batik","colonial nightmares","Goya reference"], ["vivid batik patterns","mannequin skin","dramatic tableau"], "Various museums", "A sleeping mannequin in Dutch wax batik clothing with colonial-era documents—after Goya's Sleep of Reason.", "Shonibare updates Goya's etching to address colonial Africa—the monsters that the sleep of European reason produced were the African colonial enterprise.", "male","Nigerian-British"),
    ("El Anatsui: Untitled (Strips)", "El Anatsui", 1991, "Wood and paint", "Contemporary Ghanaian", ["carved wood","painted strips","geometric","abstract","west african"], ["painted wooden strips","geometric","abstract pattern"], ["bright color","wood strips","geometric"], "Various collections", "Painted wooden strips in geometric arrangements—El Anatsui's pre-aluminum-tapestry period.", "El Anatsui began with carved and painted wood before discovering the bottle-cap tapestry form. These early works show the geometric basis of his aesthetic.", "male","Ghanaian"),
    ("Othoniel: Necklace of the Moon", "Jean-Michel Othoniel", 2004, "Murano glass", "Contemporary French", ["sculpture","glass","colorful","beads","architectural"], ["glass beads","necklace","colorful","Murano","decorative"], ["vivid glass colors","reflective","spherical"], "Various public spaces", "A public sculpture of enormous colored Murano glass beads looped over an urban structure.", "Othoniel's glass bead sculptures combine decorative beauty with monumental scale. His Kiosk des Noctambules at the Palais Royal metro is his most visible work.", "male","French"),
    ("Messager: My Vows", "Annette Messager", 1988, "Photographs, black-and-white prints, red thread", "Feminist Conceptual / French", ["feminist","installation","body parts","thread","intimate"], ["black and white photographs","body parts","red thread","vow","intimate"], ["black and white photographs","red thread web"], "Musée d'Art Moderne, Paris", "Black-and-white photographs of body parts connected by red thread covering an entire wall.", "Messager's vow installations address the female body as fragmented by the male gaze. The red thread stitches the fragments back together—but in a new order.", "female","French"),
    ("Boltanski: Monument (Odessa)", "Christian Boltanski", 1990, "Photographs, tin biscuit boxes, lights", "Conceptual / French", ["installation","memorial","holocaust","photographs","light"], ["children's photographs","tin boxes","light bulb","memorial","death"], ["black and white photographs","warm bulb light","tin box"], "Various museums", "Children's school photographs backlit by bare bulbs above stacks of biscuit tins—a memorial to the Holocaust.", "Boltanski's monuments use the detritus of anonymous lives to mourn the anonymous dead. The biscuit tins suggest ashes.", "male","French"),
    ("Bourgeois: The Arch of Hysteria", "Louise Bourgeois", 1993, "Bronze", "Contemporary French-American", ["sculpture","bronze","hysteria","arched body","psychological"], ["arched male body","bronze","hysteria","psychological","gender"], ["dark bronze","arched tension","wall mounted"], "Various collections", "An arched male figure in bronze—convulsed in a pose associated with female hysteria.", "Bourgeois's Arch of Hysteria reverses the gender assignment of the condition—giving a male body the posture historically attributed to female psychology.", "female","French-American"),
    ("Kapoor: Yellow", "Anish Kapoor", 1999, "Fiberglass and pigment", "Contemporary British-Indian", ["sculpture","yellow","pigment","concave","void"], ["concave yellow form","void","pigment","wall sculpture","depth"], ["vivid yellow pigment","dark void center","wall mounted"], "Various collections", "A concave yellow form opening into apparent infinite depth.", "Kapoor's pigment sculptures draw the eye into a void that cannot exist in the object's actual depth. Color as spatial illusion.", "male","British-Indian"),
    ("Hirst: The Acquired Inability to Escape", "Damien Hirst", 1991, "Vitrine, office furniture, cigarettes, ashtray, smoke", "Young British Artists", ["installation","office furniture","smoke","prison","conceptual"], ["office desk","chair","cigarette smoke","glass vitrine","trapped"], ["office grey","cigarette smoke","glass reflection"], "Various collections", "An office desk and chair with a lit cigarette in a sealed glass case—work as prison.", "An office imprisoned in glass—the acquired inability to escape either work or cigarettes. One of Hirst's most concise conceptual pieces.", "male","British"),
    ("Cattelan: Him", "Maurizio Cattelan", 2001, "Polyester resin, wax, human hair, synthetic fibers", "Contemporary Italian", ["sculpture","small figure","kneeling","Hitler","conceptual"], ["small kneeling figure","Hitler","prayer pose","child size","wax"], ["dark suit","wax skin quality","small scale"], "Pinault Collection, Venice", "A small kneeling boy in prayer—when you walk around it, you see it is Hitler praying.", "One of the most controversial sculptures of the 21st century. Is it prayer? Mockery? Horror? Cattelan refuses to explain.", "male","Italian"),
    ("Murakami: In the Land of the Dead, Stepping on the Tail of a Rainbow", "Takashi Murakami", 2014, "Oil on canvas", "Superflat / Japanese", ["superflat","large scale","3/11 disaster","Japan","dark colorful"], ["tsunami aftermath","skulls","flowers","Japan disaster","superflat"], ["vivid color","skulls","flowers","superflat"], "Various collections", "An enormous canvas responding to the 2011 Tohoku earthquake and tsunami—skulls, flowers, and disaster in Superflat style.", "Murakami's most ambitious response to Japanese catastrophe. The Superflat style—usually associated with cute consumer culture—is here used for mourning.", "male","Japanese"),
    # FINAL ENTRIES TO COMPLETE 200
    ("Kentridge: Black Box/Chambre Noire", "William Kentridge", 2005, "Miniature theater installation", "Contemporary South African", ["installation","miniature theater","colonialism","namibia","genocide"], ["miniature theater","film projection","Namibia","German colonialism","animation"], ["dark miniature stage","light projection"], "Deutsche Guggenheim, Berlin", "A miniature theater with animated film addressing the 1904 Herero genocide by German colonizers in Namibia.", "Kentridge's miniature theater was commissioned by Deutsche Guggenheim—a German institution addressing a German colonial genocide in Africa.", "male","South African"),
    ("Kentridge: Stereoscope", "William Kentridge", 1999, "35mm film (animated charcoal drawing)", "Contemporary South African", ["animated drawing","charcoal","johannesburg","capitalism","duality"], ["two simultaneous scenes","mine owner","landscape","south africa","duality"], ["charcoal black","white paper","double image"], "Various museums", "A stereo film showing two simultaneous animated charcoal worlds—mine owner and landscape occupying the same space.", "Kentridge's stereoscopic films use the two-eyes of stereo vision to represent the divided reality of South Africa.", "male","South African"),
    ("Shirin Neshat: Logic of the Birds", "Shirin Neshat", 2001, "Two-channel video", "Contemporary Iranian", ["video","birds","sufi poetry","female","contemplative"], ["birds migration","women","Sufi poetry","landscape","meditation"], ["black and white","birds in sky","vast landscape"], "Various museums", "Women in black and white landscapes perform a journey related to Attar's Sufi poem Conference of the Birds.", "Neshat's most poetic film—Attar's Sufi pilgrimage becomes a meditation on female exile and spiritual journey.", "female","Iranian"),
    ("Shirin Neshat: Passage", "Shirin Neshat", 2001, "Video", "Contemporary Iranian", ["video","ritual","desert","fire circle","contemplative"], ["ritual burial","fire circle","desert","mourning women"], ["black and white desert","fire ring","women"], "Various museums", "A ritual burial ceremony—women in desert, men digging, a circle of fire.", "Neshat describes the ceremony in her film as crossing the boundary between life and death in an unnamed Iranian landscape.", "female","Iranian"),
    ("Ai Weiwei: Remembering", "Ai Weiwei", 2009, "9,000 children's backpacks on museum facade", "Contemporary Chinese", ["installation","backpacks","earthquake","memorial","political"], ["children's backpacks","facade","sichuan earthquake","memorial","colorful"], ["vivid backpack colors","museum facade","political memorial"], "Haus der Kunst, Munich", "9,000 colorful children's backpacks covering a museum facade spelling a mother's words: 'She lived happily for seven years.'", "A memorial to children who died in the 2008 Sichuan earthquake because of poorly built 'tofu schools'. Ai's most politically direct public memorial.", "male","Chinese"),
    ("Ai Weiwei: Template", "Ai Weiwei", 2007, "Wood doors and windows from demolished Ming and Qing dynasty houses", "Contemporary Chinese", ["sculpture","historic material","demolition","china","political"], ["salvaged wood","old house material","stacked","political","heritage"], ["grey weathered wood","aged door frames"], "Documenta, Kassel (collapsed by rain)", "A 9-meter structure of salvaged doors and windows from demolished historic Chinese houses—collapsed in a rainstorm.", "The collapse became part of the work. Ai accepted it—the demolition by nature completing what Chinese government began.", "male","Chinese"),
    ("Shen Shaomin: Unknown Pleasures", "Shen Shaomin", 2002, "Cement sculptures", "Contemporary Chinese", ["sculpture","bones","hybrid","grotesque","political"], ["hybrid animal skeletons","cement","grotesque forms","political"], ["grey cement","skeletal forms","hybrid creatures"], "Various museums", "Hybrid animal skeletons in cement—fantastical creatures that could not have lived.", "Shen creates impossible hybrid skeletons—part scientific specimen, part political satire. Their authoritative scientific display makes them disturbing.", "male","Chinese"),
    ("Yang Shaobin: Security No. 6", "Yang Shaobin", 2006, "Oil on canvas", "Contemporary Chinese", ["figurative","security forces","political","dark","oppressive"], ["security guard figures","dark suits","oppressive","political","confrontational"], ["dark suit","red background","political tension"], "Various collections", "Confrontational security guard figures in dark suits against red.", "Yang Shaobin addresses China's expanding security state through confrontational portraits of uniformed men.", "male","Chinese"),
    ("Fiona Hall: Paradisus Terrestris", "Fiona Hall", 1989, "Sardine tins, plants", "Contemporary Australian", ["installation","sardine tins","carved plants","botanical","ironic"], ["botanical garden in sardine tins","carved plants","medicinal plants","colonialist irony"], ["tin silver","carved plant green","botanical illustration"], "Art Gallery of New South Wales", "Sardine tins carved into botanical plant specimens—the collision of colonial trade and colonial botany.", "Hall carves each plant from a different sardine tin—the colonial project of botany and the colonial project of the food trade in the same object.", "female","Australian"),
    ("Gordon Bennett: Possession Island (Abstraction)", "Gordon Bennett", 1991, "Oil and synthetic polymer on canvas", "Contemporary Australian-Indigenous", ["conceptual","indigenous","colonial","history","painting"], ["colonial mapping","indigenous land","text fragments","history painting"], ["earth brown","text fragments","historical"], "Queensland Art Gallery", "A layered painting addressing colonial 'possession' of Indigenous Australian land—historical maps and Indigenous marks colliding.", "Bennett was a non-Indigenous artist with Indigenous ancestry who addressed the colonial construction of 'Aboriginality'. His work is foundational to Australian post-colonial art.", "male","Australian"),
    ("Vernon Ah Kee: unwritten", "Vernon Ah Kee", 2008, "Charcoal on paper", "Contemporary Indigenous Australian", ["charcoal","portrait","indigenous","confrontational","large scale"], ["indigenous man","direct gaze","large charcoal portrait","confrontational"], ["charcoal black","paper white","direct gaze"], "Various collections", "A monumental charcoal portrait of an Indigenous man with a direct, confrontational gaze.", "Ah Kee's large charcoal portraits assert the presence of Aboriginal Australians through the directness of the gaze—refusing to be invisible.", "male","Australian Indigenous"),
    ("Julie Mehretu: Mogamma (A Painting in Four Parts)", "Julie Mehretu", 2012, "Ink and acrylic on canvas", "Contemporary Abstract / Ethiopian-American", ["abstract","architectural","gestural","political","large scale"], ["architectural blueprints","gestural marks","political buildings","explosive"], ["grey architectural underpainting","vivid gestural marks"], "Moderna Museet, Stockholm", "Based on the Mogamma Building in Cairo (built by the Soviets)—architectural plans exploded into gestural marks during the Arab Spring.", "Mehretu used the architecture of Soviet-era Egyptian bureaucracy as the ground layer, then painted the explosive energy of the 2011 uprising over it.", "female","Ethiopian-American"),
    ("El Anatsui: Untitled (Waves)", "El Anatsui", 2010, "Aluminum and copper wire", "Contemporary Ghanaian", ["tapestry","aluminum","wave form","fluid","monumental"], ["cascading bottle caps","wave form","fluid wall hanging","monumental"], ["gold aluminum","copper wire","wave cascade"], "Various collections", "Bottle-cap tapestry hung to suggest ocean waves—the materiality of the African trade in liquor.", "El Anatsui's wave-hung tapestries are his most architectural—the wall as ocean surface.", "male","Ghanaian"),
    ("Saodat Ismailova: Chillakhona", "Saodat Ismailova", 2020, "Video installation", "Contemporary Uzbek", ["video","sufi","silk road","female mysticism","central asia"], ["sufi ritual","women","silk road","contemplative","light"], ["soft light","traditional dress","ritual movement"], "Various museums", "A video meditation on female Sufi devotion in Central Asia—the mystic tradition rarely depicted.", "Ismailova's films explore the female spiritual and cultural traditions of Uzbekistan that Soviet rule suppressed. Among the most important Central Asian contemporary artists.", "female","Uzbek"),
]

def make_entry(idx, raw):
    if len(raw)==12: t,a,y,m,mv,s,su,c,mu,d,h,g=raw; n="Unknown"
    else: t,a,y,m,mv,s,su,c,mu,d,h,g,n=raw[:13]
    p=period_from_year(y)
    tags=list(dict.fromkeys([x.lower() for x in s[:4]]+[x.lower() for x in su[:3]]+[mv.split("/")[0].strip().lower(),p.lower().split()[0]]))[:12]
    return {"id":idx,"title":t,"artist":a,"year":y,"medium":m,"movement":mv,"style":s,"subject":su,"color_palette":c if isinstance(c,list) else [c],"museum":mu,"description":d,"historical_significance":h,"artist_gender":g,"artist_nationality":n,"period":p,"tags":tags}

def main():
    with open(DATA_PATH) as f: existing=json.load(f)
    # Get existing titles to avoid duplicates
    existing_titles = {a['title'] for a in existing}
    start=max(a["id"] for a in existing)+1
    new=[]
    for i,r in enumerate(FINAL_200):
        try:
            entry = make_entry(start+len(new), r)
            if entry['title'] not in existing_titles:
                new.append(entry)
                existing_titles.add(entry['title'])
        except Exception as e: print(f"Skip {i}: {e}")
    merged=existing+new
    with open(DATA_PATH,"w",encoding="utf-8") as f: json.dump(merged,f,ensure_ascii=False,indent=2)
    print(f"Done. {len(existing)} + {len(new)} = {len(merged)} total.")

if __name__=="__main__": main()
