"""Batch 5: adds ~300 more to reach 1020+ total."""
import json
from pathlib import Path
DATA_PATH = Path("data/artworks.json")

def period_from_year(y):
    if y < 1400: return "Ancient / Medieval"
    elif y < 1500: return "Early Renaissance"
    elif y < 1600: return "High Renaissance / Mannerism"
    elif y < 1700: return "Baroque"
    elif y < 1800: return "Rococo / Neoclassicism"
    elif y < 1850: return "Romanticism"
    elif y < 1900: return "Realism / Impressionism"
    elif y < 1945: return "Modernism"
    elif y < 1980: return "Post-War / Contemporary"
    else: return "Contemporary"

B5 = [
    ("Watteau: Pilgrimage to the Isle of Cythera", "Jean-Antoine Watteau", 1717, "Oil on canvas", "Rococo / French", ["rococo","pastoral","dreamy","figures","couples"], ["couples","departing","island of love","melancholic","dream"], ["soft green","gold","soft blue","atmospheric pastel"], "Louvre Museum, Paris", "Elegant couples depart (or arrive) from the island of love — the ambiguous direction creates a melancholic dream.", "Watteau invented the 'fête galante' genre. The Académie created a new category just to accept this painting.", "male", "French"),
    ("Watteau: Gilles (Pierrot)", "Jean-Antoine Watteau", 1718, "Oil on canvas", "Rococo / French", ["rococo","melancholic","clown","solitary","theatrical"], ["Pierrot figure","white costume","melancholy","troupe","isolated"], ["white","soft green","cream","melancholy"], "Louvre Museum, Paris", "The clown Gilles stands alone in white, his troupe below him, his gaze empty and melancholic.", "The greatest painted image of the lonely clown. Watteau died of tuberculosis aged 36, and this late work breathes his own isolation.", "male", "French"),
    ("Boucher: Diana After the Bath", "François Boucher", 1742, "Oil on canvas", "Rococo / French", ["rococo","mythological","sensuous","pastoral","decorative"], ["Diana","bath","companion","dogs","pastoral"], ["cream flesh","soft blue","warm gold","roses"], "Louvre Museum, Paris", "Diana and her companion rest after bathing in a softly sensuous rococo pastoral setting.", "Boucher was Madame de Pompadour's favorite painter. His soft erotic mythologies define the Rococo taste of Louis XV's court.", "male", "French"),
    ("Greuze: The Broken Pitcher", "Jean-Baptiste Greuze", 1771, "Oil on canvas", "French Sentimental Realism", ["sentimental","moralizing","female portrait","flower","broken"], ["young woman","broken pitcher","flowers","symbolic","innocent guilt"], ["warm cream","soft flowers","gentle light"], "Louvre Museum, Paris", "A young girl holds a broken pitcher with flowers — the broken vessel symbolizing lost innocence.", "Greuze's sentimental moral paintings were beloved by Diderot. The sexual symbolism is obvious but was officially politely ignored.", "male", "French"),
    ("Vigée-Lebrun: Marie Antoinette with Her Children", "Élisabeth Vigée Le Brun", 1787, "Oil on canvas", "Neoclassicism / French", ["royal portrait","maternal","political","detailed","official"], ["Marie Antoinette","children","cradle","official portrait","maternal"], ["red velvet","gold","white dress","children"], "Versailles Palace", "Marie Antoinette sits with her three surviving children — a political image of maternal legitimacy before the Revolution.", "Vigée Le Brun painted this to counter the 'Madame Deficit' image. An empty cradle visible (for a recently deceased child) makes it haunting.", "female", "French"),
    ("David: Madame Récamier", "Jacques-Louis David", 1800, "Oil on canvas", "Neoclassicism / French", ["neoclassical","austere","portrait","reclining","white"], ["Juliette Récamier","reclining","white dress","chaise longue","Greek style"], ["white","cream","grey","austere"], "Louvre Museum, Paris", "Juliette Récamier reclines on a Grecian chaise longue in a white Empire-style dress — austerely beautiful.", "David left the painting unfinished (you can see the missing chair feet). Récamier refused to let Gérard finish it.", "male", "French"),
    ("Ingres: The Valpinçon Bather", "Jean-Auguste-Dominique Ingres", 1808, "Oil on canvas", "Neoclassicism / French", ["nude","back view","linear","sensuous","classical"], ["bather","back view","white sheet","turban","intimate"], ["cream white sheet","pale flesh","soft turban"], "Louvre Museum, Paris", "A nude woman sits on the edge of a bath with her back to the viewer, wearing only a turban.", "Ingres painted back-turned nudes throughout his career. The pure outline and sensuous back are characteristic of his non-classical Classicism.", "male", "French"),
    ("Delacroix: Women of Algiers in Their Apartment", "Eugène Delacroix", 1834, "Oil on canvas", "Romanticism / French", ["romantic","orientalist","luminous","colorful","interior"], ["Algerian women","harem","reclining","hookah","interior light"], ["rich color","warm light","jewel tones","soft shadow"], "Louvre Museum, Paris", "Three Algerian women in a colorful interior — seen after Delacroix was permitted into a women's apartment in Algiers.", "Delacroix was the first European painter to gain access to a private Algerian home. The luminous interior and unusual directness of the women influenced Renoir and Cézanne.", "male", "French"),
    ("Courbet: A Burial at Ornans", "Gustave Courbet", 1849, "Oil on canvas", "Realism / French", ["monumental","social","dark","realistic","rural"], ["village funeral","procession","open grave","clergy","provincial"], ["dark","black mourning dress","grey earth","provincial"], "Musée d'Orsay, Paris", "A small-town provincial burial with 50 life-size figures — clergy, mourners, townspeople — around an open grave.", "Painted life-size — but of ordinary village people, not heroic figures. The Paris art world was scandalized by this 'elevation' of the provincial common people.", "male", "French"),
    ("Manet: Bar at the Folies-Bergère", "Édouard Manet", 1882, "Oil on canvas", "Realism / Modernism", ["modernist","reflection","barmaid","urban","complex"], ["barmaid","bar","mirror","reflection","Folies-Bergère"], ["vivid fruit colors","mirror reflection","black costume","marble bar"], "Courtauld Gallery, London", "A barmaid stands at a marble bar; her reflection in the mirror behind shows her talking to a customer we cannot see.", "Manet's last great painting. The mirror is spatially 'wrong' — creating a philosophical puzzle about observation and reality. His farewell to painting.", "male", "French"),
    ("Redon: The Smiling Spider", "Odilon Redon", 1887, "Charcoal", "Symbolism / French", ["symbolist","grotesque","charcoal","monstrous","dreamlike"], ["spider","eyes","grotesque smile","dark","nightmare"], ["charcoal black","white eyes","paper"], "Louvre Museum, Paris", "A giant spider with a humanoid face smiles horribly in dense charcoal.", "Redon's early charcoal 'Noirs' created a symbolic world of nightmare hybrids. The Smiling Spider became his most recognized image of irrational dread.", "male", "French"),
    ("Serusier: The Talisman", "Paul Sérusier", 1888, "Oil on cigar box lid", "Post-Impressionism / Synthetism", ["synthetist","bold color","small","founding work","flat"], ["landscape","flat color","Gauguin lesson","bold","bright"], ["vivid yellow","green","purple","flat bold color"], "Musée d'Orsay, Paris", "A tiny Breton landscape painted under Gauguin's instruction to use pure unmixed color directly — a founding work of Synthetism.", "Sérusier brought this tiny painting back to Paris where it became 'The Talisman' — the starting point of the Nabi movement.", "male", "French"),
    ("Denis: April (Nabi group)", "Maurice Denis", 1892, "Oil on canvas", "Symbolism / Nabi", ["nabi","decorative","spring","female figures","symbolic"], ["women in procession","spring flowers","symbolic","flat","decorative"], ["pale green","white","soft spring colors"], "Pushkin Museum, Moscow", "Women in white move through a spring landscape in a decorative, rhythmic composition.", "Denis was the theorist of the Nabi movement: 'A painting is essentially a flat surface covered with colors assembled in a certain order.'", "male", "French"),
    ("Bonnard: Woman with Dog", "Pierre Bonnard", 1922, "Oil on canvas", "Post-Impressionism / French", ["colorful","domestic","intimate","pattern","woman"], ["woman","dog","interior","pattern","colorful"], ["warm yellow","domestic color","patterned cloth"], "Fondation Bemberg, Toulouse", "A woman with a small dog in a colorful domestic interior — Bonnard's characteristic flattening of figure and pattern.", "Bonnard's domestic interiors transform household scenes into color fields — the woman as patterned as the wallpaper.", "male", "French"),
    ("Vuillard: The Dressmakers", "Édouard Vuillard", 1892, "Oil on canvas", "Post-Impressionism / Intimisme", ["intimate","pattern","domestic","labor","absorbed"], ["dressmakers","interior","pattern","absorbed labor","domestic"], ["red","patterned","warm domestic"], "Phillips Collection, Washington D.C.", "Women sewing in an interior absorbed into the patterned wallpaper and fabric that surrounds them.", "Vuillard's mother was a seamstress. These sewing-room paintings merge labor and decoration — the women as part of the domestic fabric.", "male", "French"),
    ("Signac: Papal Palace, Avignon", "Paul Signac", 1900, "Watercolor", "Pointillism / French", ["pointillist","watercolor","luminous","architectural","river"], ["Papal Palace","Rhône","boats","luminous","summer"], ["vivid blue","gold","orange sunlight","pointillist"], "Musée d'Orsay, Paris", "The Papal Palace at Avignon reflected in the Rhône in a luminous watercolor of pure pointillist color.", "Signac was Seurat's greatest champion. His watercolors of Mediterranean and Rhône towns are among the most luminous works of Post-Impressionism.", "male", "French"),
    ("Cross: The Evening Air", "Henri Edmond Cross", 1894, "Oil on canvas", "Pointillism / French", ["pointillist","Mediterranean","evening","figures","light"], ["women by sea","evening light","Mediterranean","soft colors","relaxed"], ["lavender","gold","soft evening","Mediterranean"], "Musée d'Orsay, Paris", "Women rest by the Mediterranean in evening light — the mosaic of color creating a warm, dreamlike atmosphere.", "Cross was the third great Pointillist. His Mediterranean subjects pushed Seurat's method toward decorative symbolism.", "male", "French"),
    ("Toulouse-Lautrec: Jane Avril Dancing", "Henri de Toulouse-Lautrec", 1892, "Oil on cardboard", "Post-Impressionism / French", ["post-impressionist","dance","figure","candid","observational"], ["Jane Avril","dancing","Moulin Rouge","alone","distinctive"], ["dark","cream skin","black stocking","observation"], "Musée d'Orsay, Paris", "Jane Avril dances alone at the Moulin Rouge with her characteristic independent, interior style.", "Lautrec was fascinated by Avril's self-contained dancing — different from the collective cancan. His several portraits of her are among his finest.", "male", "French"),
    ("Bonnard: The Breakfast Table", "Pierre Bonnard", 1936, "Oil on canvas", "Post-Impressionism / French", ["colorful","interior","morning","pattern","domestic"], ["breakfast","window light","fruit","domestic pattern","morning"], ["yellow gold","warm light","window color","fruit"], "Museum of Modern Art, MoMA", "A breakfast table in morning light with pattern on cloth, fruit, and window view in Bonnard's characteristically warm colorism.", "Bonnard's breakfast paintings isolate a moment of domestic pleasure in saturated color. He painted from memory and emotion rather than direct observation.", "male", "French"),
    ("Morandi: Still Life with Bottles", "Giorgio Morandi", 1946, "Oil on canvas", "Metaphysical / Italian", ["still life","quiet","muted","bottles","meditative"], ["bottles","jars","dust","silence","simple"], ["cream","grey","muted ochre","dust"], "Pinacoteca di Brera, Milan", "Bottles and jars grouped in quiet communion — Morandi's endlessly repeated subject of dusty objects.", "Morandi painted almost nothing but bottles and jars his entire life. His muted palette and meditative silences influenced artists worldwide.", "male", "Italian"),
    ("Morandi: Still Life with White Objects", "Giorgio Morandi", 1949, "Oil on canvas", "Metaphysical / Italian", ["still life","white","pale","architectural","meditative"], ["white bottles","pale forms","grouped objects","silence"], ["pale cream","grey white","dust","architectural"], "Museo Morandi, Bologna", "White bottles and containers cluster in near-uniform pallor — almost architectural forms.", "Morandi's white-on-white still lifes are his most extreme reduction. The objects seem to dissolve into pure atmosphere.", "male", "Italian"),
    ("Hopper: Cape Cod Evening", "Edward Hopper", 1939, "Oil on canvas", "American Realism", ["realist","solitary","evening","couple","alienation"], ["couple","dog","house","woods","estrangement"], ["dark green trees","warm house light","evening shadow"], "National Gallery of Art, Washington D.C.", "A couple on their porch look in opposite directions — the pine woods loom behind them in dark evening shadow.", "The estrangement between the couple — each looking away — and the encroaching dark woods capture American suburban isolation.", "male", "American"),
    ("Hopper: Morning Sun", "Edward Hopper", 1952, "Oil on canvas", "American Realism", ["realist","interior","solitary","light","woman"], ["woman in sun","window light","bed","morning","solitary"], ["vivid morning light","cream","warm shadows","solitary"], "Columbus Museum of Art", "A woman sits on a bed in morning sun streaming from a window — alone with the light in an empty urban space.", "One of Hopper's most meditative interiors. The woman is rapt in sun but isolated — communion with light as substitute for human connection.", "male", "American"),
    ("Hopper: Gas", "Edward Hopper", 1940, "Oil on canvas", "American Realism", ["realist","evening","solitary","highway","american"], ["gas station","attendant","evening","road","woods"], ["warm evening light","dark woods","solitary figure"], "Museum of Modern Art, MoMA", "A lone gas station attendant works at dusk as the forest darkens on either side of the road.", "The deserted highway, single worker, and encroaching dark create Hopper's most existentially American image.", "male", "American"),
    ("Wyeth: Wind from the Sea", "Andrew Wyeth", 1947, "Tempera on hardboard", "American Realism", ["realist","window","curtain","light","atmospheric"], ["lace curtain","window","fields","sea breeze","nostalgic"], ["cream curtain","pale field","blue sky","light wind"], "National Gallery of Art, Washington D.C.", "A white lace curtain billows in a sea breeze through an open window, the fields and sky beyond.", "Wyeth's most poetic window painting. The wind-moved curtain is both presence and absence — the painting breathes.", "male", "American"),
    ("O'Keeffe: Radiator Building — Night, New York", "Georgia O'Keeffe", 1927, "Oil on canvas", "American Modernism", ["modernist","nocturnal","urban","art deco","architectural"], ["radiator building","night","windows","red sign","art deco"], ["dark blue night","orange windows","red","art deco geometry"], "Fisk University, Nashville", "The Radiator Building at night with Alfred Stieglitz's name in red light — O'Keeffe's most urban and romantic painting.", "O'Keeffe rarely painted urban subjects. This night painting of the Radiator Building, with Stieglitz's name in the sign, is her most personal New York work.", "female", "American"),
    ("O'Keeffe: Pelvis with Moon", "Georgia O'Keeffe", 1943, "Oil on canvas", "American Modernism", ["desert","bones","sky","abstract","minimal"], ["pelvis bone","moon","sky","blue","framed sky"], ["blue sky","cream bone","white moon"], "Norton Simon Museum, Pasadena", "A large animal pelvis frames a blue sky with a white full moon visible through the bone's opening.", "O'Keeffe began framing sky through bones — a meditation on infinity seen through mortality.", "female", "American"),
    ("Diebenkorn: Ocean Park #79", "Richard Diebenkorn", 1975, "Oil on canvas", "Abstract Expressionism / California", ["abstract","geometric","coastal light","layered","atmospheric"], ["color field","light","geometric","California coast","layered"], ["pale blue","cream","grey","light geometric"], "Museum of Fine Arts, Boston", "Geometric color divisions in pale blue, cream, and grey create a layered atmospheric landscape.", "Diebenkorn's Ocean Park series translated the light and geometry of Santa Monica into abstract paintings of rare beauty.", "male", "American"),
    ("Wayne Thiebaud: Bakery Counter", "Wayne Thiebaud", 1962, "Oil on canvas", "Pop Art / California", ["pop art","food","cake","colorful","thick paint"], ["cakes","pies","bakery counter","thick impasto","cheerful"], ["vivid pastel","cream","strawberry red","shadow blue"], "Various collections", "A bakery display case with pies and cakes rendered in thick, luscious impasto that makes the paint itself edible-looking.", "Thiebaud's food paintings were contemporaneous with Pop Art but more sensuous — the thick paint imitates the icing it depicts.", "male", "American"),
    ("Avery: March in the Country", "Milton Avery", 1945, "Oil on canvas", "American Modernism", ["flat color","landscape","simplified","lyrical","american"], ["rolling hills","figures","spring","flat color","simplified"], ["soft ochre","blue","cream","simplified landscape"], "Phillips Collection, Washington D.C.", "Rolling hills and simplified figures in flat, lyrical color fields.", "Avery's simplified flatness was enormously important to Rothko and Gottlieb. He shows that American modernism could be gentle and joyful.", "male", "American"),
    ("De Kooning: Excavation", "Willem de Kooning", 1950, "Oil and enamel on canvas", "Abstract Expressionism / American", ["gestural","complex","dense","figures","abstract"], ["dense paint","figure fragments","excavation","all over","gestural"], ["cream","grey","black outline fragments","flesh tone"], "Art Institute of Chicago", "A dense, complex surface of interlocking forms — figure fragments suggested and denied simultaneously.", "One of the pivotal paintings of Abstract Expressionism. The title suggests archaeology — forms dug up from the unconscious.", "male", "Dutch-American"),
    ("Mitchell: La Grande Vallée XIV", "Joan Mitchell", 1983, "Oil on canvas", "Abstract Expressionism / American", ["gestural","color field","nature","lyrical","French"], ["landscape abstraction","color brushwork","nature","gestural","lyrical"], ["vivid blue","green","yellow","gestural"], "Museum of Modern Art, MoMA", "A large diptych of gestural marks in blue, green, and yellow suggesting landscape and light.", "Mitchell spent her later years in Vétheuil, near Monet's home. Her abstractions always invoke landscape — weather, light, and plant life.", "female", "American"),
    ("Krasner: White Squares", "Lee Krasner", 1955, "Oil on canvas", "Abstract Expressionism / American", ["abstract","collage","mosaic","gestural","white"], ["white mosaic","irregular fragments","gestural marks","collage","structure"], ["white","cream","soft grey fragments"], "Various collections", "A canvas of irregular white mosaic-like fragments — built from torn pieces of her own earlier paintings.", "Krasner's destruction and reconstruction of her own work was a creative strategy unmatched in AbEx. The White Squares series is her finest hour.", "female", "American"),
    ("Twombly: Untitled (New York City)", "Cy Twombly", 1953, "House paint, oil, pencil on canvas", "Abstract Expressionism / American", ["gestural","scrawl","nocturnal","grey","primal"], ["grey ground","scrawl marks","nocturnal","primal script"], ["grey house paint","white pencil scrawl","dark"], "Various collections", "Dark grey paint covered in looping pencil scrawls — Twombly's earliest complete statement.", "Made when Twombly could not afford light, these grey paintings were made by touch in the dark. They look like ancient scripts from an unknown civilization.", "male", "American"),
    ("Johns: Numbers in Color", "Jasper Johns", 1959, "Encaustic and newspaper on canvas", "Neo-Dada / American", ["encaustic","numbers","pop","newspaper","color"], ["numbers 0-9","color","newspaper collage","encaustic texture"], ["vivid color","newspaper grey","encaustic texture"], "Albright-Knox Art Gallery, Buffalo", "The numbers 0 through 9 repeated in rows of different color combinations in Johns's characteristic encaustic medium.", "Johns's number and alphabet paintings treat familiar forms as objects to be examined — is it a number or a painting of a number?", "male", "American"),
    ("Noland: Half", "Kenneth Noland", 1959, "Acrylic on canvas", "Color Field / American", ["color field","target","concentric circles","flat","direct"], ["target painting","concentric circles","flat color","centered","direct"], ["red","gold","grey","concentric circles"], "Various collections", "Concentric circles of color on an unprimed canvas — flat, direct, centered.", "Noland's target paintings emerged directly from Frankenthaler's staining technique. The centered circles eliminate all compositional choice.", "male", "American"),
    ("Louis: Alpha Pi", "Morris Louis", 1961, "Acrylic on canvas", "Color Field / American", ["color field","stripe","poured","color","minimal"], ["diagonal stripes","poured color","raw canvas","vivid","parallel"], ["vivid color stripes","raw canvas","parallel bands"], "Metropolitan Museum of Art, New York", "Diagonal stripes of poured acrylic in vivid colors on unprimed raw canvas.", "Louis poured paint directly on tilted unprimed canvas — the color is the canvas surface itself, not applied paint. Radically different from gestural painting.", "male", "American"),
    ("Stella: Gran Cairo", "Frank Stella", 1962, "Alkyd on canvas", "Minimalism / Hard-Edge", ["minimal","hard edge","geometric","stripe","shaped canvas"], ["concentric triangles","geometric precision","flat","stripe","hard edge"], ["vivid color triangles","hard edge geometric"], "Whitney Museum, New York", "Concentric triangles in flat vivid color — the composition determined entirely by the canvas's square shape.", "Stella's 'Protractor' and early shaped-canvas works reduced painting to its own internal logic. His maxim: 'What you see is what you see.'", "male", "American"),
    ("Albers: Homage to the Square: Saturated", "Josef Albers", 1952, "Oil on masonite", "Bauhaus / American", ["minimal","color theory","square","optical","systematic"], ["three nested squares","color interaction","systematic","optical"], ["orange","red","warm systematic squares"], "Various collections", "Three nested squares of warm color demonstrate how colors change their appearance relative to each other.", "Albers spent 26 years systematically exploring how color changes perceptually in relation to its surrounding color. The entire Homage to the Square series is a single scientific-artistic project.", "male", "German-American"),
    ("Reinhardt: Abstract Painting No. 5", "Ad Reinhardt", 1952, "Oil on canvas", "Abstract Expressionism / American", ["abstract","near black","systematic","meditative","austere"], ["dark color fields","grid","near-black","systematic"], ["deep red","dark blue","near black","grid"], "Various collections", "A grid of dark color fields barely distinguishable from each other at first glance.", "Reinhardt's reduction toward pure dark, toward 'the last painting' — this transitional work shows him moving from dark color to near-black.", "male", "American"),
    ("Guston: Transition (1958)", "Philip Guston", 1958, "Oil on canvas", "Abstract Expressionism / American", ["abstract","pink","gestural","atmospheric","transitional"], ["pink ground","dark gestural marks","atmospheric","hovering"], ["pink","dark marks","atmospheric grey"], "Museum of Modern Art, MoMA", "Dark gestural marks cluster and hover in a pink atmospheric ground — Guston in transition from pure abstraction.", "This 'transition' painting shows Guston moving from pure gestural abstraction back toward figuration. The clustering marks already suggest heads and objects.", "male", "American"),
    ("de Kooning: Door to the River", "Willem de Kooning", 1960, "Oil on canvas", "Abstract Expressionism / American", ["gestural","yellow","abstract","aggressive","landscape"], ["yellow abstract","landscape suggestion","door","gestural marks"], ["vivid yellow","white","gestural","landscape traces"], "Whitney Museum, New York", "A canvas of yellow and white gestural marks that suggest a landscape—a door, a river—through pure paint energy.", "De Kooning's transition from Woman paintings to landscape abstraction. The yellow is unprecedented in his palette.", "male", "Dutch-American"),
    ("Rothko: Orange and Yellow", "Mark Rothko", 1956, "Oil on canvas", "Color Field / American", ["color field","meditative","luminous","large scale","spiritual"], ["orange rectangle","yellow rectangle","soft edges","luminous","large scale"], ["vivid orange","yellow","luminous warm"], "Albright-Knox Art Gallery, Buffalo", "Two rectangles — orange above yellow — their edges dissolving in mutual luminosity.", "Rothko considered his paintings not about color or form but about 'the basic human emotions — tragedy, ecstasy, doom'.", "male", "Russian-American"),
    ("Newman: Cathedra", "Barnett Newman", 1951, "Oil on canvas", "Color Field / American", ["color field","blue","sublime","spiritual","monumental"], ["deep blue","two zips","vast horizontal","sublime"], ["deep blue","white zip","blue grey zip"], "Stedelijk Museum, Amsterdam", "A vast horizontal canvas of deep blue with two vertical zips — a field of transcendent blue.", "Newman's blue canvases invoke the sky, the sea, and the sacred. He gave them titles like 'Cathedra' to indicate their spiritual ambition.", "male", "American"),
    ("Frankethaler: Cool Summer", "Helen Frankenthaler", 1962, "Oil on canvas", "Color Field / American", ["color field","stained","lyrical","abstract","cool"], ["cool color wash","stained","lyrical abstract","subtle"], ["pale blue","grey","white","cool stained"], "Corcoran Gallery (now National Gallery), Washington D.C.", "Cool blues and greys stained into unprimed canvas in a lyrical, atmospheric abstraction.", "Frankenthaler's cool palette paintings are as important as her better-known Mountains and Sea. The staining method creates landscapes without depicting them.", "female", "American"),
    # PHOTGRAPHY
    ("Adams: Half Dome, Merced River, Winter", "Ansel Adams", 1938, "Gelatin silver print", "Photography / American", ["landscape","monumental","dramatic","black and white","winter"], ["Half Dome","Merced River","winter","snow","dramatic sky"], ["black and white","dramatic contrast"], "Various collections", "Half Dome reflected in the Merced River in winter with dramatic sky.", "Adams used his Zone System to achieve maximum tonal range from shadow to highlight. His Yosemite photographs define the American sublime.", "male", "American"),
    ("Arbus: Child with Toy Hand Grenade, NYC", "Diane Arbus", 1962, "Gelatin silver print", "Photography / American", ["direct gaze","street photography","child","tension","disturbing"], ["boy","toy grenade","grimace","Central Park","tension"], ["black and white","grey","direct gaze"], "Various collections", "A boy holds a toy hand grenade with a contorted, grimacing expression while standing in Central Park.", "One of the most famous street photographs. The boy's grotesque expression against the toy weapon creates an image of childhood aggression and violence.", "female", "American"),
    ("Evans: Allie Mae Burroughs", "Walker Evans", 1936, "Gelatin silver print", "Documentary Photography / American", ["documentary","portrait","Great Depression","dignity","direct"], ["tenant farmer wife","direct gaze","wooden wall","dignity"], ["black and white","wooden planks","direct"], "Library of Congress, Washington D.C.", "A sharecropper's wife looks directly at the camera with composed, wary dignity.", "Evans's Farm Security Administration portraits define American documentary photography. Allie Mae Burroughs's face is one of the most analyzed in photography.", "male", "American"),
    ("Bourke-White: Fort Peck Dam", "Margaret Bourke-White", 1936, "Gelatin silver print (LIFE cover)", "Photography / American", ["documentary","industrial","monumental","american","dam"], ["Fort Peck Dam","construction workers","monumental","workers","dam"], ["black and white","monumental scale","workers tiny"], "Various collections", "Workers tiny against the monumental face of the Fort Peck Dam during construction.", "The first cover of LIFE Magazine (1936). Bourke-White defined the monumental American industrial documentary photograph.", "female", "American"),
    ("Abbott: Changing New York (Nightview)", "Berenice Abbott", 1938, "Gelatin silver print", "Photography / American", ["documentary","city at night","aerial","modernist","urban"], ["city lights","night aerial","geometric grid","urban","skyscrapers"], ["black","white city lights","geometric grid"], "Museum of the City of New York", "New York City at night from above — a grid of lights creating an abstract geometric carpet.", "Abbott documented New York's transformation with scientific precision and Modernist vision. Her aerial city-at-night photographs anticipate satellite imagery.", "female", "American"),
    ("Weston: Pepper No. 30", "Edward Weston", 1930, "Gelatin silver print", "Photography / American", ["still life","abstract","organic","close-up","sensuous"], ["green pepper","abstract form","organic","close-up","sensuous"], ["warm grey","dark velvet","organic form"], "Various collections", "A single green pepper in close-up — its form simultaneously vegetable and human in its organic abstraction.", "Weston's pepper took five days of attempts with a large-format camera. The result is simultaneously a pepper and a nude and a sculpture.", "male", "American"),
    ("Man Ray: Tears", "Man Ray", 1930, "Gelatin silver print", "Surrealism / Photography", ["surrealist","photograph","glass tears","female","staged"], ["close-up eye","glass tears","artifice","surrealist","female"], ["black and white","glass teardrops","dramatic"], "Museum of Modern Art, MoMA", "Glass teardrops on a close-up female eye — artificial tears in a staged surrealist photograph.", "Man Ray's staged photographs are Surrealist objects. The glass tears make artificial what should be natural — a meditation on performance and feeling.", "male", "American"),
    ("Eisenstaedt: V-J Day in Times Square", "Alfred Eisenstaedt", 1945, "Gelatin silver print", "Documentary Photography / American", ["documentary","celebration","VJ Day","iconic","street"], ["sailor kissing nurse","Times Square","VJ Day","spontaneous","iconic"], ["black and white","Times Square","celebration"], "Various collections", "A sailor kisses a nurse in Times Square on V-J Day — the spontaneous celebration of the end of World War II.", "The most reproduced photograph of World War II's end. Four different photographs were taken that day; Eisenstaedt's is definitive.", "male", "American"),
    ("Doisneau: The Kiss at the Hotel de Ville", "Robert Doisneau", 1950, "Gelatin silver print", "Documentary Photography / French", ["documentary","romance","paris","street","staged"], ["couple kissing","Paris café","street","passers-by","love"], ["black and white","Paris grey","romantic"], "Various collections", "A couple kisses in front of a Paris café while the street life flows around them indifferently.", "Doisneau's most famous image. Later revealed to be staged — the couple were actors. The staging controversy created a different kind of image.", "male", "French"),
    # CONCEPTUAL
    ("Duchamp: Bicycle Wheel", "Marcel Duchamp", 1913, "Bicycle wheel on stool (replica)", "Dada / Readymade", ["readymade","first readymade","conceptual","wheel","rotation"], ["bicycle wheel","stool","rotation","first readymade","concept"], ["chrome wheel","wooden stool"], "Museum of Modern Art, MoMA", "A bicycle wheel mounted upside-down on a white kitchen stool.", "Duchamp's first readymade — chosen for visual pleasure (the spinning wheel) rather than meaning. The concept of the readymade would change art forever.", "male", "French"),
    ("Duchamp: In Advance of the Broken Arm", "Marcel Duchamp", 1915, "Snow shovel (replica)", "Dada / Readymade", ["readymade","snow shovel","conceptual","anti-art","concept"], ["snow shovel","hardware store","signed","readymade","titled"], ["galvanized steel grey","wooden handle"], "Yale University Art Gallery", "A standard hardware-store snow shovel, purchased unmodified, titled and signed as artwork.", "The first American readymade. Duchamp's question: if an artist designates an object as art, does the object become art? Still unanswered.", "male", "French"),
    ("Warhol: Brillo Box", "Andy Warhol", 1964, "Silkscreen on plywood", "Pop Art / American", ["pop art","brand","consumer culture","product","serial"], ["Brillo soap pad box","silkscreen","stacked","consumer brand"], ["red","blue","white","consumer brand colors"], "Various museums", "Wooden boxes painted and silkscreened to replicate Brillo soap pad packaging exactly.", "Arthur Danto asked: if the Brillo Box looks identical to what's in the supermarket, what makes the art world's version Art? His answer launched 'institutional theory'.", "male", "American"),
    ("Warhol: Disaster Series (Electric Chair)", "Andy Warhol", 1963, "Acrylic and silkscreen on canvas", "Pop Art / American", ["pop art","death","repetition","electric chair","dark"], ["electric chair","empty room","silkscreen","repetition","death"], ["grey","dark purple","muted","death"], "Museum of Modern Art, MoMA", "A photograph of an empty electric chair, silkscreened in grey on a near-monochrome canvas.", "Warhol's 'Death and Disaster' series addresses the mass media's numbing effect on images of death. The empty chair is more disturbing than an occupied one.", "male", "American"),
    ("Warhol: Mao", "Andy Warhol", 1972, "Acrylic and silkscreen on canvas", "Pop Art / American", ["pop art","political","silkscreen","celebrity","colorful"], ["Mao Zedong","silkscreen portrait","colorful warhol treatment","political icon"], ["vivid pop colors","silkscreened face"], "Art Institute of Chicago", "The official portrait of Mao Zedong treated with Warhol's silkscreen and vivid pop colors.", "Warhol made Mao portraits immediately after Nixon's visit to China in 1972. The treatment elevates/deflates political authority into celebrity.", "male", "American"),
    ("Beuys: I Like America and America Likes Me", "Joseph Beuys", 1974, "Performance (photograph documentation)", "Conceptual Art / German", ["performance","political","coyote","duration","healing"], ["Beuys","wild coyote","felt blanket","staff","isolation"], ["grey felt","brown coyote","documentation photo"], "René Block Gallery, New York", "Beuys spent three days in a gallery room with a wild coyote — his felt-wrapped staff the only mediating object.", "A healing ritual addressing America's treatment of indigenous peoples. The coyote is a sacred figure to Native Americans. Beuys arrived and departed without touching American ground.", "male", "German"),
    ("Beuys: The Pack (Das Rudel)", "Joseph Beuys", 1969, "Volkswagen van, 24 sledges with felt, fat, flashlights", "Conceptual Art / German", ["installation","felt","fat","survival kit","political"], ["VW van","sledges","felt","fat","survival","emergency"], ["grey felt brown","industrial grey"], "Neue Galerie, Kassel", "A Volkswagen van with 24 sledges pouring from its back doors, each equipped with felt, fat, and a flashlight — a survival kit.", "Beuys linked the materials to his own WWII survival story (he says he was wrapped in felt and fat by Tartar nomads after his plane crashed). The survival kit as political statement.", "male", "German"),
    ("Kiefer: The Rhine", "Anselm Kiefer", 1982, "Oil, acrylic, shellac, straw on canvas", "Neo-Expressionism / German", ["expressionist","landscape","historical","german","dark"], ["Rhine landscape","leaden sky","straw","desolation","Germany"], ["grey sky","dark earth","straw texture","dark"], "Centre Pompidou, Paris", "A leaden landscape with a dark river and a horizon weighted with the materiality of straw and paint.", "Kiefer's Rhine invokes the Romantic mythology of Germany — Caspar David Friedrich — but blackened with historical guilt.", "male", "German"),
    ("Baselitz: Dresdner Frauen (Dresden Women)", "Georg Baselitz", 1989, "Oil on canvas", "Neo-Expressionism / German", ["expressionist","inverted","female figures","historical","bold"], ["inverted women figures","Dresden","bold paint","upside down"], ["vivid color","inverted figures","raw paint"], "Various collections", "Monumental female figures painted upside-down in raw, expressionist color.", "Baselitz began inverting his figures in 1969 to separate form from content — the painting becomes about paint, not subject matter.", "male", "German"),
    ("Lüpertz: Germania", "Markus Lüpertz", 1970, "Distemper on canvas", "Neo-Expressionism / German", ["expressionist","german mythology","bold","symbolic","painting"], ["Germania allegory","German helmet","bold form","symbolic"], ["dark earth","grey","dramatic"], "Various collections", "A German military helmet motif as abstracted symbolic form.", "Lüpertz's Germania paintings confront German history through the recycled iconography of militarism — helmets as pure paint form.", "male", "German"),
    ("Immendorff: Café Deutschland", "Jörg Immendorff", 1977, "Oil on canvas", "Neo-Expressionism / German", ["expressionist","political","divided Germany","bar scene","allegorical"], ["café","east west germany","figures","political allegory","eagle"], ["dark","vivid color","figures dense","political"], "Städel Museum, Frankfurt", "An allegorical bar scene where East and West German figures meet/clash across a divided table.", "Immendorff's Café Deutschland series addressed the division of Germany through baroque political allegory. A unique fusion of art history and political commentary.", "male", "German"),
    ("Richter: Ema (Nude on a Staircase)", "Gerhard Richter", 1966, "Oil on canvas", "Photorealism / German", ["photorealist","blurred","nude","staircase","duchamp reference"], ["nude woman descending staircase","blurred photograph","photorealism"], ["grey","flesh","blurred photo quality"], "Museum Ludwig, Cologne", "A nude woman descends a staircase in a blurred photographic style — a homage to Duchamp.", "Richter's most direct reference to art history. The blurring transforms a domestic photograph into an investigation of seeing and representation.", "male", "German"),
    # EAST ASIAN EXPANDED
    ("Ni Zan: The Rongxi Studio", "Ni Zan", 1372, "Ink on paper scroll", "Yuan Dynasty / Chinese", ["literati","ink","spare","three zones","minimalist"], ["bamboo","empty pavilion","distant mountains","three zones","minimal"], ["pale ink wash","white paper","spare"], "National Palace Museum, Taipei", "Sparse rocks and bamboo, an empty pavilion, and distant mountains in three horizontal zones of pale ink.", "Ni Zan's radical emptiness — no figures, no activity, a conspicuously absent human world — became the summit of literati painting.", "male", "Chinese"),
    ("Wang Hui: Kang Xi Emperor's Southern Inspection Tour", "Wang Hui", 1698, "Color on silk scroll", "Qing Dynasty / Chinese", ["panoramic","imperial","detailed","historical","scroll"], ["Kangxi Emperor","procession","cities","rivers","panoramic tour"], ["rich color","narrative","blue green","imperial"], "Metropolitan Museum of Art, New York", "A section from the 12-scroll series documenting the Kangxi Emperor's 1689 southern tour — cities, rivers, processions.", "Wang Hui coordinated a team of painters for this 12-scroll imperial commission — the most ambitious pictorial record of a Chinese imperial journey.", "male", "Chinese"),
    ("Qi Baishi: Shrimp", "Qi Baishi", 1940, "Ink on paper", "Republican Period / Chinese Modern", ["literati","ink","animals","loose","expressive"], ["shrimp","ink wash","loose brushwork","transparent","movement"], ["ink grey","transparent washes","white paper"], "Various collections", "Shrimp rendered in pure ink wash with extraordinary transparency and a sense of liquid movement.", "Qi Baishi is the best-loved Chinese painter of the 20th century. His shrimp achieved perfect balance between observation and expressive mark-making.", "male", "Chinese"),
    ("Ren Xiong: Self-Portrait", "Ren Xiong", 1850, "Ink and color on paper", "Qing Dynasty / Chinese", ["self-portrait","unusual","confrontational","late Qing","melancholic"], ["self-portrait","dramatic pose","exposed body","direct gaze"], ["ink blue","flesh","red","dramatic"], "Palace Museum, Beijing", "A dramatic self-portrait in which Ren Xiong confronts the viewer in a theatrical, melancholic pose.", "Unique in Chinese art history for its theatrical self-exposure and psychological directness. Very unusual in the context of Chinese portraiture.", "male", "Chinese"),
    ("Fu Baoshi: The Goddess of the Luo River", "Fu Baoshi", 1944, "Ink and color on paper", "Republican / Chinese Modern", ["ink wash","lyrical","mythological","atmospheric","figure"], ["water goddess","mist","river","mythology","atmospheric"], ["blue ink","mist","atmospheric","lyrical"], "Various collections", "The water goddess of the Luo River floats in atmospheric mist — lyrical fusion of classical poetry and modern ink technique.", "Fu Baoshi developed a unique ink-wash style that combined Tang dynasty poetry with modern expressive technique.", "male", "Chinese"),
    # SOUTH ASIAN EXPANDED
    ("Raja Ravi Varma: Shakuntala Looking for Bees", "Raja Ravi Varma", 1894, "Oil on canvas", "Indian Academic Realism", ["academic","mythological","indian","realistic","romantic"], ["Shakuntala","writing","bees","kalidasa","india"], ["green foliage","cream dress","warm skin","romantic"], "Sri Chitra Art Gallery, Thiruvananthapuram", "Shakuntala writes her love letter with a sharp nail, distracted by bees attracted to her flower garland — from Kalidasa's play.", "Ravi Varma was the first Indian artist to use oil paint in a European academic style. His mythological prints were distributed across India and defined popular Hindu iconography.", "male", "Indian"),
    ("Gaganendranath Tagore: Dwarf (Baul Singer)", "Gaganendranath Tagore", 1922, "Watercolor and gouache", "Bengali Renaissance / Indian", ["modernist","cubist influenced","bengali","social commentary","caricature"], ["baul singer","cubist distortion","bengali culture","social satire"], ["dark colors","cubist distortion","social commentary"], "Rabindra Bharati Society, Kolkata", "A Baul (wandering mystic singer) depicted with cubist distortion and social satire.", "Gaganendranath was the first Indian Cubist — absorbing Cubism from European magazines and applying it to Bengali folk culture and social commentary.", "male", "Indian"),
    ("Jamini Roy: The Three Maries", "Jamini Roy", 1940, "Casein on cardboard", "Indian Modernism / Bengal", ["flat color","bengali folk","bold outline","modern","simplified"], ["three women","folk art style","simplified","bold outline","Indian"], ["terracotta","cream","black bold outline","Indian ochre"], "Various collections", "Three women in a simplified, folk-art-influenced style with bold outlines and flat color.", "Roy rejected European academism and based his style on Kalighat pat painting — a Bengali folk tradition. His synthesis created a uniquely Indian modernism.", "male", "Indian"),
    ("Souza: Birth", "Francis Newton Souza", 1955, "Oil on board", "Indian Expressionism / PAG", ["expressionist","birth","raw","dark","powerful"], ["birth scene","mother","child","raw expressionism","dark"], ["dark earth","dramatic light","raw paint"], "National Gallery of Modern Art, New Delhi", "A raw expressionist birth scene — mother and child in dark, powerful brushwork.", "Souza co-founded the Progressive Artists' Group, which rejected Indian academic tradition. His work combines Francis Bacon's influence with Indian expressionist energy.", "male", "Indian"),
    # SOUTHEAST ASIAN
    ("Affandi: Self-Portrait", "Affandi", 1974, "Oil on canvas", "Indonesian Expressionism", ["expressionist","self-portrait","squeezed paint","raw","indonesian"], ["self-portrait","rough paint","direct squeeze technique","emotional","raw"], ["raw earth tones","thick squeezed paint","direct"], "Affandi Museum, Yogyakarta", "A raw self-portrait made by squeezing paint directly from the tube onto the canvas.", "Affandi developed his 'dripping and smearing' technique without formal training. He is Indonesia's most celebrated painter internationally.", "male", "Indonesian"),
    ("Heri Dono: Flying Angels", "Heri Dono", 1989, "Mixed media installation", "Contemporary Indonesian", ["installation","wayang","contemporary","political","satirical"], ["puppet-like angels","javanese","political satire","wayang","flying"], ["bright color","puppet material","satirical"], "Various museums", "Puppet-like angel figures combining Javanese wayang (shadow puppet) aesthetics with contemporary political satire.", "Dono synthesizes Javanese traditional arts with critical commentary on Indonesian politics. Indonesia's most internationally known contemporary artist.", "male", "Indonesian"),
    # AFRICAN EXPANDED
    ("Ghada Amer: Love Has No End", "Ghada Amer", 2002, "Embroidery and gel on canvas", "Contemporary Egyptian-American", ["embroidery","female figure","tangled threads","feminist","contemporary"], ["embroidered figures","dangling threads","intimacy","female sexuality"], ["tangled thread colors","oil gel","feminist"], "Various collections", "Embroidered female figures with threads hanging loose from the canvas — intimacy and labor combined.", "Amer's embroidered paintings combine a 'feminine' craft medium with erotic female imagery — reclaiming both from their conventional diminishment.", "female", "Egyptian-American"),
    ("Wael Shawky: Cabaret Crusades", "Wael Shawky", 2010, "Video installation (puppet theater)", "Contemporary Egyptian", ["video","puppet","crusades","history","theatrical"], ["marionettes","crusades","arab narrative","theater","historical revision"], ["theatrical color","puppet theater","dark"], "Various museums", "Historical puppet theater videos depicting the Crusades from an Arab perspective using marionette figures.", "Shawky rewrites the Crusades narrative from the Arab side — a fundamental challenge to Eurocentric art history using the theatrical puppet medium.", "male", "Egyptian"),
    ("Abdoulaye Konaté: Composition en Rouge et Noir", "Abdoulaye Konaté", 2010, "Textile", "Contemporary Malian", ["textile","abstract","political","large scale","West African"], ["red black textile","abstract","large scale","political","West African"], ["vivid red","black","gold thread","large textile"], "Various museums", "A monumental textile composition in red and black — Konaté's abstract political statement in traditional West African fabric.", "Konaté creates large-scale textile paintings that combine West African fabric traditions with contemporary abstract art. Among Africa's most internationally respected artists.", "male", "Malian"),
    ("Pascale Marthine Tayou: Plastic Bags", "Pascale Marthine Tayou", 2001, "Plastic bags, installation", "Contemporary Cameroonian", ["installation","plastic bags","global","waste","political"], ["colorful bags","column","global waste","market","color"], ["vivid plastic color","column of bags"], "Various museums", "A column of colorful plastic bags from markets around the world — a monument to global consumer waste.", "Tayou's plastic bag installations address globalization and waste by using the universal material of global markets.", "male", "Cameroonian"),
    # EUROPEAN CONTEMPORARY
    ("Gerhard Richter: Stag", "Gerhard Richter", 1963, "Oil on canvas", "Photorealism / German", ["photorealist","blurred","animal","forest","photograph"], ["stag in forest","blurred photograph","grey tones"], ["grey","blurred dark","photo texture"], "Museum Ludwig, Cologne", "A blurred photograph of a stag in a forest — one of Richter's earliest photo-paintings.", "Richter began painting from photographs to create 'objective' images without artistic intervention. This early work already shows his characteristic blur.", "male", "German"),
    ("Sigmar Polke: Supermarkets", "Sigmar Polke", 1976, "Synthetic polymer on fabric", "German Painting / Conceptual", ["halftone","consumer culture","pattern fabric","ironic","conceptual"], ["supermarket shelves","printed fabric","Ben-Day dots","consumer"], ["Ben-Day dots","printed fabric","consumer goods"], "Various collections", "Supermarket shelves rendered in halftone dots on a printed fabric support — consumer culture on consumer culture.", "Polke combines commercial printing techniques with found fabric to create layers of consumer imagery that critique each other.", "male", "German"),
    ("Dieter Roth: Daily Mirror", "Dieter Roth", 1961, "Cut newspaper pages", "Fluxus / Swiss", ["conceptual","cut newspaper","language","destruction","Fluxus"], ["cut holes","newspaper","destruction","text","language"], ["newsprint grey","cut holes","text"], "Various collections", "Daily Mirror newspaper pages with words and images systematically cut out — the negative presence of language.", "Roth's cut newspapers are simultaneously literary and visual — the absent words creating a new kind of presence.", "male", "German-Swiss"),
    ("Martin Kippenberger: Sorry not Sorry", "Martin Kippenberger", 1992, "Oil on canvas", "Neo-Expressionism / German", ["expressionist","ironic","self-portraiture","crude","humor"], ["self-portrait","sorry","text","crude paint","humor"], ["dark","cream","text","crude marks"], "Various collections", "A crude self-portrait with the word 'Sorry' — Kippenberger's characteristic combination of bad painting and dark humor.", "Kippenberger's cultivated failure was the most sustained artistic position of the 1980s German Neo-Expressionist scene.", "male", "German"),
    ("Neo Rauch: Aufmarsch (Parade)", "Neo Rauch", 2003, "Oil on canvas", "Contemporary Figurative / German", ["figurative","parade","dreamlike","DDR aesthetic","strange"], ["parade figures","socialist style","dreamlike","marching"], ["muted ochre","grey","socialist palette"], "Various collections", "Figures in a surreal parade in an indeterminate historical setting fusing East German socialism with nightmare.", "Rauch's parade paintings explore the collective ritual life of socialist culture through dreamwork and paint.", "male", "German"),
    # LATIN AMERICAN EXPANDED
    ("Carlos Cruz-Diez: Physichromie No. 500", "Carlos Cruz-Diez", 1969, "Mixed media", "Kinetic Art / Venezuelan", ["kinetic","color","movement","optical","latin american"], ["chromatic expansion","parallel strips","color change","viewer movement"], ["varied chromatic strips","optical color change"], "Various collections", "Parallel vertical strips of color that change as the viewer moves — creating color from movement rather than pigment.", "Cruz-Diez believed color exists only in the act of looking — it is neither in the object nor the eye but in the encounter between them.", "male", "Venezuelan"),
    ("Julio Le Parc: Lumière en Mouvement", "Julio Le Parc", 1965, "Motor, metal pieces, light", "Kinetic Art / Argentine", ["kinetic","light","motor","optical","movement"], ["reflected light","moving metal","environmental","optical"], ["reflected light patterns","mechanical movement"], "Various museums", "A motor-driven mobile of metal pieces that reflect and scatter light across the room.", "Le Parc is the grandfather of Argentine kinetic and light art. His work questions the traditional art object by making light and movement the medium.", "male", "Argentine"),
    ("Lygia Pape: Divisor", "Lygia Pape", 1968, "Fabric, community performance", "Neo-Concretism / Brazilian", ["performance","collective","fabric","participatory","community"], ["white sheet","collective heads through holes","community movement"], ["white fabric","multiple heads above"], "Various public spaces, Rio de Janeiro", "A large white fabric sheet with holes for many people's heads — a collective performance in public space.", "Pape's Divisor makes the individual body part of a collective organism. A fundamentally different model of art participation from European happenings.", "female", "Brazilian"),
    ("Nelson Leirner: Bandeja (Tray)", "Nelson Leirner", 1966, "Stuffed pig on tray", "Brazilian Neo-Dada / Conceptual", ["conceptual","institutional critique","pig","brazil","provocation"], ["stuffed pig","tray","institutional critique","provocation"], ["pink pig","silver tray"], "Pinacoteca do Estado, São Paulo", "A stuffed pig arranged on a silver serving tray — submitted to the official Salon and accepted.", "When the Salon jury accepted this work without noticing it was a provocation, Leirner leaked it to the press. The scandal launched Brazilian conceptualism.", "male", "Brazilian"),
    # ADDITIONAL SPECIFIC ASIAN
    ("Isamu Noguchi: Akari Light Sculpture", "Isamu Noguchi", 1951, "Washi paper and bamboo", "Japanese-American Modernism", ["sculpture","light","organic","japanese","washi"], ["paper lantern","light","organic form","shadow","washi"], ["warm paper white","bamboo structure","glowing"], "Various collections", "A washi paper lantern-sculpture with organic form and bamboo structure — light as both medium and subject.", "Noguchi designed over 200 Akari variations. They combine Japanese lantern tradition with Brancusi-influenced sculpture. Among the most democratic art objects ever made.", "male", "Japanese-American"),
    ("Lee Ufan: From Line", "Lee Ufan", 1977, "Oil on canvas", "Mono-ha / Korean-Japanese", ["minimal","line","presence","material","contemplative"], ["single brushstroke","fading line","canvas edge","presence","silence"], ["grey blue","white canvas","single mark"], "Guggenheim Bilbao", "A single brushstroke of grey-blue that begins at the canvas edge and fades to nothing before reaching the other.", "Lee Ufan's single marks carry the full weight of his philosophy: the mark is the event of meeting between hand, paint, and canvas.", "male", "Korean"),
    ("Yun Hyong-keun: Umber-Blue", "Yun Hyong-keun", 1975, "Oil on linen", "Korean Dansaekhwa", ["dansaekhwa","minimal","umber","absorption","Korean"], ["umber field","blue vertical","linen texture","absorbed","subtle"], ["deep umber brown","dark blue","linen texture"], "Various collections", "Deep umber and blue-black soaked into raw linen — color absorbed into the fabric of the support.", "Yun's paintings embody the Korean aesthetic of 'restraint and emptiness'. The colors literally become the canvas through soaking.", "male", "Korean"),
    ("Ha Chong-Hyun: Conjunction", "Ha Chong-Hyun", 1981, "Oil on hemp cloth", "Korean Dansaekhwa", ["dansaekhwa","material","back-painting","hemp","minimal"], ["oil pushed through hemp","textured surface","material process","minimal"], ["ochre","grey through hemp texture"], "National Museum of Modern and Contemporary Art, Seoul", "Oil paint pushed through the back of hemp cloth, the texture of the fabric becoming the mark of the brush.", "Ha Chong-Hyun's back-pushing technique — painting through the canvas rather than on it — creates a unique material-process relationship.", "male", "Korean"),
    ("Park Seo-Bo: Écriture No. 50-78", "Park Seo-Bo", 1978, "Oil and pencil on hanji", "Korean Dansaekhwa", ["dansaekhwa","grey","hanji","repetitive line","meditative"], ["grey ground","pencil lines","hanji","repetitive","meditative"], ["grey","pale cream","fine pencil lines","hanji texture"], "Various collections", "Repetitive pencil lines worked into grey oil paint on hanji (Korean paper) — a meditative process work.", "Park Seo-Bo drew lines into wet paint for hours — a meditative act. The Dansaekhwa artists brought Korean aesthetic values of emptiness into modernist painting.", "male", "Korean"),
    # ADDITIONAL EUROPEAN MODERN
    ("Mondrian: Tableau I", "Piet Mondrian", 1921, "Oil on canvas", "De Stijl / Dutch", ["de stijl","grid","primary colors","black lines","minimal"], ["grid","red rectangle","blue small","yellow small","black lines"], ["red","blue","yellow","black lines","white"], "Gemeentemuseum Den Haag", "A grid of black lines divides the canvas with one large red rectangle — the classic Mondrian composition.", "Mondrian's Tableau series established the format that defined De Stijl for the world. The asymmetric grid creates tension through pure geometric means.", "male", "Dutch"),
    ("Kupka: Amorpha, Fugue in Two Colors", "Frantisek Kupka", 1912, "Oil on canvas", "Orphism / Czech", ["abstract","circular motion","orphism","color","cosmic"], ["two interlocking circles","color abstraction","cosmic","fugue"], ["vivid red","dark blue","circular forms"], "National Gallery, Prague", "Two interlocking forms — one red, one dark — spiral in a cosmic fugue of pure color abstraction.", "Kupka independently arrived at pure abstraction simultaneously with Kandinsky. His musical-cosmological approach is unique in early abstraction.", "male", "Czech"),
    ("Léger: Three Women (Le Grand Déjeuner)", "Fernand Léger", 1921, "Oil on canvas", "Purism / Cubism", ["cubist","figurative","mechanical","monumental","classical"], ["three women","nude reclining","mechanical forms","classical","monumental"], ["grey","cream","classical architecture","mechanical flesh"], "Museum of Modern Art, MoMA", "Three large nude women in a precise, monumental arrangement — their bodies as smooth and mechanical as the objects around them.", "Léger's post-WWI classicism treats the female nude with the same formal dignity as a machine — neither more nor less. Pure form.", "male", "French"),
    ("Le Corbusier: Still Life (Purism)", "Le Corbusier (Charles-Édouard Jeanneret)", 1920, "Oil on canvas", "Purism / Swiss-French", ["purist","still life","geometric","bottles","precise"], ["bottles","glasses","table","geometric precision","purism"], ["cream","grey","precise geometric","table still life"], "Fondation Le Corbusier, Paris", "Bottles, glasses, and a pipe arranged with architectural precision on a table — the manifesto of Purist painting.", "Le Corbusier and Ozenfant codified Purism as a reaction to what they saw as Cubism's decorative excess. Painting as architecture of the visible world.", "male", "Swiss"),
    ("Chirico: The Soothsayer's Recompense", "Giorgio de Chirico", 1913, "Oil on canvas", "Metaphysical Art / Italian", ["metaphysical","silence","train","shadow","clock"], ["train","palm tree","classical arcade","shadow","afternoon silence"], ["warm ochre","long shadow","yellow sky","deserted"], "Philadelphia Museum of Art", "A steam train passes behind a classical arcade where a reclining figure lies — afternoon silence amplified by long shadows.", "De Chirico's metaphysical paintings made the familiar strange by silence, long shadows, and the juxtaposition of ancient and modern.", "male", "Italian-Greek"),
    ("Modigliani: Head (Tête)", "Amedeo Modigliani", 1911, "Limestone sculpture", "Modernism / Italian", ["sculpture","elongated","carved","serene","archaic"], ["elongated head","closed eyes","limestone","archaic","serene"], ["pale limestone","carved surface"], "Tate Modern, London", "An elongated limestone head with closed eyes and a simplified oval form — the carved equivalent of his painted faces.", "Modigliani carved these heads under Brancusi's influence. He wanted to create a 'temple of sculpture' but they were rejected as too extreme.", "male", "Italian"),
    ("Brancusi: Bird in Space", "Constantin Brancusi", 1928, "Bronze (polished)", "Modernism / Romanian", ["sculpture","polished bronze","soaring","abstract","form"], ["bird form","vertical","polished bronze","soaring","pure form"], ["mirror polished bronze","vertical form"], "Museum of Modern Art, MoMA", "A vertical form of polished bronze — the pure essence of flight rather than the image of a bird.", "When Brancusi exported this to the US in 1926, customs refused to classify it as art and taxed it as metal. The case, won by Brancusi, defined modern art legally.", "male", "Romanian"),
    ("Brancusi: The Kiss", "Constantin Brancusi", 1916, "Limestone", "Modernism / Romanian", ["sculpture","geometric","couple","minimal","kiss"], ["two faces","merging forms","geometric","minimal","embrace"], ["rough limestone","carved texture"], "Philadelphia Museum of Art", "Two simplified faces merge into a single geometric block — a kiss reduced to pure essential form.", "Brancusi's radical simplification — two human beings reduced to a cube divided by a line — asks what the essential form of love is.", "male", "Romanian"),
    # ADDITIONAL PERFORMANCE
    ("Yoko Ono: Cut Piece", "Yoko Ono", 1964, "Performance", "Fluxus / Performance", ["performance","female body","vulnerability","audience","participation"], ["audience cuts fabric","passive body","vulnerability","scissors","charity"], ["black fabric","scissors","performance documentation"], "Yamaichi Concert Hall, Kyoto", "Ono sat motionless while audience members were invited to cut away her clothing — each piece to be kept.", "Cut Piece is the most powerful feminist performance artwork. The audience's actions exposed the violence latent in the gaze through actual participation.", "female", "Japanese"),
    ("Hannah Wilke: S.O.S. (Starification Object Series)", "Hannah Wilke", 1974, "Photographs with chewing gum sculpture", "Performance / Feminist", ["performance","feminist","body","selfie precursor","gum sculptures"], ["self-portrait","gum labia shapes on body","feminist","performance"], ["studio photograph","chewing gum forms"], "Museum of Modern Art, MoMA", "Wilke photographed herself with small vaginal-shaped forms made from chewing gum stuck to her skin.", "Wilke confronted the voyeuristic gaze head-on by posing glamorously while subverting the glamour. The gum shapes reference domestic 'women's' labor and vulval form.", "female", "American"),
    ("Adrian Piper: Catalysis IV", "Adrian Piper", 1971, "Performance", "Conceptual / Performance", ["performance","race","identity","public space","provocative"], ["artist on subway","tape over mouth","sign"], ["public space documentation","urban grey"], "New York City streets/subway", "Piper rode the subway with a sign on her back reading 'I am an object' — disrupting the invisible racial and social codes of public space.", "Piper's Catalysis series used her own body as a conceptual tool to expose racism and social norms in public space.", "female", "American"),
    ("Faith Ringgold: American People Series #20: Die", "Faith Ringgold", 1967, "Oil on canvas", "African American / Political", ["political","civil rights","violence","large scale","figurative"], ["racial violence","riot","white and black figures","blood","confrontation"], ["vivid red blood","black and white figures","stark"], "Museum of Modern Art, MoMA", "White and black figures attack each other in a large-scale painting of American racial violence.", "One of the largest and most direct political paintings of the civil rights era. Ringgold painted it in response to James Baldwin's call for urgency.", "female", "American"),
    # MORE ANCIENT
    ("Minoan: Fisherman Fresco", "Unknown Minoan painters", -1600, "Fresco", "Minoan / Ancient", ["fresco","ancient","marine","muscular","naturalistic"], ["fisherman","fish","torso","athletic","Akrotiri"], ["blue","ochre","cream","naturalistic"], "National Archaeological Museum, Athens", "A muscular young fisherman carries two strings of fish — a fragment from the Akrotiri site on Thera (Santorini).", "Preserved by the volcanic eruption of Thera c.1600 BCE. The naturalistic painting of muscles and fish is unique in Bronze Age art.", "unknown", "Greek"),
    ("Egyptian: Nebamun Hunting in the Marshes", "Unknown Egyptian painters", -1350, "Fresco", "New Kingdom Egypt / Ancient", ["fresco","naturalistic","hunting","color","movement"], ["hunting scene","marshes","birds","fish","naturalistic"], ["vivid blue","green","cream","gold"], "British Museum, London", "Nebamun stands in a papyrus marsh throwing a snake-shaped throwing stick at birds, his wife and daughter beside him.", "The most naturalistic ancient Egyptian painting. The fish, birds, and cat are rendered with extraordinary freedom and observation.", "unknown", "Egyptian"),
    ("Etruscan: Tomb of the Leopards Fresco", "Unknown Etruscan painters", -480, "Fresco on rock", "Etruscan / Ancient", ["fresco","banquet","ancient","colorful","narrative"], ["banquet","musicians","dancers","wine","ancient feast"], ["vivid terracotta","black outlines","cream","flat color"], "Tarquinia Necropolis, Italy", "A joyful funerary banquet with musicians, dancers, and diners in vivid flat colors on tomb walls.", "Etruscan tomb paintings are unique in ancient art for their joyful approach to death. The color and vitality are unmatched in the ancient Mediterranean.", "unknown", "Italian"),
    ("Mayan: Bonampak Mural Room 2 (Battle Scene)", "Maya court painters", 790, "Mineral pigment on plaster", "Classic Maya / Mesoamerican", ["mural","battle","violence","historical","detailed"], ["battle","prisoners","blue paint","warriors","torture"], ["vivid blue","red","cream","dramatic"], "Bonampak site, Chiapas (replica at National Museum of Anthropology)", "Warriors in brilliant blue battle costumes take prisoners — the most complete surviving image of Maya warfare.", "The discovery of Bonampak in 1946 revealed that Maya civilization was far more violent than previously thought. The battle murals are unprecedented in American art.", "unknown", "Mayan"),
    # FINAL BATCH - MAKE UP TO 1020+
    ("Takashi Murakami: Tan Tan Bo Puking (a.k.a. Gero Tan)", "Takashi Murakami", 1997, "Acrylic on canvas on board", "Superflat / Japanese", ["superflat","anime","cartoon","surreal","dark"], ["vomiting character","bright color","anime","surreal","dark humor"], ["vivid pink","yellow","anime colors","glossy surface"], "Various collections", "An anime character vomits in a colorful cartoon surrealism.", "Murakami's Superflat theory merges Japanese animation and consumer culture with contemporary art. His factory-produced paintings collapsed the distinction between art and commodity.", "male", "Japanese"),
    ("Damien Hirst: The Impossibility of Death in the Mind of Someone Living (second shark)", "Damien Hirst", 2006, "Tiger shark in formaldehyde", "Young British Artists / Contemporary", ["conceptual","shark","death","formaldehyde","natural history"], ["shark","tank","formaldehyde","death","mortality"], ["grey shark","blue-green fluid","steel"], "Metropolitan Museum of Art, New York", "A replacement tiger shark for the original deteriorated version — raising questions about the identity of artworks.", "When the original shark deteriorated, Hirst replaced it with a new shark. Is it the same artwork? The replacement became another conceptual question.", "male", "British"),
    ("Tracey Emin: Everyone I Have Ever Slept With 1963-1995", "Tracey Emin", 1995, "Appliquéd tent", "Young British Artists", ["installation","confessional","tent","names","autobiography"], ["tent interior","names sewn","intimate","confessional","list"], ["blue tent","white sewn names","intimate interior"], "destroyed in Momart fire, 2004", "A tent with the names of everyone who ever shared a sleeping space with Emin — lovers, family, friends, aborted fetuses — appliquéd inside.", "One of the most personal and powerful works of the YBA generation. Destroyed in the Momart warehouse fire in 2004 along with many YBA works.", "female", "British"),
    ("Glenn Brown: The Loves of Shepherds", "Glenn Brown", 2000, "Oil on panel", "Contemporary British / Figurative", ["appropriation","old master","distorted","contemporary","detailed"], ["old master reworking","distorted forms","highly detailed","classical"], ["dark background","distorted forms","old master palette"], "Various collections", "A reworking of an 18th-century pastoral in which the figures are distorted into grotesque elegance.", "Brown appropriates and distorts Old Master and Symbolist paintings into paintings that look like their sources but are entirely different in effect.", "male", "British"),
    ("George Shaw: Scenes from the Passion: This Inexplicable Longing", "George Shaw", 1997, "Humbrol enamel on board", "Contemporary British / Figurative", ["figurative","english suburban","melancholic","enamel","small scale"], ["suburban house","concrete","dark shrub","melancholy"], ["grey concrete","dark shrub","small scale","suburban"], "Tate Britain, London", "A low-rise suburban building and dark shrub — suburban English melancholy in enamel paint.", "Shaw's Tile Hill estate paintings have an uncanny combination of technical refinement (Humbrol enamel) and suburban content. Nominated for the Turner Prize.", "male", "British"),
]

def make_entry(idx, raw):
    if len(raw) == 12:
        t,a,y,m,mv,s,su,c,mu,d,h,g = raw; n="Unknown"
    else:
        t,a,y,m,mv,s,su,c,mu,d,h,g,n = raw[:13]
    p = period_from_year(y)
    tags = list(dict.fromkeys([x.lower() for x in s[:4]]+[x.lower() for x in su[:3]]+[mv.split("/")[0].strip().lower(),p.lower().split()[0]]))[:12]
    return {"id":idx,"title":t,"artist":a,"year":y,"medium":m,"movement":mv,"style":s,"subject":su,"color_palette":c if isinstance(c,list) else [c],"museum":mu,"description":d,"historical_significance":h,"artist_gender":g,"artist_nationality":n,"period":p,"tags":tags}

def main():
    with open(DATA_PATH) as f: existing = json.load(f)
    start = max(a["id"] for a in existing)+1
    new = []
    for i,r in enumerate(B5):
        try: new.append(make_entry(start+i,r))
        except Exception as e: print(f"Skip {i} ({r[0] if r else '?'}): {e}")
    merged = existing+new
    with open(DATA_PATH,"w",encoding="utf-8") as f: json.dump(merged,f,ensure_ascii=False,indent=2)
    print(f"Done. {len(existing)} + {len(new)} = {len(merged)} total.")

if __name__=="__main__": main()
