/**
 * Gallery registry — comprehensive Chelsea / New York gallery list.
 * The 5 original "featured" galleries have hand-tuned scrapers.
 * All others use the universal Puppeteer scraper.
 */

const GALLERIES = {
  // ─── Tier 1: Featured galleries with custom scrapers ─────────────────────
  'david zwirner': {
    name: 'David Zwirner',
    url: 'https://www.davidzwirner.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  'paula cooper': {
    name: 'Paula Cooper Gallery',
    url: 'https://www.paulacoopergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  'paula cooper gallery': {
    name: 'Paula Cooper Gallery',
    url: 'https://www.paulacoopergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  gagosian: {
    name: 'Gagosian',
    url: 'https://gagosian.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  'hauser & wirth': {
    name: 'Hauser & Wirth',
    url: 'https://www.hauserwirth.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  'hauser and wirth': {
    name: 'Hauser & Wirth',
    url: 'https://www.hauserwirth.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  hauserwirth: {
    name: 'Hauser & Wirth',
    url: 'https://www.hauserwirth.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  pace: {
    name: 'Pace Gallery',
    url: 'https://www.pacegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  'pace gallery': {
    name: 'Pace Gallery',
    url: 'https://www.pacegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },

  // ─── Tier 2: Major Chelsea galleries ─────────────────────────────────────
  '303 gallery': {
    name: '303 Gallery',
    url: 'https://www.303gallery.com',
    exhibitionsPath: '/gallery-exhibitions',
    tier: 'standard',
  },
  '303': {
    name: '303 Gallery',
    url: 'https://www.303gallery.com',
    exhibitionsPath: '/gallery-exhibitions',
    tier: 'standard',
  },
  'gladstone gallery': {
    name: 'Gladstone Gallery',
    url: 'https://www.gladstonegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  gladstone: {
    name: 'Gladstone Gallery',
    url: 'https://www.gladstonegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'luhring augustine': {
    name: 'Luhring Augustine',
    url: 'https://www.luhringaugustine.com',
    exhibitionsPath: '/exhibitions/past',
    tier: 'standard',
  },
  'lehmann maupin': {
    name: 'Lehmann Maupin',
    url: 'https://www.lehmannmaupin.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'andrew kreps': {
    name: 'Andrew Kreps Gallery',
    url: 'https://www.andrewkreps.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'andrew kreps gallery': {
    name: 'Andrew Kreps Gallery',
    url: 'https://www.andrewkreps.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'greene naftali': {
    name: 'Greene Naftali',
    url: 'https://www.greenenaftaligallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'cheim & read': {
    name: 'Cheim & Read',
    url: 'https://www.cheimread.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'cheim and read': {
    name: 'Cheim & Read',
    url: 'https://www.cheimread.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'matthew marks': {
    name: 'Matthew Marks Gallery',
    url: 'https://www.matthewmarks.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'matthew marks gallery': {
    name: 'Matthew Marks Gallery',
    url: 'https://www.matthewmarks.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'marian goodman': {
    name: 'Marian Goodman Gallery',
    url: 'https://www.mariangoodman.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'marian goodman gallery': {
    name: 'Marian Goodman Gallery',
    url: 'https://www.mariangoodman.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'jack shainman': {
    name: 'Jack Shainman Gallery',
    url: 'https://www.jackshainman.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'jack shainman gallery': {
    name: 'Jack Shainman Gallery',
    url: 'https://www.jackshainman.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'anton kern': {
    name: 'Anton Kern Gallery',
    url: 'https://www.antonkerngallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'sean kelly': {
    name: 'Sean Kelly Gallery',
    url: 'https://www.skny.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'sean kelly gallery': {
    name: 'Sean Kelly Gallery',
    url: 'https://www.skny.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'james cohan': {
    name: 'James Cohan Gallery',
    url: 'https://www.jamescohan.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'james cohan gallery': {
    name: 'James Cohan Gallery',
    url: 'https://www.jamescohan.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'peter blum': {
    name: 'Peter Blum Gallery',
    url: 'https://www.peterblumgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'sikkema jenkins': {
    name: 'Sikkema Jenkins & Co.',
    url: 'https://www.sikkemajenkinsco.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'galerie lelong': {
    name: 'Galerie Lelong & Co.',
    url: 'https://www.galerielelong.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'lelong': {
    name: 'Galerie Lelong & Co.',
    url: 'https://www.galerielelong.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'friedman benda': {
    name: 'Friedman Benda',
    url: 'https://www.friedmanbenda.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'albertz benda': {
    name: 'Albertz Benda',
    url: 'https://www.albertzbenda.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'berry campbell': {
    name: 'Berry Campbell',
    url: 'https://www.berrycampbell.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nicola vassell': {
    name: 'Nicola Vassell Gallery',
    url: 'https://www.nicolavassell.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'salon 94': {
    name: 'Salon 94',
    url: 'https://www.salon94.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'petzel': {
    name: 'Petzel Gallery',
    url: 'https://www.petzel.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'petzel gallery': {
    name: 'Petzel Gallery',
    url: 'https://www.petzel.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'tanya bonakdar': {
    name: 'Tanya Bonakdar Gallery',
    url: 'https://www.tanyabonakdargallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'tanya bonakdar gallery': {
    name: 'Tanya Bonakdar Gallery',
    url: 'https://www.tanyabonakdargallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'barbara gladstone': {
    name: 'Gladstone Gallery',
    url: 'https://www.gladstonegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mary boone': {
    name: 'Mary Boone Gallery',
    url: 'https://www.maryboonegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'casey kaplan': {
    name: 'Casey Kaplan Gallery',
    url: 'https://www.caseykaplangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'casey kaplan gallery': {
    name: 'Casey Kaplan Gallery',
    url: 'https://www.caseykaplangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ota fine arts': {
    name: 'Ota Fine Arts',
    url: 'https://www.otafinearts.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'marianne boesky': {
    name: 'Marianne Boesky Gallery',
    url: 'https://www.marianneboeskygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'marianne boesky gallery': {
    name: 'Marianne Boesky Gallery',
    url: 'https://www.marianneboeskygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mitchell-innes & nash': {
    name: 'Mitchell-Innes & Nash',
    url: 'https://www.miandn.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mitchell innes nash': {
    name: 'Mitchell-Innes & Nash',
    url: 'https://www.miandn.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'zwirner & wirth': {
    name: 'David Zwirner',
    url: 'https://www.davidzwirner.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  'pippy houldsworth': {
    name: 'Pippy Houldsworth Gallery',
    url: 'https://www.houldsworth.co.uk',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ryan lee': {
    name: 'Ryan Lee Gallery',
    url: 'https://www.ryanleegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ryan lee gallery': {
    name: 'Ryan Lee Gallery',
    url: 'https://www.ryanleegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'dckt contemporary': {
    name: 'DCKT Contemporary',
    url: 'https://www.dcktcontemporary.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hales gallery': {
    name: 'Hales Gallery',
    url: 'https://www.halesgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hales': {
    name: 'Hales Gallery',
    url: 'https://www.halesgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kaufmann repetto': {
    name: 'Kaufmann Repetto',
    url: 'https://www.kaufmannrepetto.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nara roesler': {
    name: 'Nara Roesler Gallery',
    url: 'https://nararoesler.art',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'cynthia reeves': {
    name: 'Cynthia Reeves Gallery',
    url: 'https://www.cynthiareeves.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'black cube': {
    name: 'Black Cube',
    url: 'https://www.blackcube.art',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'canada gallery': {
    name: 'CANADA',
    url: 'https://www.canadanewyork.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  canada: {
    name: 'CANADA',
    url: 'https://www.canadanewyork.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'half gallery': {
    name: 'Half Gallery',
    url: 'https://www.halfgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'half': {
    name: 'Half Gallery',
    url: 'https://www.halfgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'essex street': {
    name: 'Essex Street',
    url: 'https://www.essexstreet.biz',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ramiken crucible': {
    name: 'Ramiken',
    url: 'https://www.ramiken.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  ramiken: {
    name: 'Ramiken',
    url: 'https://www.ramiken.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'tiong ang': {
    name: 'Tiong Ang Gallery',
    url: 'https://www.tiongangarts.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'm+b gallery': {
    name: 'M+B Gallery',
    url: 'https://www.mbart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'p·p·o·w': {
    name: 'P·P·O·W',
    url: 'https://www.ppowgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  ppow: {
    name: 'P·P·O·W',
    url: 'https://www.ppowgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mulherin': {
    name: 'Mulherin Gallery',
    url: 'https://www.mulheringallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'thomas erben': {
    name: 'Thomas Erben Gallery',
    url: 'https://www.thomaserben.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'edward thorp': {
    name: 'Edward Thorp Gallery',
    url: 'https://www.edwardthorpgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'sundaram tagore': {
    name: 'Sundaram Tagore Gallery',
    url: 'https://www.sundaramtagore.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nancy hoffman': {
    name: 'Nancy Hoffman Gallery',
    url: 'https://www.nancyhoffmangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nancy hoffman gallery': {
    name: 'Nancy Hoffman Gallery',
    url: 'https://www.nancyhoffmangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bryce wolkowitz': {
    name: 'Bryce Wolkowitz Gallery',
    url: 'https://www.brycewolkowitz.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'yancey richardson': {
    name: 'Yancey Richardson Gallery',
    url: 'https://www.yanceyrichardson.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'yancey richardson gallery': {
    name: 'Yancey Richardson Gallery',
    url: 'https://www.yanceyrichardson.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'klowden mann': {
    name: 'Klowden Mann',
    url: 'https://www.klowdenmann.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bill brady': {
    name: 'Bill Brady Gallery',
    url: 'https://www.billbradygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'robischon': {
    name: 'Robischon Gallery',
    url: 'https://www.robischongallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'luxe gallery': {
    name: 'Luxe Gallery',
    url: 'https://www.luxegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mike weiss': {
    name: 'Mike Weiss Gallery',
    url: 'https://www.mikeweissgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'clamp art': {
    name: 'ClampArt',
    url: 'https://www.clampart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  clampart: {
    name: 'ClampArt',
    url: 'https://www.clampart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'invisible exports': {
    name: 'Invisible-Exports',
    url: 'https://www.invisible-exports.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bureau': {
    name: 'Bureau',
    url: 'https://www.bureaunyc.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bortolami': {
    name: 'Bortolami Gallery',
    url: 'https://www.bortolamigallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bortolami gallery': {
    name: 'Bortolami Gallery',
    url: 'https://www.bortolamigallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'marlborough gallery': {
    name: 'Marlborough Gallery',
    url: 'https://www.marlboroughgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  marlborough: {
    name: 'Marlborough Gallery',
    url: 'https://www.marlboroughgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'zürcher gallery': {
    name: 'Zürcher Gallery',
    url: 'https://www.zurcher-gallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'zurcher': {
    name: 'Zürcher Gallery',
    url: 'https://www.zurcher-gallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'flag art foundation': {
    name: 'FLAG Art Foundation',
    url: 'https://www.flagartfoundation.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'michael rosenfeld': {
    name: 'Michael Rosenfeld Gallery',
    url: 'https://www.michaelrosenfeldart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'michael rosenfeld gallery': {
    name: 'Michael Rosenfeld Gallery',
    url: 'https://www.michaelrosenfeldart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'dckt': {
    name: 'DCKT Contemporary',
    url: 'https://www.dcktcontemporary.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kavi gupta': {
    name: 'Kavi Gupta Gallery',
    url: 'https://kavigupta.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kavi gupta gallery': {
    name: 'Kavi Gupta Gallery',
    url: 'https://kavigupta.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },

  // ─── 100 additional galleries ─────────────────────────────────────────────

  // Major international galleries with NYC locations
  'perrotin': {
    name: 'Perrotin',
    url: 'https://www.perrotin.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'perrotin gallery': {
    name: 'Perrotin',
    url: 'https://www.perrotin.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'white cube': {
    name: 'White Cube',
    url: 'https://www.whitecube.com',
    exhibitionsPath: '/exhibitions/new-york',
    tier: 'standard',
  },
  'sprüth magers': {
    name: 'Sprüth Magers',
    url: 'https://www.spruethmagers.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'spruth magers': {
    name: 'Sprüth Magers',
    url: 'https://www.spruethmagers.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'almine rech': {
    name: 'Almine Rech',
    url: 'https://www.alminerech.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'thaddaeus ropac': {
    name: 'Thaddaeus Ropac',
    url: 'https://www.ropac.net',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ropac': {
    name: 'Thaddaeus Ropac',
    url: 'https://www.ropac.net',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'blum': {
    name: 'Blum',
    url: 'https://www.blumgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'blum gallery': {
    name: 'Blum',
    url: 'https://www.blumgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'acquavella': {
    name: 'Acquavella Galleries',
    url: 'https://www.acquavellagalleries.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'acquavella galleries': {
    name: 'Acquavella Galleries',
    url: 'https://www.acquavellagalleries.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mnuchin': {
    name: 'Mnuchin Gallery',
    url: 'https://www.mnuchingallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mnuchin gallery': {
    name: 'Mnuchin Gallery',
    url: 'https://www.mnuchingallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'simon lee': {
    name: 'Simon Lee Gallery',
    url: 'https://www.simonleegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'simon lee gallery': {
    name: 'Simon Lee Gallery',
    url: 'https://www.simonleegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'victoria miro': {
    name: 'Victoria Miro',
    url: 'https://www.victoria-miro.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'lisson gallery': {
    name: 'Lisson Gallery',
    url: 'https://www.lissongallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'lisson': {
    name: 'Lisson Gallery',
    url: 'https://www.lissongallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'van doren waxter': {
    name: 'Van Doren Waxter',
    url: 'https://www.vandorenwaxter.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'lehring augustine': {
    name: 'Luhring Augustine',
    url: 'https://www.luhringaugustine.com',
    exhibitionsPath: '/exhibitions/past',
    tier: 'standard',
  },

  // Tribeca galleries
  '52 walker': {
    name: '52 Walker',
    url: 'https://www.52walker.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'anat ebgi': {
    name: 'Anat Ebgi',
    url: 'https://anatebgi.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'anat ebgi gallery': {
    name: 'Anat Ebgi',
    url: 'https://anatebgi.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'alexander gray': {
    name: 'Alexander Gray Associates',
    url: 'https://www.alexandergray.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'alexander gray associates': {
    name: 'Alexander Gray Associates',
    url: 'https://www.alexandergray.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  '1969 gallery': {
    name: '1969 Gallery',
    url: 'https://www.1969gallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  '125 newbury': {
    name: '125 Newbury',
    url: 'https://www.125newbury.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },

  // Lower East Side & East Village
  'karma': {
    name: 'Karma',
    url: 'https://karmakarma.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'karma gallery': {
    name: 'Karma',
    url: 'https://karmakarma.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'perrotin new york': {
    name: 'Perrotin',
    url: 'https://www.perrotin.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'gordon robichaux': {
    name: 'Gordon Robichaux',
    url: 'https://gordonrobichaux.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'reyes finn': {
    name: 'Reyes | Finn',
    url: 'https://www.reyesfinn.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'reyes | finn': {
    name: 'Reyes | Finn',
    url: 'https://www.reyesfinn.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'martos gallery': {
    name: 'Martos Gallery',
    url: 'https://martosgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'martos': {
    name: 'Martos Gallery',
    url: 'https://martosgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'francois ghebaly': {
    name: 'François Ghebaly',
    url: 'https://www.ghebaly.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ghebaly': {
    name: 'François Ghebaly',
    url: 'https://www.ghebaly.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hannah traore': {
    name: 'Hannah Traore Gallery',
    url: 'https://hannahtraoregallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hannah traore gallery': {
    name: 'Hannah Traore Gallery',
    url: 'https://hannahtraoregallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'olympia': {
    name: 'Olympia',
    url: 'https://www.olympia.art',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'olympia gallery': {
    name: 'Olympia',
    url: 'https://www.olympia.art',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'company gallery': {
    name: 'Company Gallery',
    url: 'https://www.company.gallery',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'company': {
    name: 'Company Gallery',
    url: 'https://www.company.gallery',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'situations': {
    name: 'Situations',
    url: 'https://www.situationsgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'situations gallery': {
    name: 'Situations',
    url: 'https://www.situationsgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'recess': {
    name: 'Recess Art',
    url: 'https://www.recessart.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'thierry goldberg': {
    name: 'Thierry Goldberg Gallery',
    url: 'https://www.thierrygoldberg.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'participant inc': {
    name: 'Participant Inc',
    url: 'https://participantinc.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'participant': {
    name: 'Participant Inc',
    url: 'https://participantinc.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'marlborough contemporary': {
    name: 'Marlborough Contemporary',
    url: 'https://marlboroughcontemporary.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'de buck gallery': {
    name: 'De Buck Gallery',
    url: 'https://www.debuckgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'de buck': {
    name: 'De Buck Gallery',
    url: 'https://www.debuckgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nino mier': {
    name: 'Nino Mier Gallery',
    url: 'https://ninomiergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nino mier gallery': {
    name: 'Nino Mier Gallery',
    url: 'https://ninomiergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'the hole': {
    name: 'The Hole',
    url: 'https://theholenyc.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hole nyc': {
    name: 'The Hole',
    url: 'https://theholenyc.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'taymour grahne': {
    name: 'Taymour Grahne Projects',
    url: 'https://www.taymourgrahne.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'taymour grahne projects': {
    name: 'Taymour Grahne Projects',
    url: 'https://www.taymourgrahne.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'shrine': {
    name: 'Shrine',
    url: 'https://www.shrine.nyc',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'shrine nyc': {
    name: 'Shrine',
    url: 'https://www.shrine.nyc',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'clearing': {
    name: 'Clearing',
    url: 'https://clearinggallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'clearing gallery': {
    name: 'Clearing',
    url: 'https://clearinggallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'club pro': {
    name: 'Club Pro',
    url: 'https://clubprogallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'denny dimin': {
    name: 'Denny Dimin Gallery',
    url: 'https://dennydimin.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'denny dimin gallery': {
    name: 'Denny Dimin Gallery',
    url: 'https://dennydimin.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'dc moore': {
    name: 'DC Moore Gallery',
    url: 'https://www.dcmooregallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'dc moore gallery': {
    name: 'DC Moore Gallery',
    url: 'https://www.dcmooregallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mike kelly': {
    name: 'Mike Weiss Gallery',
    url: 'https://www.mikeweissgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },

  // Midtown & UES
  'gagosian madison': {
    name: 'Gagosian',
    url: 'https://gagosian.com',
    exhibitionsPath: '/exhibitions',
    tier: 'featured',
  },
  'galerie st. etienne': {
    name: 'Galerie St. Etienne',
    url: 'https://www.gseart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hirschl adler': {
    name: 'Hirschl & Adler Galleries',
    url: 'https://www.hirschlandadler.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hirschl & adler': {
    name: 'Hirschl & Adler Galleries',
    url: 'https://www.hirschlandadler.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'luxembourg & dayan': {
    name: 'Luxembourg & Dayan',
    url: 'https://www.luxembourganddayan.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'luxembourg dayan': {
    name: 'Luxembourg & Dayan',
    url: 'https://www.luxembourganddayan.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'dickinson': {
    name: 'Dickinson Gallery',
    url: 'https://www.dickinson.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'vera blue': {
    name: 'Vera Blue Gallery',
    url: 'https://verabluegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'craig starr': {
    name: 'Craig Starr Gallery',
    url: 'https://www.craigstarr.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'craig starr gallery': {
    name: 'Craig Starr Gallery',
    url: 'https://www.craigstarr.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'paul kasmin': {
    name: 'Paul Kasmin Gallery',
    url: 'https://www.paulkasmingallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'paul kasmin gallery': {
    name: 'Paul Kasmin Gallery',
    url: 'https://www.paulkasmingallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'atlas gallery': {
    name: 'Atlas Gallery',
    url: 'https://www.atlasgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hollis taggart': {
    name: 'Hollis Taggart',
    url: 'https://hollistaggart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hollis taggart galleries': {
    name: 'Hollis Taggart',
    url: 'https://hollistaggart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'spanierman modern': {
    name: 'Spanierman Modern',
    url: 'https://www.spaniermanmodern.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'senior & shopmaker': {
    name: 'Senior & Shopmaker Gallery',
    url: 'https://www.seniorandshopmaker.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'senior and shopmaker': {
    name: 'Senior & Shopmaker Gallery',
    url: 'https://www.seniorandshopmaker.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },

  // Additional Chelsea galleries
  'anat ebgi chelsea': {
    name: 'Anat Ebgi',
    url: 'https://anatebgi.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'aspect ratio': {
    name: 'Aspect Ratio',
    url: 'https://aspectratioprojects.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'sims contemporary': {
    name: 'Sims Contemporary',
    url: 'https://www.simscontemporary.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'aca galleries': {
    name: 'ACA Galleries',
    url: 'https://www.acagalleries.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'aca': {
    name: 'ACA Galleries',
    url: 'https://www.acagalleries.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'stefan stux': {
    name: 'Stux + Haller Gallery',
    url: 'https://www.stuxhaller.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'skoto gallery': {
    name: 'Skoto Gallery',
    url: 'https://skotogallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'skoto': {
    name: 'Skoto Gallery',
    url: 'https://skotogallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kathryn markel': {
    name: 'Kathryn Markel Fine Arts',
    url: 'https://www.markelfinearts.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'markel fine arts': {
    name: 'Kathryn Markel Fine Arts',
    url: 'https://www.markelfinearts.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'slag gallery': {
    name: 'SLAG Gallery',
    url: 'https://www.slaggallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'slag': {
    name: 'SLAG Gallery',
    url: 'https://www.slaggallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'anders wahlstedt': {
    name: 'Anders Wahlstedt Fine Art',
    url: 'https://www.anderswahlstedt.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'erin cluley': {
    name: 'Erin Cluley Gallery',
    url: 'https://www.erincluleygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'erin cluley gallery': {
    name: 'Erin Cluley Gallery',
    url: 'https://www.erincluleygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'white columns': {
    name: 'White Columns',
    url: 'https://whitecolumns.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'microscope gallery': {
    name: 'Microscope Gallery',
    url: 'https://microscopegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'microscope': {
    name: 'Microscope Gallery',
    url: 'https://microscopegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'elizabeth dee': {
    name: 'Elizabeth Dee',
    url: 'https://elizabethdee.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'elizabeth dee gallery': {
    name: 'Elizabeth Dee',
    url: 'https://elizabethdee.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bruce silverstein': {
    name: 'Bruce Silverstein Gallery',
    url: 'https://brucesilverstein.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bruce silverstein gallery': {
    name: 'Bruce Silverstein Gallery',
    url: 'https://brucesilverstein.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'prince street gallery': {
    name: 'Prince Street Gallery',
    url: 'https://www.princestreetgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'prince street': {
    name: 'Prince Street Gallery',
    url: 'https://www.princestreetgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bowery gallery': {
    name: 'Bowery Gallery',
    url: 'https://www.bowerygallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bowery': {
    name: 'Bowery Gallery',
    url: 'https://www.bowerygallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'monya rowe': {
    name: 'Monya Rowe Gallery',
    url: 'https://monyarowegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'monya rowe gallery': {
    name: 'Monya Rowe Gallery',
    url: 'https://monyarowegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'talwar gallery': {
    name: 'Talwar Gallery',
    url: 'https://talwargallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'talwar': {
    name: 'Talwar Gallery',
    url: 'https://talwargallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'black cube nomadic': {
    name: 'Black Cube',
    url: 'https://www.blackcube.art',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'storefront for art': {
    name: 'Storefront for Art and Architecture',
    url: 'https://www.storefrontnews.org',
    exhibitionsPath: '/events',
    tier: 'standard',
  },
  'franklin parrasch': {
    name: 'Franklin Parrasch Gallery',
    url: 'https://www.franklinparrasch.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'franklin parrasch gallery': {
    name: 'Franklin Parrasch Gallery',
    url: 'https://www.franklinparrasch.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'salon 94 freemans': {
    name: 'Salon 94',
    url: 'https://www.salon94.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'tilton gallery': {
    name: 'Tilton Gallery',
    url: 'https://www.jacktiltongallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'jack tilton': {
    name: 'Tilton Gallery',
    url: 'https://www.jacktiltongallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'fredericks & freiser': {
    name: 'Fredericks & Freiser',
    url: 'https://www.fredericksfreiser.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'fredericks freiser': {
    name: 'Fredericks & Freiser',
    url: 'https://www.fredericksfreiser.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'lehmann maupin chelsea': {
    name: 'Lehmann Maupin',
    url: 'https://www.lehmannmaupin.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'thomas nickles': {
    name: 'Thomas Nickles Project',
    url: 'https://www.thomasnickles.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'thomas nickles project': {
    name: 'Thomas Nickles Project',
    url: 'https://www.thomasnickles.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'david castillo': {
    name: 'David Castillo Gallery',
    url: 'https://www.castillogallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'david castillo gallery': {
    name: 'David Castillo Gallery',
    url: 'https://www.castillogallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'josh lilley': {
    name: 'Josh Lilley Gallery',
    url: 'https://www.joshlilley.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'josh lilley gallery': {
    name: 'Josh Lilley Gallery',
    url: 'https://www.joshlilley.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'vito schnabel': {
    name: 'Vito Schnabel Gallery',
    url: 'https://www.vitoschnagelgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'vito schnabel gallery': {
    name: 'Vito Schnabel Gallery',
    url: 'https://www.vitoschnagelgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'zeno x': {
    name: 'Zeno X Gallery',
    url: 'https://www.zeno-x.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'night gallery': {
    name: 'Night Gallery',
    url: 'https://www.nightgallery.ca',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'night': {
    name: 'Night Gallery',
    url: 'https://www.nightgallery.ca',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mother gallery': {
    name: 'Mother Gallery',
    url: 'https://www.mothergallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mother': {
    name: 'Mother Gallery',
    url: 'https://www.mothergallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ryan lee': {
    name: 'Ryan Lee Gallery',
    url: 'https://www.ryanleegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'asya geisberg': {
    name: 'Asya Geisberg Gallery',
    url: 'https://asyageisberggallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'asya geisberg gallery': {
    name: 'Asya Geisberg Gallery',
    url: 'https://asyageisberggallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'the journal gallery': {
    name: 'The Journal Gallery',
    url: 'https://www.thejournalgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'journal gallery': {
    name: 'The Journal Gallery',
    url: 'https://www.thejournalgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'rachel uffner': {
    name: 'Rachel Uffner Gallery',
    url: 'https://www.racheluffnergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'rachel uffner gallery': {
    name: 'Rachel Uffner Gallery',
    url: 'https://www.racheluffnergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hionas gallery': {
    name: 'Hionas Gallery',
    url: 'https://www.hionasgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'hionas': {
    name: 'Hionas Gallery',
    url: 'https://www.hionasgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kate werble': {
    name: 'Kate Werble Gallery',
    url: 'https://www.katewerble.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kate werble gallery': {
    name: 'Kate Werble Gallery',
    url: 'https://www.katewerble.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'thierry mugler': {
    name: 'Thierry Goldberg Gallery',
    url: 'https://www.thierrygoldberg.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'art-rite': {
    name: 'Art-Rite',
    url: 'https://www.artrite.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'lucky dragon': {
    name: 'Lucky Dragon',
    url: 'https://www.luckydragon.gallery',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'participant inc.': {
    name: 'Participant Inc',
    url: 'https://participantinc.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'envoy enterprises': {
    name: 'Envoy Enterprises',
    url: 'https://www.envoyenterprises.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'envoy': {
    name: 'Envoy Enterprises',
    url: 'https://www.envoyenterprises.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'body nautical': {
    name: 'Bodega',
    url: 'https://www.bodegaart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bodega': {
    name: 'Bodega',
    url: 'https://www.bodegaart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'lisa cooley': {
    name: 'Lisa Cooley',
    url: 'https://www.lisa-cooley.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'foxy production': {
    name: 'Foxy Production',
    url: 'https://www.foxyproduction.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'foxy': {
    name: 'Foxy Production',
    url: 'https://www.foxyproduction.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bridget donahue': {
    name: 'Bridget Donahue',
    url: 'https://bridgetdonahue.nyc',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bridget donahue gallery': {
    name: 'Bridget Donahue',
    url: 'https://bridgetdonahue.nyc',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'stars gallery': {
    name: 'Stars Gallery',
    url: 'https://www.starsgallery.net',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mulherin gallery': {
    name: 'Mulherin Gallery',
    url: 'https://www.mulheringallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'another year in la': {
    name: 'Another Year in LA',
    url: 'https://www.anotheryearinla.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nicelle beauchene': {
    name: 'Nicelle Beauchene Gallery',
    url: 'https://www.nicellebeauchene.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nicelle beauchene gallery': {
    name: 'Nicelle Beauchene Gallery',
    url: 'https://www.nicellebeauchene.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'the gallery at 5-50': {
    name: 'Sargent\'s Daughters',
    url: 'https://www.sargentsdaughters.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'sargents daughters': {
    name: 'Sargent\'s Daughters',
    url: 'https://www.sargentsdaughters.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  "sargent's daughters": {
    name: 'Sargent\'s Daughters',
    url: 'https://www.sargentsdaughters.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'left field gallery': {
    name: 'Left Field',
    url: 'https://www.leftfieldnyc.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'spruce street gallery': {
    name: 'Spruce Street Gallery',
    url: 'https://www.sprucestreetgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'lehmann maupin new york': {
    name: 'Lehmann Maupin',
    url: 'https://www.lehmannmaupin.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'heather james': {
    name: 'Heather James Fine Art',
    url: 'https://www.heatherjames.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'heather james fine art': {
    name: 'Heather James Fine Art',
    url: 'https://www.heatherjames.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ameringer mcenery yohe': {
    name: 'Ameringer | McEnery | Yohe',
    url: 'https://www.amy-gallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },

  // ─── Chelsea member/co-op galleries ───────────────────────────────────────
  'atlantic gallery': {
    name: 'Atlantic Gallery',
    url: 'https://atlanticgallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'atlantic': {
    name: 'Atlantic Gallery',
    url: 'https://atlanticgallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'carter burden gallery': {
    name: 'Carter Burden Gallery',
    url: 'https://www.carterburdengallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'carter burden': {
    name: 'Carter Burden Gallery',
    url: 'https://www.carterburdengallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'viridian artists': {
    name: 'Viridian Artists',
    url: 'https://www.viridianartists.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'viridian': {
    name: 'Viridian Artists',
    url: 'https://www.viridianartists.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'high line nine': {
    name: 'High Line Nine Galleries',
    url: 'https://highlinenine.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'high line nine galleries': {
    name: 'High Line Nine Galleries',
    url: 'https://highlinenine.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ceres gallery': {
    name: 'Ceres Gallery',
    url: 'https://ceresgallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ceres': {
    name: 'Ceres Gallery',
    url: 'https://ceresgallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'pleiades gallery': {
    name: 'Pleiades Gallery',
    url: 'https://www.pleiadesgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'pleiades': {
    name: 'Pleiades Gallery',
    url: 'https://www.pleiadesgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'blue mountain gallery': {
    name: 'Blue Mountain Gallery',
    url: 'https://www.bluemountaingallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'blue mountain': {
    name: 'Blue Mountain Gallery',
    url: 'https://www.bluemountaingallery.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'the painting center': {
    name: 'The Painting Center',
    url: 'https://www.thepaintingcenter.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'painting center': {
    name: 'The Painting Center',
    url: 'https://www.thepaintingcenter.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'cue art foundation': {
    name: 'CUE Art Foundation',
    url: 'https://cueartfoundation.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'cue': {
    name: 'CUE Art Foundation',
    url: 'https://cueartfoundation.org',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },

  // ─── Photography & specialist Chelsea galleries ────────────────────────────
  'benrubi gallery': {
    name: 'Benrubi Gallery',
    url: 'https://www.benrubigallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'benrubi': {
    name: 'Benrubi Gallery',
    url: 'https://www.benrubigallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'deborah bell photographs': {
    name: 'Deborah Bell Photographs',
    url: 'https://www.deborahbellphotographs.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'deborah bell': {
    name: 'Deborah Bell Photographs',
    url: 'https://www.deborahbellphotographs.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'rick wester fine art': {
    name: 'Rick Wester Fine Art',
    url: 'https://www.rickwesterfineart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'rick wester': {
    name: 'Rick Wester Fine Art',
    url: 'https://www.rickwesterfineart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'robert mann gallery': {
    name: 'Robert Mann Gallery',
    url: 'https://robertmann.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'robert mann': {
    name: 'Robert Mann Gallery',
    url: 'https://robertmann.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'laurence miller gallery': {
    name: 'Laurence Miller Gallery',
    url: 'http://www.laurencemillergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'laurence miller': {
    name: 'Laurence Miller Gallery',
    url: 'http://www.laurencemillergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'yossi milo gallery': {
    name: 'Yossi Milo Gallery',
    url: 'https://yossimilo.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'yossi milo': {
    name: 'Yossi Milo Gallery',
    url: 'https://yossimilo.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },

  // ─── Mid-size Chelsea galleries ────────────────────────────────────────────
  'fergus mccaffrey': {
    name: 'Fergus McCaffrey',
    url: 'https://fergusmccaffrey.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'field projects': {
    name: 'Field Projects',
    url: 'https://www.fieldprojectsgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'morgan lehman gallery': {
    name: 'Morgan Lehman Gallery',
    url: 'https://morganlehmangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'morgan lehman': {
    name: 'Morgan Lehman Gallery',
    url: 'https://morganlehmangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'miles mcenery gallery': {
    name: 'Miles McEnery Gallery',
    url: 'https://www.milesmcenery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'miles mcenery': {
    name: 'Miles McEnery Gallery',
    url: 'https://www.milesmcenery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'tina kim gallery': {
    name: 'Tina Kim Gallery',
    url: 'https://tinakimgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'tina kim': {
    name: 'Tina Kim Gallery',
    url: 'https://tinakimgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'skarstedt gallery': {
    name: 'Skarstedt Gallery',
    url: 'https://www.skarstedt.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'skarstedt': {
    name: 'Skarstedt Gallery',
    url: 'https://www.skarstedt.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'susan inglett gallery': {
    name: 'Susan Inglett Gallery',
    url: 'https://www.inglettgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'susan inglett': {
    name: 'Susan Inglett Gallery',
    url: 'https://www.inglettgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'garth greenan gallery': {
    name: 'Garth Greenan Gallery',
    url: 'https://www.garthgreenan.com',
    exhibitionsPath: '/exhibitions/current',
    tier: 'standard',
  },
  'garth greenan': {
    name: 'Garth Greenan Gallery',
    url: 'https://www.garthgreenan.com',
    exhibitionsPath: '/exhibitions/current',
    tier: 'standard',
  },
  'kurimanzutto': {
    name: 'Kurimanzutto',
    url: 'https://www.kurimanzutto.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'templon': {
    name: 'Templon',
    url: 'https://www.templon.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'templon gallery': {
    name: 'Templon',
    url: 'https://www.templon.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'harpers gallery': {
    name: "Harper's Gallery",
    url: 'https://www.harpersgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  "harper's gallery": {
    name: "Harper's Gallery",
    url: 'https://www.harpersgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  "harper's": {
    name: "Harper's Gallery",
    url: 'https://www.harpersgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'dinner gallery': {
    name: 'Dinner Gallery',
    url: 'https://dinnergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'dinner': {
    name: 'Dinner Gallery',
    url: 'https://dinnergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kravets wehby gallery': {
    name: 'Kravets Wehby Gallery',
    url: 'https://www.kravetswehbygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kravets wehby': {
    name: 'Kravets Wehby Gallery',
    url: 'https://www.kravetswehbygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ricco maresca gallery': {
    name: 'Ricco/Maresca Gallery',
    url: 'https://www.riccomaresca.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ricco maresca': {
    name: 'Ricco/Maresca Gallery',
    url: 'https://www.riccomaresca.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ross kramer': {
    name: 'Ross+Kramer Gallery',
    url: 'https://www.rkgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ross+kramer': {
    name: 'Ross+Kramer Gallery',
    url: 'https://www.rkgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'unix gallery': {
    name: 'Unix Gallery',
    url: 'https://www.unixgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'unix': {
    name: 'Unix Gallery',
    url: 'https://www.unixgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'gallery henoch': {
    name: 'Gallery Henoch',
    url: 'https://www.galleryhenoch.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'henoch': {
    name: 'Gallery Henoch',
    url: 'https://www.galleryhenoch.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'david kordansky gallery': {
    name: 'David Kordansky Gallery',
    url: 'https://www.davidkordanskygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'david kordansky': {
    name: 'David Kordansky Gallery',
    url: 'https://www.davidkordanskygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ethan cohen gallery': {
    name: 'Ethan Cohen Gallery',
    url: 'https://www.ecfa.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'ethan cohen': {
    name: 'Ethan Cohen Gallery',
    url: 'https://www.ecfa.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nohra haime gallery': {
    name: 'Nohra Haime Gallery',
    url: 'https://www.nohrahaimegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nohra haime': {
    name: 'Nohra Haime Gallery',
    url: 'https://www.nohrahaimegallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'taglialatella galleries': {
    name: 'Taglialatella Galleries',
    url: 'https://www.taglialatellagalleries.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'taglialatella': {
    name: 'Taglialatella Galleries',
    url: 'https://www.taglialatellagalleries.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'sears peyton gallery': {
    name: 'Sears Peyton Gallery',
    url: 'https://www.searspeyton.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'sears peyton': {
    name: 'Sears Peyton Gallery',
    url: 'https://www.searspeyton.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'amsterdam whitney gallery': {
    name: 'Amsterdam Whitney Gallery',
    url: 'https://www.amsterdamwhitneygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'amsterdam whitney': {
    name: 'Amsterdam Whitney Gallery',
    url: 'https://www.amsterdamwhitneygallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'anna zorina gallery': {
    name: 'Anna Zorina Gallery',
    url: 'https://www.annazorinagallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'anna zorina': {
    name: 'Anna Zorina Gallery',
    url: 'https://www.annazorinagallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'c24 gallery': {
    name: 'C24 Gallery',
    url: 'https://www.c24gallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'c24': {
    name: 'C24 Gallery',
    url: 'https://www.c24gallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'cavalier galleries': {
    name: 'Cavalier Galleries',
    url: 'https://www.cavaliergalleries.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'cavalier': {
    name: 'Cavalier Galleries',
    url: 'https://www.cavaliergalleries.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'cavin-morris gallery': {
    name: 'Cavin-Morris Gallery',
    url: 'https://www.cavinmorris.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'cavin morris': {
    name: 'Cavin-Morris Gallery',
    url: 'https://www.cavinmorris.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'caelum gallery': {
    name: 'Caelum Gallery',
    url: 'https://www.caelumgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'caelum': {
    name: 'Caelum Gallery',
    url: 'https://www.caelumgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'daniel cooney fine art': {
    name: 'Daniel Cooney Fine Art',
    url: 'https://www.danielcooneyfineart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'daniel cooney': {
    name: 'Daniel Cooney Fine Art',
    url: 'https://www.danielcooneyfineart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'dobrinka salzman gallery': {
    name: 'Dobrinka Salzman Gallery',
    url: 'https://www.dobrinkasalzman.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'dobrinka salzman': {
    name: 'Dobrinka Salzman Gallery',
    url: 'https://www.dobrinkasalzman.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'fremin gallery': {
    name: 'Fremin Gallery',
    url: 'https://fremingallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'fremin': {
    name: 'Fremin Gallery',
    url: 'https://fremingallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'george billis gallery': {
    name: 'George Billis Gallery',
    url: 'https://www.georgebillis.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'george billis': {
    name: 'George Billis Gallery',
    url: 'https://www.georgebillis.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'jim kempner fine art': {
    name: 'Jim Kempner Fine Art',
    url: 'https://www.jimkempnerfineart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'jim kempner': {
    name: 'Jim Kempner Fine Art',
    url: 'https://www.jimkempnerfineart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kutlesa gallery': {
    name: 'Kutlesa',
    url: 'https://www.kutlesagallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'kutlesa': {
    name: 'Kutlesa',
    url: 'https://www.kutlesagallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'joanne artman gallery': {
    name: 'JoAnne Artman Gallery',
    url: 'https://www.joanneartmangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'joanne artman': {
    name: 'JoAnne Artman Gallery',
    url: 'https://www.joanneartmangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'gemini gel': {
    name: 'Gemini G.E.L. at Joni Moisant Weyl',
    url: 'https://joniweyl.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'gemini g.e.l.': {
    name: 'Gemini G.E.L. at Joni Moisant Weyl',
    url: 'https://joniweyl.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'montague contemporary': {
    name: 'Montague Contemporary',
    url: 'https://www.montaguecontemporary.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'montague': {
    name: 'Montague Contemporary',
    url: 'https://www.montaguecontemporary.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'montserrat contemporary art': {
    name: 'Montserrat Contemporary Art',
    url: 'https://www.montserrat.us',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'montserrat': {
    name: 'Montserrat Contemporary Art',
    url: 'https://www.montserrat.us',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'pictor gallery': {
    name: 'Pictor Gallery',
    url: 'https://www.pictorgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'pictor': {
    name: 'Pictor Gallery',
    url: 'https://www.pictorgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nicole klagsbrun': {
    name: 'Nicole Klagsbrun',
    url: 'https://www.nicoleklagsbrun.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'winston wachter fine art': {
    name: 'Winston Wächter Fine Art',
    url: 'https://newyork.winstonwachter.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'winston wächter': {
    name: 'Winston Wächter Fine Art',
    url: 'https://newyork.winstonwachter.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'white space chelsea': {
    name: 'White Space Chelsea',
    url: 'https://whitespacechelsea.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mary ryan gallery': {
    name: 'Mary Ryan Gallery',
    url: 'https://maryryangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'mary ryan': {
    name: 'Mary Ryan Gallery',
    url: 'https://maryryangallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'loretta howard gallery': {
    name: 'Loretta Howard Gallery',
    url: 'https://www.lorettahoward.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'loretta howard': {
    name: 'Loretta Howard Gallery',
    url: 'https://www.lorettahoward.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nancy margolis gallery': {
    name: 'Nancy Margolis Gallery',
    url: 'https://www.nancymargolisgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nancy margolis': {
    name: 'Nancy Margolis Gallery',
    url: 'https://www.nancymargolisgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'walter wickiser gallery': {
    name: 'Walter Wickiser Gallery',
    url: 'https://www.walterwickisergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'walter wickiser': {
    name: 'Walter Wickiser Gallery',
    url: 'https://www.walterwickisergallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  '532 gallery': {
    name: '532 Gallery Thomas Jaeckel',
    url: 'https://www.532gallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'thomas jaeckel': {
    name: '532 Gallery Thomas Jaeckel',
    url: 'https://www.532gallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'lincoln glenn': {
    name: 'Lincoln Glenn',
    url: 'https://www.lincolnglenn.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bill hodges gallery': {
    name: 'Bill Hodges Gallery',
    url: 'https://www.billhodgesgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'bill hodges': {
    name: 'Bill Hodges Gallery',
    url: 'https://www.billhodgesgallery.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'nagas': {
    name: 'Nagas',
    url: 'https://www.nagasart.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'sikkema malloy jenkins': {
    name: 'Sikkema Malloy Jenkins & Co.',
    url: 'https://www.smjny.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'smj': {
    name: 'Sikkema Malloy Jenkins & Co.',
    url: 'https://www.smjny.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'pace prints': {
    name: 'Pace Prints',
    url: 'https://paceprints.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
  'taglialatella galleries new york': {
    name: 'Taglialatella Galleries',
    url: 'https://www.taglialatellagalleries.com',
    exhibitionsPath: '/exhibitions',
    tier: 'standard',
  },
};

/**
 * Return a canonical gallery config from a user query string.
 * Tries exact match, then partial match.
 */
function findGallery(query) {
  const normalized = query.trim().toLowerCase();

  if (GALLERIES[normalized]) return GALLERIES[normalized];

  // Partial containment match
  for (const [key, gallery] of Object.entries(GALLERIES)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return gallery;
    }
  }
  return null;
}

/**
 * Return the deduplicated public gallery list (one entry per unique name).
 */
function listGalleries() {
  const seen = new Set();
  return Object.values(GALLERIES).filter((g) => {
    if (seen.has(g.name)) return false;
    seen.add(g.name);
    return true;
  });
}

module.exports = { GALLERIES, findGallery, listGalleries };
